      subroutine vbic_4T_it_cf_fj(p,Vbei,Vbex,Vbci,Vbep,Vbcp,Vrcx,Vbcx
     +,Vrci,Vrbx,Vrbi,Vre,Vrbp,Vrs,Vbe,Vbc,Ibe,Ibe_Vbei,Ibex,Ibex_Vbex
     +,Itzf,Itzf_Vbei,Itzf_Vbci,Itzr,Itzr_Vbci,Itzr_Vbei,Ibc,Ibc_Vbci
     +,Ibc_Vbei,Ibep,Ibep_Vbep,Ircx,Ircx_Vrcx,Irci,Irci_Vrci,Irci_Vbci
     +,Irci_Vbcx,Irbx,Irbx_Vrbx,Irbi,Irbi_Vrbi,Irbi_Vbei,Irbi_Vbci,Ire
     +,Ire_Vre,Irbp,Irbp_Vrbp,Irbp_Vbep,Irbp_Vbci,Qbe,Qbe_Vbei,Qbe_Vbci
     +,Qbex,Qbex_Vbex,Qbc,Qbc_Vbci,Qbcx,Qbcx_Vbcx,Qbep,Qbep_Vbep
     +,Qbep_Vbci,Qbeo,Qbeo_Vbe,Qbco,Qbco_Vbc,Ibcp,Ibcp_Vbcp,Iccp
     +,Iccp_Vbep,Iccp_Vbci,Iccp_Vbcp,Irs,Irs_Vrs,Qbcp,Qbcp_Vbcp,SCALE)
      implicit double precision (a-z)
      double precision p(108)
c
c     Function and derivative code
c
      Vtv=1.380662e-23*(2.731500e+02+p(1))/1.602189e-19
      if(p(52).GT.0.0)then
         IVEF=1.0/p(52)
      else
         IVEF=0.0
      endif
      if(p(53).GT.0.0)then
         IVER=1.0/p(53)
      else
         IVER=0.0
      endif
      if(p(54).GT.0.0)then
         IIKF=1.0/p(54)
      else
         IIKF=0.0
      endif
      if(p(55).GT.0.0)then
         IIKR=1.0/p(55)
      else
         IIKR=0.0
      endif
      if(p(56).GT.0.0)then
         IIKP=1.0/p(56)
      else
         IIKP=0.0
      endif
      if(p(4).GT.0.0)then
         IVO=1.0/p(4)
      else
         IVO=0.0
      endif
      if(p(6).GT.0.0)then
         IHRCF=1.0/p(6)
      else
         IHRCF=0.0
      endif
      if(p(60).GT.0.0)then
         IVTF=1.0/p(60)
      else
         IVTF=0.0
      endif
      if(p(61).GT.0.0)then
         IITF=1.0/p(61)
      else
         IITF=0.0
      endif
      if(p(61).GT.0.0)then
         slTF=0.0
      else
         slTF=1.0
      endif
      dv0=-p(18)*p(15)
      if(p(20).LE.0.0)then
         dvh=Vbei+dv0
         dvh_Vbei=1.0
         if(dvh.GT.0.0)then
            xvar1=(1.0-p(15))
            xvar2=(-1.0-p(19))
            pwq=xvar1**xvar2
            qlo=p(18)*(1.0-pwq*(1.0-p(15))*(1.0-p(15)))/(1.0-p(19))
            qlo_Vbei=0.0
            qhi=dvh*(1.0-p(15)+0.5*p(19)*dvh/p(18))*pwq
            qhi_dvh=(0.5*dvh*p(19)/p(18)-p(15)+1.0)*pwq+0.5*dvh*p(19)*pw
     +q/p(18)
            qhi_Vbei=qhi_dvh*dvh_Vbei
         else
            xvar1=(1.0-Vbei/p(18))
            xvar1_Vbei=-1.0/p(18)
            xvar2=(1.0-p(19))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbei=xvar3_xvar1*xvar1_Vbei
            qlo=p(18)*(1.0-xvar3)/(1.0-p(19))
            qlo_xvar3=-p(18)/(1.0-p(19))
            qlo_Vbei=qlo_xvar3*xvar3_Vbei
            qhi=0.0
            qhi_Vbei=0.0
         endif
         qdbe=qlo+qhi
         qdbe_qlo=1.0
         qdbe_qhi=1.0
         qdbe_Vbei=qdbe_qlo*qlo_Vbei
         qdbe_Vbei=qdbe_Vbei+qdbe_qhi*qhi_Vbei
      else
         mv0=sqrt(dv0*dv0+4.0*p(20)*p(20))
         vl0=-0.5*(dv0+mv0)
         xvar1=(1.0-vl0/p(18))
         xvar2=(1.0-p(19))
         xvar3=xvar1**xvar2
         q0=-p(18)*xvar3/(1.0-p(19))
         dv=Vbei+dv0
         dv_Vbei=1.0
         mv=sqrt(dv*dv+4.0*p(20)*p(20))
         mv_dv=dv/sqrt((dv*dv)+4.0*(p(20)*p(20)))
         mv_Vbei=mv_dv*dv_Vbei
         vl=0.5*(dv-mv)-dv0
         vl_dv=0.5
         vl_mv=-0.5
         vl_Vbei=vl_dv*dv_Vbei
         vl_Vbei=vl_Vbei+vl_mv*mv_Vbei
         xvar1=(1.0-vl/p(18))
         xvar1_vl=-1.0/p(18)
         xvar1_Vbei=xvar1_vl*vl_Vbei
         xvar2=(1.0-p(19))
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vbei=xvar3_xvar1*xvar1_Vbei
         qlo=-p(18)*xvar3/(1.0-p(19))
         qlo_xvar3=-p(18)/(1.0-p(19))
         qlo_Vbei=qlo_xvar3*xvar3_Vbei
         xvar1=(1.0-p(15))
         xvar2=(-p(19))
         xvar3=xvar1**xvar2
         qdbe=qlo+xvar3*(Vbei-vl+vl0)-q0
         qdbe_qlo=1.0
         qdbe_Vbei=xvar3
         qdbe_vl=-xvar3
         qdbe_Vbei=qdbe_Vbei+qdbe_qlo*qlo_Vbei
         qdbe_Vbei=qdbe_Vbei+qdbe_vl*vl_Vbei
      endif
      dv0=-p(18)*p(15)
      if(p(20).LE.0.0)then
         dvh=Vbex+dv0
         dvh_Vbex=1.0
         if(dvh.GT.0.0)then
            xvar1=(1.0-p(15))
            xvar2=(-1.0-p(19))
            pwq=xvar1**xvar2
            qlo=p(18)*(1.0-pwq*(1.0-p(15))*(1.0-p(15)))/(1.0-p(19))
            qlo_Vbex=0.0
            qhi=dvh*(1.0-p(15)+0.5*p(19)*dvh/p(18))*pwq
            qhi_dvh=(0.5*dvh*p(19)/p(18)-p(15)+1.0)*pwq+0.5*dvh*p(19)*pw
     +q/p(18)
            qhi_Vbex=qhi_dvh*dvh_Vbex
         else
            xvar1=(1.0-Vbex/p(18))
            xvar1_Vbex=-1.0/p(18)
            xvar2=(1.0-p(19))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbex=xvar3_xvar1*xvar1_Vbex
            qlo=p(18)*(1.0-xvar3)/(1.0-p(19))
            qlo_xvar3=-p(18)/(1.0-p(19))
            qlo_Vbex=qlo_xvar3*xvar3_Vbex
            qhi=0.0
            qhi_Vbex=0.0
         endif
         qdbex=qlo+qhi
         qdbex_qlo=1.0
         qdbex_qhi=1.0
         qdbex_Vbex=qdbex_qlo*qlo_Vbex
         qdbex_Vbex=qdbex_Vbex+qdbex_qhi*qhi_Vbex
      else
         mv0=sqrt(dv0*dv0+4.0*p(20)*p(20))
         vl0=-0.5*(dv0+mv0)
         xvar1=(1.0-vl0/p(18))
         xvar2=(1.0-p(19))
         xvar3=xvar1**xvar2
         q0=-p(18)*xvar3/(1.0-p(19))
         dv=Vbex+dv0
         dv_Vbex=1.0
         mv=sqrt(dv*dv+4.0*p(20)*p(20))
         mv_dv=dv/sqrt((dv*dv)+4.0*(p(20)*p(20)))
         mv_Vbex=mv_dv*dv_Vbex
         vl=0.5*(dv-mv)-dv0
         vl_dv=0.5
         vl_mv=-0.5
         vl_Vbex=vl_dv*dv_Vbex
         vl_Vbex=vl_Vbex+vl_mv*mv_Vbex
         xvar1=(1.0-vl/p(18))
         xvar1_vl=-1.0/p(18)
         xvar1_Vbex=xvar1_vl*vl_Vbex
         xvar2=(1.0-p(19))
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vbex=xvar3_xvar1*xvar1_Vbex
         qlo=-p(18)*xvar3/(1.0-p(19))
         qlo_xvar3=-p(18)/(1.0-p(19))
         qlo_Vbex=qlo_xvar3*xvar3_Vbex
         xvar1=(1.0-p(15))
         xvar2=(-p(19))
         xvar3=xvar1**xvar2
         qdbex=qlo+xvar3*(Vbex-vl+vl0)-q0
         qdbex_qlo=1.0
         qdbex_Vbex=xvar3
         qdbex_vl=-xvar3
         qdbex_Vbex=qdbex_Vbex+qdbex_qlo*qlo_Vbex
         qdbex_Vbex=qdbex_Vbex+qdbex_vl*vl_Vbex
      endif
      dv0=-p(25)*p(15)
      if(p(27).LE.0.0)then
         dvh=Vbci+dv0
         dvh_Vbci=1.0
         if(dvh.GT.0.0)then
            xvar1=(1.0-p(15))
            xvar2=(-1.0-p(26))
            pwq=xvar1**xvar2
            qlo=p(25)*(1.0-pwq*(1.0-p(15))*(1.0-p(15)))/(1.0-p(26))
            qlo_Vbci=0.0
            qhi=dvh*(1.0-p(15)+0.5*p(26)*dvh/p(25))*pwq
            qhi_dvh=(0.5*dvh*p(26)/p(25)-p(15)+1.0)*pwq+0.5*dvh*p(26)*pw
     +q/p(25)
            qhi_Vbci=qhi_dvh*dvh_Vbci
         else
            if((p(86).GT.0.0).AND.(Vbci.LT.-p(86)))then
               xvar1=(1.0+p(86)/p(25))
               xvar2=(1.0-p(26))
               xvar3=xvar1**xvar2
               qlo=p(25)*(1.0-xvar3*(1.0-((1.0-p(26))*(Vbci+p(86)))/(p(2
     +5)+p(86))))/(1.0-p(26))
               qlo_Vbci=p(25)*xvar3/(p(86)+p(25))
            else
               xvar1=(1.0-Vbci/p(25))
               xvar1_Vbci=-1.0/p(25)
               xvar2=(1.0-p(26))
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
               qlo=p(25)*(1.0-xvar3)/(1.0-p(26))
               qlo_xvar3=-p(25)/(1.0-p(26))
               qlo_Vbci=qlo_xvar3*xvar3_Vbci
            endif
            qhi=0.0
            qhi_Vbci=0.0
         endif
         qdbc=qlo+qhi
         qdbc_qlo=1.0
         qdbc_qhi=1.0
         qdbc_Vbci=qdbc_qlo*qlo_Vbci
         qdbc_Vbci=qdbc_Vbci+qdbc_qhi*qhi_Vbci
      else
         if((p(86).GT.0.0).AND.(p(87).GT.0.0))then
            vn0=(p(86)+dv0)/(p(86)-dv0)
            vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*p(27)*p(27))+sqrt
     +((vn0+1.0)*(vn0+1.0)+4.0*p(87)*p(87)))
            vl0=0.5*(vnl0*(p(86)-dv0)-p(86)-dv0)
            xvar1=(1.0-vl0/p(25))
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            qlo0=p(25)*(1.0-xvar3)/(1.0-p(26))
            vn=(2.0*Vbci+p(86)+dv0)/(p(86)-dv0)
            vn_Vbci=2.0/(p(86)-dv0)
            vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*p(27)*p(27))+sqrt((vn
     ++1.0)*(vn+1.0)+4.0*p(87)*p(87)))
            vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(p(87)*p(87)))+sqrt
     +(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(27))))-2.0*vn*((vn+1.0)/sqrt(((v
     +n+1.0)*(vn+1.0))+4.0*(p(87)*p(87)))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.
     +0))+4.0*(p(27)*p(27))))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(p(87)*p(87
     +)))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(27))))*(sqrt(((vn+1.0)*(
     +vn+1.0))+4.0*(p(87)*p(87)))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(
     +27)))))
            vnl_Vbci=vnl_vn*vn_Vbci
            vl=0.5*(vnl*(p(86)-dv0)-p(86)-dv0)
            vl_vnl=0.5*(p(86)-dv0)
            vl_Vbci=vl_vnl*vnl_Vbci
            xvar1=(1.0-vl/p(25))
            xvar1_vl=-1.0/p(25)
            xvar1_Vbci=xvar1_vl*vl_Vbci
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
            qlo=p(25)*(1.0-xvar3)/(1.0-p(26))
            qlo_xvar3=-p(25)/(1.0-p(26))
            qlo_Vbci=qlo_xvar3*xvar3_Vbci
            sel=0.5*(vnl+1.0)
            sel_vnl=0.5
            sel_Vbci=sel_vnl*vnl_Vbci
            xvar1=(1.0+p(86)/p(25))
            xvar2=(-p(26))
            crt=xvar1**xvar2
            xvar1=(1.0+dv0/p(25))
            xvar2=(-p(26))
            cmx=xvar1**xvar2
            cl=(1.0-sel)*crt+sel*cmx
            cl_sel=cmx-crt
            cl_Vbci=cl_sel*sel_Vbci
            ql=(Vbci-vl+vl0)*cl
            ql_Vbci=cl
            ql_vl=-cl
            ql_cl=vl0-vl+Vbci
            ql_Vbci=ql_Vbci+ql_vl*vl_Vbci
            ql_Vbci=ql_Vbci+ql_cl*cl_Vbci
            qdbc=ql+qlo-qlo0
            qdbc_ql=1.0
            qdbc_qlo=1.0
            qdbc_Vbci=qdbc_ql*ql_Vbci
            qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci
         else
            mv0=sqrt(dv0*dv0+4.0*p(27)*p(27))
            vl0=-0.5*(dv0+mv0)
            xvar1=(1.0-vl0/p(25))
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            q0=-p(25)*xvar3/(1.0-p(26))
            dv=Vbci+dv0
            dv_Vbci=1.0
            mv=sqrt(dv*dv+4.0*p(27)*p(27))
            mv_dv=dv/sqrt((dv*dv)+4.0*(p(27)*p(27)))
            mv_Vbci=mv_dv*dv_Vbci
            vl=0.5*(dv-mv)-dv0
            vl_dv=0.5
            vl_mv=-0.5
            vl_Vbci=vl_dv*dv_Vbci
            vl_Vbci=vl_Vbci+vl_mv*mv_Vbci
            xvar1=(1.0-vl/p(25))
            xvar1_vl=-1.0/p(25)
            xvar1_Vbci=xvar1_vl*vl_Vbci
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
            qlo=-p(25)*xvar3/(1.0-p(26))
            qlo_xvar3=-p(25)/(1.0-p(26))
            qlo_Vbci=qlo_xvar3*xvar3_Vbci
            xvar1=(1.0-p(15))
            xvar2=(-p(26))
            xvar3=xvar1**xvar2
            qdbc=qlo+xvar3*(Vbci-vl+vl0)-q0
            qdbc_qlo=1.0
            qdbc_Vbci=xvar3
            qdbc_vl=-xvar3
            qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci
            qdbc_Vbci=qdbc_Vbci+qdbc_vl*vl_Vbci
         endif
      endif
      dv0=-p(25)*p(15)
      if(p(27).LE.0.0)then
         dvh=Vbep+dv0
         dvh_Vbep=1.0
         if(dvh.GT.0.0)then
            xvar1=(1.0-p(15))
            xvar2=(-1.0-p(26))
            pwq=xvar1**xvar2
            qlo=p(25)*(1.0-pwq*(1.0-p(15))*(1.0-p(15)))/(1.0-p(26))
            qlo_Vbep=0.0
            qhi=dvh*(1.0-p(15)+0.5*p(26)*dvh/p(25))*pwq
            qhi_dvh=(0.5*dvh*p(26)/p(25)-p(15)+1.0)*pwq+0.5*dvh*p(26)*pw
     +q/p(25)
            qhi_Vbep=qhi_dvh*dvh_Vbep
         else
            if((p(86).GT.0.0).AND.(Vbep.LT.-p(86)))then
               xvar1=(1.0+p(86)/p(25))
               xvar2=(1.0-p(26))
               xvar3=xvar1**xvar2
               qlo=p(25)*(1.0-xvar3*(1.0-((1.0-p(26))*(Vbep+p(86)))/(p(2
     +5)+p(86))))/(1.0-p(26))
               qlo_Vbep=p(25)*xvar3/(p(86)+p(25))
            else
               xvar1=(1.0-Vbep/p(25))
               xvar1_Vbep=-1.0/p(25)
               xvar2=(1.0-p(26))
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
               qlo=p(25)*(1.0-xvar3)/(1.0-p(26))
               qlo_xvar3=-p(25)/(1.0-p(26))
               qlo_Vbep=qlo_xvar3*xvar3_Vbep
            endif
            qhi=0.0
            qhi_Vbep=0.0
         endif
         qdbep=qlo+qhi
         qdbep_qlo=1.0
         qdbep_qhi=1.0
         qdbep_Vbep=qdbep_qlo*qlo_Vbep
         qdbep_Vbep=qdbep_Vbep+qdbep_qhi*qhi_Vbep
      else
         if((p(86).GT.0.0).AND.(p(87).GT.0.0))then
            vn0=(p(86)+dv0)/(p(86)-dv0)
            vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*p(27)*p(27))+sqrt
     +((vn0+1.0)*(vn0+1.0)+4.0*p(87)*p(87)))
            vl0=0.5*(vnl0*(p(86)-dv0)-p(86)-dv0)
            xvar1=(1.0-vl0/p(25))
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            qlo0=p(25)*(1.0-xvar3)/(1.0-p(26))
            vn=(2.0*Vbep+p(86)+dv0)/(p(86)-dv0)
            vn_Vbep=2.0/(p(86)-dv0)
            vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*p(27)*p(27))+sqrt((vn
     ++1.0)*(vn+1.0)+4.0*p(87)*p(87)))
            vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(p(87)*p(87)))+sqrt
     +(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(27))))-2.0*vn*((vn+1.0)/sqrt(((v
     +n+1.0)*(vn+1.0))+4.0*(p(87)*p(87)))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.
     +0))+4.0*(p(27)*p(27))))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(p(87)*p(87
     +)))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(27))))*(sqrt(((vn+1.0)*(
     +vn+1.0))+4.0*(p(87)*p(87)))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(p(27)*p(
     +27)))))
            vnl_Vbep=vnl_vn*vn_Vbep
            vl=0.5*(vnl*(p(86)-dv0)-p(86)-dv0)
            vl_vnl=0.5*(p(86)-dv0)
            vl_Vbep=vl_vnl*vnl_Vbep
            xvar1=(1.0-vl/p(25))
            xvar1_vl=-1.0/p(25)
            xvar1_Vbep=xvar1_vl*vl_Vbep
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
            qlo=p(25)*(1.0-xvar3)/(1.0-p(26))
            qlo_xvar3=-p(25)/(1.0-p(26))
            qlo_Vbep=qlo_xvar3*xvar3_Vbep
            sel=0.5*(vnl+1.0)
            sel_vnl=0.5
            sel_Vbep=sel_vnl*vnl_Vbep
            xvar1=(1.0+p(86)/p(25))
            xvar2=(-p(26))
            crt=xvar1**xvar2
            xvar1=(1.0+dv0/p(25))
            xvar2=(-p(26))
            cmx=xvar1**xvar2
            cl=(1.0-sel)*crt+sel*cmx
            cl_sel=cmx-crt
            cl_Vbep=cl_sel*sel_Vbep
            ql=(Vbep-vl+vl0)*cl
            ql_Vbep=cl
            ql_vl=-cl
            ql_cl=vl0-vl+Vbep
            ql_Vbep=ql_Vbep+ql_vl*vl_Vbep
            ql_Vbep=ql_Vbep+ql_cl*cl_Vbep
            qdbep=ql+qlo-qlo0
            qdbep_ql=1.0
            qdbep_qlo=1.0
            qdbep_Vbep=qdbep_ql*ql_Vbep
            qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep
         else
            mv0=sqrt(dv0*dv0+4.0*p(27)*p(27))
            vl0=-0.5*(dv0+mv0)
            xvar1=(1.0-vl0/p(25))
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            q0=-p(25)*xvar3/(1.0-p(26))
            dv=Vbep+dv0
            dv_Vbep=1.0
            mv=sqrt(dv*dv+4.0*p(27)*p(27))
            mv_dv=dv/sqrt((dv*dv)+4.0*(p(27)*p(27)))
            mv_Vbep=mv_dv*dv_Vbep
            vl=0.5*(dv-mv)-dv0
            vl_dv=0.5
            vl_mv=-0.5
            vl_Vbep=vl_dv*dv_Vbep
            vl_Vbep=vl_Vbep+vl_mv*mv_Vbep
            xvar1=(1.0-vl/p(25))
            xvar1_vl=-1.0/p(25)
            xvar1_Vbep=xvar1_vl*vl_Vbep
            xvar2=(1.0-p(26))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
            qlo=-p(25)*xvar3/(1.0-p(26))
            qlo_xvar3=-p(25)/(1.0-p(26))
            qlo_Vbep=qlo_xvar3*xvar3_Vbep
            xvar1=(1.0-p(15))
            xvar2=(-p(26))
            xvar3=xvar1**xvar2
            qdbep=qlo+xvar3*(Vbep-vl+vl0)-q0
            qdbep_qlo=1.0
            qdbep_Vbep=xvar3
            qdbep_vl=-xvar3
            qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep
            qdbep_Vbep=qdbep_Vbep+qdbep_vl*vl_Vbep
         endif
      endif
      if(p(28).GT.0.0)then
         dv0=-p(29)*p(15)
         if(p(31).LE.0.0)then
            dvh=Vbcp+dv0
            dvh_Vbcp=1.0
            if(dvh.GT.0.0)then
               xvar1=(1.0-p(15))
               xvar2=(-1.0-p(30))
               pwq=xvar1**xvar2
               qlo=p(29)*(1.0-pwq*(1.0-p(15))*(1.0-p(15)))/(1.0-p(30))
               qlo_Vbep=0.0
               qlo_Vbcp=0.0
               qhi=dvh*(1.0-p(15)+0.5*p(30)*dvh/p(29))*pwq
               qhi_dvh=(0.5*dvh*p(30)/p(29)-p(15)+1.0)*pwq+0.5*dvh*p(30)
     +*pwq/p(29)
               qhi_Vbep=0.0
               qhi_Vbcp=qhi_dvh*dvh_Vbcp
            else
               xvar1=(1.0-Vbcp/p(29))
               xvar1_Vbcp=-1.0/p(29)
               xvar2=(1.0-p(30))
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vbcp=xvar3_xvar1*xvar1_Vbcp
               qlo=p(29)*(1.0-xvar3)/(1.0-p(30))
               qlo_xvar3=-p(29)/(1.0-p(30))
               qlo_Vbep=0.0
               qlo_Vbcp=qlo_xvar3*xvar3_Vbcp
               qhi=0.0
               qhi_Vbep=0.0
               qhi_Vbcp=0.0
            endif
            qdbcp=qlo+qhi
            qdbcp_qlo=1.0
            qdbcp_qhi=1.0
            qdbcp_Vbcp=qdbcp_qlo*qlo_Vbcp
            qdbcp_Vbep=qdbcp_qlo*qlo_Vbep
            qdbcp_Vbep=qdbcp_Vbep+qdbcp_qhi*qhi_Vbep
            qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_qhi*qhi_Vbcp
         else
            mv0=sqrt(dv0*dv0+4.0*p(31)*p(31))
            vl0=-0.5*(dv0+mv0)
            xvar1=(1.0-vl0/p(29))
            xvar2=(1.0-p(30))
            xvar3=xvar1**xvar2
            q0=-p(29)*xvar3/(1.0-p(30))
            dv=Vbcp+dv0
            dv_Vbcp=1.0
            mv=sqrt(dv*dv+4.0*p(31)*p(31))
            mv_dv=dv/sqrt((dv*dv)+4.0*(p(31)*p(31)))
            mv_Vbcp=mv_dv*dv_Vbcp
            vl=0.5*(dv-mv)-dv0
            vl_dv=0.5
            vl_mv=-0.5
            vl_Vbcp=vl_dv*dv_Vbcp
            vl_Vbcp=vl_Vbcp+vl_mv*mv_Vbcp
            xvar1=(1.0-vl/p(29))
            xvar1_vl=-1.0/p(29)
            xvar1_Vbcp=xvar1_vl*vl_Vbcp
            xvar2=(1.0-p(30))
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbcp=xvar3_xvar1*xvar1_Vbcp
            qlo=-p(29)*xvar3/(1.0-p(30))
            qlo_xvar3=-p(29)/(1.0-p(30))
            qlo_Vbep=0.0
            qlo_Vbcp=qlo_xvar3*xvar3_Vbcp
            xvar1=(1.0-p(15))
            xvar2=(-p(30))
            xvar3=xvar1**xvar2
            qdbcp=qlo+xvar3*(Vbcp-vl+vl0)-q0
            qdbcp_qlo=1.0
            qdbcp_Vbcp=xvar3
            qdbcp_vl=-xvar3
            qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_qlo*qlo_Vbcp
            qdbcp_Vbep=qdbcp_qlo*qlo_Vbep
            qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_vl*vl_Vbcp
         endif
      else
         qdbcp=0.0
         qdbcp_Vbcp=0.0
      endif
      argi=Vbei/(p(13)*Vtv)
      argi_Vbei=1.0/(p(13)*Vtv)
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbei=expi_argi*argi_Vbei
      Ifi=p(12)*(expi-1.0)
      Ifi_expi=p(12)
      Ifi_Vbei=Ifi_expi*expi_Vbei
      argi=Vbci/(p(14)*Vtv)
      argi_Vbci=1.0/(p(14)*Vtv)
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      Iri=p(12)*p(95)*(expi-1.0)
      Iri_expi=p(12)*p(95)
      Iri_Vbci=Iri_expi*expi_Vbci
      q1z=1.0+qdbe*IVER+qdbc*IVEF
      q1z_qdbe=IVER
      q1z_qdbc=IVEF
      q1z_Vbei=q1z_qdbe*qdbe_Vbei
      q1z_Vbci=q1z_qdbc*qdbc_Vbci
      q1=0.5*(sqrt((q1z-1.0e-4)*(q1z-1.0e-4)+1.0e-8)+q1z-1.0e-4)+1.0e-4
      q1_q1z=0.5*((q1z-1.0e-4)/sqrt(((q1z-1.0e-4)*(q1z-1.0e-4))+1.0e-8)+
     +1.0)
      q1_Vbei=q1_q1z*q1z_Vbei
      q1_Vbci=q1_q1z*q1z_Vbci
      q2=Ifi*IIKF+Iri*IIKR
      q2_Ifi=IIKF
      q2_Iri=IIKR
      q2_Vbei=q2_Ifi*Ifi_Vbei
      q2_Vbci=q2_Iri*Iri_Vbci
      if(p(89).LT.0.5)then
         xvar2=1.0/p(90)
         xvar3=q1**xvar2
         xvar3_q1=xvar3*xvar2/q1
         xvar3_Vbei=xvar3_q1*q1_Vbei
         xvar3_Vbci=xvar3_q1*q1_Vbci
         xvar1=(xvar3+4.0*q2)
         xvar1_xvar3=1.0
         xvar1_q2=4.0
         xvar1_Vbei=xvar1_xvar3*xvar3_Vbei
         xvar1_Vbci=xvar1_xvar3*xvar3_Vbci
         xvar1_Vbei=xvar1_Vbei+xvar1_q2*q2_Vbei
         xvar1_Vbci=xvar1_Vbci+xvar1_q2*q2_Vbci
         xvar4=xvar1**p(90)
         xvar4_xvar1=xvar4*p(90)/xvar1
         xvar4_Vbei=xvar4_xvar1*xvar1_Vbei
         xvar4_Vbci=xvar4_xvar1*xvar1_Vbci
         qb=0.5*(q1+xvar4)
         qb_q1=0.5
         qb_xvar4=0.5
         qb_Vbei=qb_q1*q1_Vbei
         qb_Vbci=qb_q1*q1_Vbci
         qb_Vbei=qb_Vbei+qb_xvar4*xvar4_Vbei
         qb_Vbci=qb_Vbci+qb_xvar4*xvar4_Vbci
      else
         xvar1=(1.0+4.0*q2)
         xvar1_q2=4.0
         xvar1_Vbei=xvar1_q2*q2_Vbei
         xvar1_Vbci=xvar1_q2*q2_Vbci
         xvar2=xvar1**p(90)
         xvar2_xvar1=xvar2*p(90)/xvar1
         xvar2_Vbei=xvar2_xvar1*xvar1_Vbei
         xvar2_Vbci=xvar2_xvar1*xvar1_Vbci
         qb=0.5*q1*(1.0+xvar2)
         qb_q1=0.5*(xvar2+1.0)
         qb_xvar2=0.5*q1
         qb_Vbei=qb_q1*q1_Vbei
         qb_Vbci=qb_q1*q1_Vbci
         qb_Vbei=qb_Vbei+qb_xvar2*xvar2_Vbei
         qb_Vbci=qb_Vbci+qb_xvar2*xvar2_Vbci
      endif
      Itzr=Iri/qb
      Itzr_Iri=1.0/qb
      Itzr_qb=-Iri/(qb*qb)
      Itzr_Vbci=Itzr_Iri*Iri_Vbci
      Itzr_Vbei=Itzr_qb*qb_Vbei
      Itzr_Vbci=Itzr_Vbci+Itzr_qb*qb_Vbci
      Itzf=Ifi/qb
      Itzf_Ifi=1.0/qb
      Itzf_qb=-Ifi/(qb*qb)
      Itzf_Vbei=Itzf_Ifi*Ifi_Vbei
      Itzf_Vbei=Itzf_Vbei+Itzf_qb*qb_Vbei
      Itzf_Vbci=Itzf_qb*qb_Vbci
      if(p(43).GT.0.0)then
         argi=Vbep/(p(45)*Vtv)
         argi_Vbep=1.0/(p(45)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbep=expi_argi*argi_Vbep
         argx=Vbci/(p(45)*Vtv)
         argx_Vbci=1.0/(p(45)*Vtv)
         if(argx.GT.100.0)then
            expx_argx=exp(100.0)
            expx=expx_argx*(1.0+(argx-100.0))
         elseif(argx.LT.-100.0)then
            expx_argx=exp(-100.0)
            expx=expx_argx*(1.0+(argx+100.0))
         else
            expx=exp(argx)
            expx_argx=expx
         endif
         expx_Vbci=expx_argx*argx_Vbci
         Ifp=p(43)*(p(44)*expi+(1.0-p(44))*expx-1.0)
         Ifp_expi=p(43)*p(44)
         Ifp_expx=p(43)*(1.0-p(44))
         Ifp_Vbep=Ifp_expi*expi_Vbep
         Ifp_Vbci=Ifp_expx*expx_Vbci
         q2p=Ifp*IIKP
         q2p_Ifp=IIKP
         q2p_Vbep=q2p_Ifp*Ifp_Vbep
         q2p_Vbci=q2p_Ifp*Ifp_Vbci
         qbp=0.5*(1.0+sqrt(1.0+4.0*q2p))
         qbp_q2p=1.0/sqrt(4.0*q2p+1.0)
         qbp_Vbep=qbp_q2p*q2p_Vbep
         qbp_Vbci=qbp_q2p*q2p_Vbci
         argi=Vbcp/(p(45)*Vtv)
         argi_Vbcp=1.0/(p(45)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbcp=expi_argi*argi_Vbcp
         Irp=p(43)*(expi-1.0)
         Irp_expi=p(43)
         Irp_Vbcp=Irp_expi*expi_Vbcp
         Iccp=(Ifp-Irp)/qbp
         Iccp_Ifp=1.0/qbp
         Iccp_Irp=-1.0/qbp
         Iccp_qbp=-(Ifp-Irp)/(qbp*qbp)
         Iccp_Vbep=Iccp_Ifp*Ifp_Vbep
         Iccp_Vbci=Iccp_Ifp*Ifp_Vbci
         Iccp_Vbcp=Iccp_Irp*Irp_Vbcp
         Iccp_Vbep=Iccp_Vbep+Iccp_qbp*qbp_Vbep
         Iccp_Vbci=Iccp_Vbci+Iccp_qbp*qbp_Vbci
      else
         Ifp=0.0
         Ifp_Vbep=0.0
         Ifp_Vbci=0.0
         qbp=1.0
         qbp_Vbep=0.0
         qbp_Vbci=0.0
         Iccp=0.0
         Iccp_Vbep=0.0
         Iccp_Vbci=0.0
         Iccp_Vbcp=0.0
      endif
      if(p(33).EQ.1.0)then
         argi=Vbei/(p(34)*Vtv)
         argi_Vbei=1.0/(p(34)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbei=expi_argi*argi_Vbei
         argn=Vbei/(p(36)*Vtv)
         argn_Vbei=1.0/(p(36)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbei=expn_argn*argn_Vbei
         if(p(99).GT.0.0)then
            argx=(-p(99)-Vbei)/(p(100)*Vtv)
            argx_Vbei=-1.0/(p(100)*Vtv)
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vbei=expx_argx*argx_Vbei
            Ibe=p(32)*(expi-1.0)+p(35)*(expn-1.0)-p(101)*(expx-p(105))
            Ibe_expi=p(32)
            Ibe_expn=p(35)
            Ibe_expx=-p(101)
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expx*expx_Vbei
         else
            Ibe=p(32)*(expi-1.0)+p(35)*(expn-1.0)
            Ibe_expi=p(32)
            Ibe_expn=p(35)
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
         endif
         Ibex=0.0
         Ibex_Vbex=0.0
      elseif(p(33).EQ.0.0)then
         Ibe=0.0
         Ibe_Vbei=0.0
         argi=Vbex/(p(34)*Vtv)
         argi_Vbex=1.0/(p(34)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbex=expi_argi*argi_Vbex
         argn=Vbex/(p(36)*Vtv)
         argn_Vbex=1.0/(p(36)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbex=expn_argn*argn_Vbex
         if(p(99).GT.0.0)then
            argx=(-p(99)-Vbex)/(p(100)*Vtv)
            argx_Vbex=-1.0/(p(100)*Vtv)
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vbex=expx_argx*argx_Vbex
            Ibex=p(32)*(expi-1.0)+p(35)*(expn-1.0)-p(101)*(expx-p(105))
            Ibex_expi=p(32)
            Ibex_expn=p(35)
            Ibex_expx=-p(101)
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expx*expx_Vbex
         else
            Ibex=p(32)*(expi-1.0)+p(35)*(expn-1.0)
            Ibex_expi=p(32)
            Ibex_expn=p(35)
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
         endif
      else
         argi=Vbei/(p(34)*Vtv)
         argi_Vbei=1.0/(p(34)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbei=expi_argi*argi_Vbei
         argn=Vbei/(p(36)*Vtv)
         argn_Vbei=1.0/(p(36)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbei=expn_argn*argn_Vbei
         if(p(99).GT.0.0)then
            argx=(-p(99)-Vbei)/(p(100)*Vtv)
            argx_Vbei=-1.0/(p(100)*Vtv)
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vbei=expx_argx*argx_Vbei
            Ibe=p(33)*(p(32)*(expi-1.0)+p(35)*(expn-1.0)-p(101)*(expx-p(
     +105)))
            Ibe_expi=p(32)*p(33)
            Ibe_expn=p(35)*p(33)
            Ibe_expx=-p(101)*p(33)
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expx*expx_Vbei
         else
            Ibe=p(33)*(p(32)*(expi-1.0)+p(35)*(expn-1.0))
            Ibe_expi=p(32)*p(33)
            Ibe_expn=p(35)*p(33)
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
         endif
         argi=Vbex/(p(34)*Vtv)
         argi_Vbex=1.0/(p(34)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbex=expi_argi*argi_Vbex
         argn=Vbex/(p(36)*Vtv)
         argn_Vbex=1.0/(p(36)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbex=expn_argn*argn_Vbex
         if(p(99).GT.0.0)then
            argx=(-p(99)-Vbex)/(p(100)*Vtv)
            argx_Vbex=-1.0/(p(100)*Vtv)
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vbex=expx_argx*argx_Vbex
            Ibex=(1.0-p(33))*(p(32)*(expi-1.0)+p(35)*(expn-1.0)-p(101)*(
     +expx-p(105)))
            Ibex_expi=p(32)*(1.0-p(33))
            Ibex_expn=p(35)*(1.0-p(33))
            Ibex_expx=-p(101)*(1.0-p(33))
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expx*expx_Vbex
         else
            Ibex=(1.0-p(33))*(p(32)*(expi-1.0)+p(35)*(expn-1.0))
            Ibex_expi=p(32)*(1.0-p(33))
            Ibex_expn=p(35)*(1.0-p(33))
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
         endif
      endif
      argi=Vbci/(p(38)*Vtv)
      argi_Vbci=1.0/(p(38)*Vtv)
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      argn=Vbci/(p(40)*Vtv)
      argn_Vbci=1.0/(p(40)*Vtv)
      if(argn.GT.100.0)then
         expn_argn=exp(100.0)
         expn=expn_argn*(1.0+(argn-100.0))
      elseif(argn.LT.-100.0)then
         expn_argn=exp(-100.0)
         expn=expn_argn*(1.0+(argn+100.0))
      else
         expn=exp(argn)
         expn_argn=expn
      endif
      expn_Vbci=expn_argn*argn_Vbci
      Ibcj=p(37)*(expi-1.0)+p(39)*(expn-1.0)
      Ibcj_expi=p(37)
      Ibcj_expn=p(39)
      Ibcj_Vbci=Ibcj_expi*expi_Vbci
      Ibcj_Vbci=Ibcj_Vbci+Ibcj_expn*expn_Vbci
      if((p(46).GT.0.0).OR.(p(47).GT.0.0))then
         argi=Vbep/(p(38)*Vtv)
         argi_Vbep=1.0/(p(38)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbep=expi_argi*argi_Vbep
         argn=Vbep/(p(40)*Vtv)
         argn_Vbep=1.0/(p(40)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbep=expn_argn*argn_Vbep
         Ibep=p(46)*(expi-1.0)+p(47)*(expn-1.0)
         Ibep_expi=p(46)
         Ibep_expn=p(47)
         Ibep_Vbep=Ibep_expi*expi_Vbep
         Ibep_Vbep=Ibep_Vbep+Ibep_expn*expn_Vbep
      else
         Ibep=0.0
         Ibep_Vbep=0.0
      endif
      if(p(41).GT.0.0)then
         vl=0.5*(sqrt((p(25)-Vbci)*(p(25)-Vbci)+0.01)+(p(25)-Vbci))
         vl_Vbci=0.5*(-(p(25)-Vbci)/sqrt(((p(25)-Vbci)*(p(25)-Vbci))+0.0
     +1)-1.0)
         xvar2=(p(26)-1.0)
         xvar3=vl**xvar2
         xvar3_vl=xvar3*xvar2/vl
         xvar3_Vbci=xvar3_vl*vl_Vbci
         xvar1=-p(42)*xvar3
         xvar1_xvar3=-p(42)
         xvar1_Vbci=xvar1_xvar3*xvar3_Vbci
         if(xvar1.GT.100.0)then
            xvar4_xvar1=exp(100.0)
            xvar4=xvar4_xvar1*(1.0+(xvar1-100.0))
         elseif(xvar1.LT.-100.0)then
            xvar4_xvar1=exp(-100.0)
            xvar4=xvar4_xvar1*(1.0+(xvar1+100.0))
         else
            xvar4=exp(xvar1)
            xvar4_xvar1=xvar4
         endif
         xvar4_Vbci=xvar4_xvar1*xvar1_Vbci
         avalf=p(41)*vl*xvar4
         avalf_vl=p(41)*xvar4
         avalf_xvar4=p(41)*vl
         avalf_Vbci=avalf_vl*vl_Vbci
         avalf_Vbci=avalf_Vbci+avalf_xvar4*xvar4_Vbci
         Igc=(Itzf-Itzr-Ibcj)*avalf
         Igc_Itzf=avalf
         Igc_Itzr=-avalf
         Igc_Ibcj=-avalf
         Igc_avalf=-Itzr+Itzf-Ibcj
         Igc_Vbei=Igc_Itzf*Itzf_Vbei
         Igc_Vbci=Igc_Itzf*Itzf_Vbci
         Igc_Vbci=Igc_Vbci+Igc_Itzr*Itzr_Vbci
         Igc_Vbei=Igc_Vbei+Igc_Itzr*Itzr_Vbei
         Igc_Vbci=Igc_Vbci+Igc_Ibcj*Ibcj_Vbci
         Igc_Vbci=Igc_Vbci+Igc_avalf*avalf_Vbci
      else
         Igc=0.0
         Igc_Vbei=0.0
         Igc_Vbci=0.0
      endif
      Ibc=Ibcj-Igc
      Ibc_Ibcj=1.0
      Ibc_Igc=-1.0
      Ibc_Vbci=Ibc_Ibcj*Ibcj_Vbci
      Ibc_Vbei=Ibc_Igc*Igc_Vbei
      Ibc_Vbci=Ibc_Vbci+Ibc_Igc*Igc_Vbci
      if(p(2).GT.0.0)then
         Ircx=Vrcx/p(2)
         Ircx_Vrcx=1.0/p(2)
      else
         Ircx=0.0
         Ircx_Vrcx=0.0
      endif
      argi=Vbci/Vtv
      argi_Vbci=1.0/Vtv
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      argx=Vbcx/Vtv
      argx_Vbcx=1.0/Vtv
      if(argx.GT.100.0)then
         expx_argx=exp(100.0)
         expx=expx_argx*(1.0+(argx-100.0))
      elseif(argx.LT.-100.0)then
         expx_argx=exp(-100.0)
         expx=expx_argx*(1.0+(argx+100.0))
      else
         expx=exp(argx)
         expx_argx=expx
      endif
      expx_Vbcx=expx_argx*argx_Vbcx
      Kbci=sqrt(1.0+p(5)*expi)
      Kbci_expi=p(5)/(2.0*sqrt(expi*p(5)+1.0))
      Kbci_Vbci=Kbci_expi*expi_Vbci
      Kbcx=sqrt(1.0+p(5)*expx)
      Kbcx_expx=p(5)/(2.0*sqrt(expx*p(5)+1.0))
      Kbcx_Vbcx=Kbcx_expx*expx_Vbcx
      if(p(3).GT.0.0)then
         rKp1=(Kbci+1.0)/(Kbcx+1.0)
         rKp1_Kbci=1.0/(Kbcx+1.0)
         rKp1_Kbcx=-(Kbci+1.0)/((Kbcx+1.0)*(Kbcx+1.0))
         rKp1_Vbci=rKp1_Kbci*Kbci_Vbci
         rKp1_Vbcx=rKp1_Kbcx*Kbcx_Vbcx
         xvar1=log(rKp1)
         xvar1_rKp1=1.0/rKp1
         xvar1_Vbci=xvar1_rKp1*rKp1_Vbci
         xvar1_Vbcx=xvar1_rKp1*rKp1_Vbcx
         Iohm=(Vrci+Vtv*(Kbci-Kbcx-xvar1))/p(3)
         Iohm_Vrci=1.0/p(3)
         Iohm_Kbci=Vtv/p(3)
         Iohm_Kbcx=-Vtv/p(3)
         Iohm_xvar1=-Vtv/p(3)
         Iohm_Vbci=Iohm_Kbci*Kbci_Vbci
         Iohm_Vbcx=Iohm_Kbcx*Kbcx_Vbcx
         Iohm_Vbci=Iohm_Vbci+Iohm_xvar1*xvar1_Vbci
         Iohm_Vbcx=Iohm_Vbcx+Iohm_xvar1*xvar1_Vbcx
         derf=IVO*p(3)*Iohm/(1.0+0.5*IVO*IHRCF*sqrt(Vrci*Vrci+0.01))
         derf_Iohm=IVO*p(3)/(0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)
         derf_Vrci=-0.5*IHRCF*Iohm*(IVO*IVO)*p(3)*Vrci/(sqrt((Vrci*Vrci)
     ++0.01)*((0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)*(0.5*IHRCF*IVO*
     +sqrt((Vrci*Vrci)+0.01)+1.0)))
         derf_Vrci=derf_Vrci+derf_Iohm*Iohm_Vrci
         derf_Vbci=derf_Iohm*Iohm_Vbci
         derf_Vbcx=derf_Iohm*Iohm_Vbcx
         Irci=Iohm/sqrt(1.0+derf*derf)
         Irci_Iohm=1.0/sqrt((derf*derf)+1.0)
         Irci_derf=-derf*Iohm/(((derf*derf)+1.0)**(3.0/2.0))
         Irci_Vrci=Irci_Iohm*Iohm_Vrci
         Irci_Vbci=Irci_Iohm*Iohm_Vbci
         Irci_Vbcx=Irci_Iohm*Iohm_Vbcx
         Irci_Vrci=Irci_Vrci+Irci_derf*derf_Vrci
         Irci_Vbci=Irci_Vbci+Irci_derf*derf_Vbci
         Irci_Vbcx=Irci_Vbcx+Irci_derf*derf_Vbcx
      else
         Irci=0.0
         Irci_Vrci=0.0
         Irci_Vbci=0.0
         Irci_Vbcx=0.0
      endif
      if(p(7).GT.0.0)then
         Irbx=Vrbx/p(7)
         Irbx_Vrbx=1.0/p(7)
      else
         Irbx=0.0
         Irbx_Vrbx=0.0
      endif
      if(p(8).GT.0.0)then
         Irbi=Vrbi*qb/p(8)
         Irbi_Vrbi=qb/p(8)
         Irbi_qb=Vrbi/p(8)
         Irbi_Vbei=Irbi_qb*qb_Vbei
         Irbi_Vbci=Irbi_qb*qb_Vbci
      else
         Irbi=0.0
         Irbi_Vrbi=0.0
         Irbi_Vbei=0.0
         Irbi_Vbci=0.0
      endif
      if(p(9).GT.0.0)then
         Ire=Vre/p(9)
         Ire_Vre=1.0/p(9)
      else
         Ire=0.0
         Ire_Vre=0.0
      endif
      if(p(11).GT.0.0)then
         Irbp=Vrbp*qbp/p(11)
         Irbp_Vrbp=qbp/p(11)
         Irbp_qbp=Vrbp/p(11)
         Irbp_Vbep=Irbp_qbp*qbp_Vbep
         Irbp_Vbci=Irbp_qbp*qbp_Vbci
      else
         Irbp=0.0
         Irbp_Vrbp=0.0
         Irbp_Vbep=0.0
         Irbp_Vbci=0.0
      endif
      if((p(48).GT.0.0).OR.(p(50).GT.0.0))then
         argi=Vbcp/(p(49)*Vtv)
         argi_Vbcp=1.0/(p(49)*Vtv)
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbcp=expi_argi*argi_Vbcp
         argn=Vbcp/(p(51)*Vtv)
         argn_Vbcp=1.0/(p(51)*Vtv)
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbcp=expn_argn*argn_Vbcp
         Ibcp=p(48)*(expi-1.0)+p(50)*(expn-1.0)
         Ibcp_expi=p(48)
         Ibcp_expn=p(50)
         Ibcp_Vbcp=Ibcp_expi*expi_Vbcp
         Ibcp_Vbcp=Ibcp_Vbcp+Ibcp_expn*expn_Vbcp
      else
         Ibcp=0.0
         Ibcp_Vbcp=0.0
      endif
      if(p(10).GT.0.0)then
         Irs=Vrs/p(10)
         Irs_Vrs=1.0/p(10)
      else
         Irs=0.0
         Irs_Vrs=0.0
      endif
      if(Ifi.GT.0.0)then
         sgIf=1.0
      else
         sgIf=0.0
      endif
      rIf=Ifi*sgIf*IITF
      rIf_Ifi=IITF*sgIf
      rIf_Vbei=rIf_Ifi*Ifi_Vbei
      mIf=rIf/(rIf+1.0)
      mIf_rIf=1.0/(rIf+1.0)-rIf/((rIf+1.0)*(rIf+1.0))
      mIf_Vbei=mIf_rIf*rIf_Vbei
      xvar1=Vbci*IVTF/1.44
      xvar1_Vbci=0.6944444*IVTF
      if(xvar1.GT.100.0)then
         xvar2_xvar1=exp(100.0)
         xvar2=xvar2_xvar1*(1.0+(xvar1-100.0))
      elseif(xvar1.LT.-100.0)then
         xvar2_xvar1=exp(-100.0)
         xvar2=xvar2_xvar1*(1.0+(xvar1+100.0))
      else
         xvar2=exp(xvar1)
         xvar2_xvar1=xvar2
      endif
      xvar2_Vbci=xvar2_xvar1*xvar1_Vbci
      tff=p(57)*(1.0+p(58)*q1)*(1.0+p(59)*xvar2*(slTF+mIf*mIf)*sgIf)
      tff_q1=p(58)*p(57)*(sgIf*(slTF+(mIf*mIf))*p(59)*xvar2+1.0)
      tff_xvar2=(q1*p(58)+1.0)*sgIf*(slTF+(mIf*mIf))*p(57)*p(59)
      tff_mIf=2.0*mIf*(q1*p(58)+1.0)*sgIf*p(57)*p(59)*xvar2
      tff_Vbei=tff_q1*q1_Vbei
      tff_Vbci=tff_q1*q1_Vbci
      tff_Vbci=tff_Vbci+tff_xvar2*xvar2_Vbci
      tff_Vbei=tff_Vbei+tff_mIf*mIf_Vbei
      Qbe=p(17)*qdbe*p(33)+tff*Ifi/qb
      Qbe_qdbe=p(17)*p(33)
      Qbe_tff=Ifi/qb
      Qbe_Ifi=tff/qb
      Qbe_qb=-Ifi*tff/(qb*qb)
      Qbe_Vbei=Qbe_qdbe*qdbe_Vbei
      Qbe_Vbei=Qbe_Vbei+Qbe_tff*tff_Vbei
      Qbe_Vbci=Qbe_tff*tff_Vbci
      Qbe_Vbei=Qbe_Vbei+Qbe_Ifi*Ifi_Vbei
      Qbe_Vbei=Qbe_Vbei+Qbe_qb*qb_Vbei
      Qbe_Vbci=Qbe_Vbci+Qbe_qb*qb_Vbci
      Qbex=p(17)*qdbex*(1.0-p(33))
      Qbex_qdbex=p(17)*(1.0-p(33))
      Qbex_Vbex=Qbex_qdbex*qdbex_Vbex
      Qbc=p(22)*qdbc+p(62)*Iri+p(23)*Kbci
      Qbc_qdbc=p(22)
      Qbc_Iri=p(62)
      Qbc_Kbci=p(23)
      Qbc_Vbci=Qbc_qdbc*qdbc_Vbci
      Qbc_Vbci=Qbc_Vbci+Qbc_Iri*Iri_Vbci
      Qbc_Vbci=Qbc_Vbci+Qbc_Kbci*Kbci_Vbci
      Qbcx=p(23)*Kbcx
      Qbcx_Kbcx=p(23)
      Qbcx_Vbcx=Qbcx_Kbcx*Kbcx_Vbcx
      Qbep=p(24)*qdbep+p(62)*Ifp
      Qbep_qdbep=p(24)
      Qbep_Ifp=p(62)
      Qbep_Vbep=Qbep_qdbep*qdbep_Vbep
      Qbep_Vbep=Qbep_Vbep+Qbep_Ifp*Ifp_Vbep
      Qbep_Vbci=Qbep_Ifp*Ifp_Vbci
      Qbcp=p(28)*qdbcp+p(88)*Vbcp
      Qbcp_qdbcp=p(28)
      Qbcp_Vbcp=p(88)
      Qbcp_Vbcp=Qbcp_Vbcp+Qbcp_qdbcp*qdbcp_Vbcp
      Qbeo=Vbe*p(16)
      Qbeo_Vbe=p(16)
      Qbco=Vbc*p(21)
      Qbco_Vbc=p(21)
c
c     Scale outputs
c
      if(SCALE.NE.1.0)then
         Ibe=SCALE*Ibe
         Ibe_Vbei=SCALE*Ibe_Vbei
         Ibex=SCALE*Ibex
         Ibex_Vbex=SCALE*Ibex_Vbex
         Itzf=SCALE*Itzf
         Itzf_Vbei=SCALE*Itzf_Vbei
         Itzf_Vbci=SCALE*Itzf_Vbci
         Itzr=SCALE*Itzr
         Itzr_Vbci=SCALE*Itzr_Vbci
         Itzr_Vbei=SCALE*Itzr_Vbei
         Ibc=SCALE*Ibc
         Ibc_Vbci=SCALE*Ibc_Vbci
         Ibc_Vbei=SCALE*Ibc_Vbei
         Ibep=SCALE*Ibep
         Ibep_Vbep=SCALE*Ibep_Vbep
         Ircx=SCALE*Ircx
         Ircx_Vrcx=SCALE*Ircx_Vrcx
         Irci=SCALE*Irci
         Irci_Vrci=SCALE*Irci_Vrci
         Irci_Vbci=SCALE*Irci_Vbci
         Irci_Vbcx=SCALE*Irci_Vbcx
         Irbx=SCALE*Irbx
         Irbx_Vrbx=SCALE*Irbx_Vrbx
         Irbi=SCALE*Irbi
         Irbi_Vrbi=SCALE*Irbi_Vrbi
         Irbi_Vbei=SCALE*Irbi_Vbei
         Irbi_Vbci=SCALE*Irbi_Vbci
         Ire=SCALE*Ire
         Ire_Vre=SCALE*Ire_Vre
         Irbp=SCALE*Irbp
         Irbp_Vrbp=SCALE*Irbp_Vrbp
         Irbp_Vbep=SCALE*Irbp_Vbep
         Irbp_Vbci=SCALE*Irbp_Vbci
         Qbe=SCALE*Qbe
         Qbe_Vbei=SCALE*Qbe_Vbei
         Qbe_Vbci=SCALE*Qbe_Vbci
         Qbex=SCALE*Qbex
         Qbex_Vbex=SCALE*Qbex_Vbex
         Qbc=SCALE*Qbc
         Qbc_Vbci=SCALE*Qbc_Vbci
         Qbcx=SCALE*Qbcx
         Qbcx_Vbcx=SCALE*Qbcx_Vbcx
         Qbep=SCALE*Qbep
         Qbep_Vbep=SCALE*Qbep_Vbep
         Qbep_Vbci=SCALE*Qbep_Vbci
         Qbeo=SCALE*Qbeo
         Qbeo_Vbe=SCALE*Qbeo_Vbe
         Qbco=SCALE*Qbco
         Qbco_Vbc=SCALE*Qbco_Vbc
         Ibcp=SCALE*Ibcp
         Ibcp_Vbcp=SCALE*Ibcp_Vbcp
         Iccp=SCALE*Iccp
         Iccp_Vbep=SCALE*Iccp_Vbep
         Iccp_Vbci=SCALE*Iccp_Vbci
         Iccp_Vbcp=SCALE*Iccp_Vbcp
         Irs=SCALE*Irs
         Irs_Vrs=SCALE*Irs_Vrs
         Qbcp=SCALE*Qbcp
         Qbcp_Vbcp=SCALE*Qbcp_Vbcp
      endif
      return
      end
