
#include <stdio.h>
#include <math.h>

int vbic_4T_it_cf_fj(p
	,Vbei,Vbex,Vbci,Vbep,Vbcp,Vrcx
	,Vbcx,Vrci,Vrbx,Vrbi,Vre,Vrbp,Vrs
	,Vbe,Vbc,Ibe,Ibe_Vbei,Ibex,Ibex_Vbex,Itzf
	,Itzf_Vbei,Itzf_Vbci,Itzr,Itzr_Vbci,Itzr_Vbei,Ibc,Ibc_Vbci
	,Ibc_Vbei,Ibep,Ibep_Vbep,Ircx,Ircx_Vrcx,Irci,Irci_Vrci
	,Irci_Vbci,Irci_Vbcx,Irbx,Irbx_Vrbx,Irbi,Irbi_Vrbi,Irbi_Vbei
	,Irbi_Vbci,Ire,Ire_Vre,Irbp,Irbp_Vrbp,Irbp_Vbep,Irbp_Vbci
	,Qbe,Qbe_Vbei,Qbe_Vbci,Qbex,Qbex_Vbex,Qbc,Qbc_Vbci
	,Qbcx,Qbcx_Vbcx,Qbep,Qbep_Vbep,Qbep_Vbci,Qbeo,Qbeo_Vbe
	,Qbco,Qbco_Vbc,Ibcp,Ibcp_Vbcp,Iccp,Iccp_Vbep,Iccp_Vbci
	,Iccp_Vbcp,Irs,Irs_Vrs,Qbcp,Qbcp_Vbcp,SCALE)
double *p
	,*Vbei,*Vbex,*Vbci,*Vbep,*Vbcp,*Vrcx
	,*Vbcx,*Vrci,*Vrbx,*Vrbi,*Vre,*Vrbp,*Vrs
	,*Vbe,*Vbc,*Ibe,*Ibe_Vbei,*Ibex,*Ibex_Vbex,*Itzf
	,*Itzf_Vbei,*Itzf_Vbci,*Itzr,*Itzr_Vbci,*Itzr_Vbei,*Ibc,*Ibc_Vbci
	,*Ibc_Vbei,*Ibep,*Ibep_Vbep,*Ircx,*Ircx_Vrcx,*Irci,*Irci_Vrci
	,*Irci_Vbci,*Irci_Vbcx,*Irbx,*Irbx_Vrbx,*Irbi,*Irbi_Vrbi,*Irbi_Vbei
	,*Irbi_Vbci,*Ire,*Ire_Vre,*Irbp,*Irbp_Vrbp,*Irbp_Vbep,*Irbp_Vbci
	,*Qbe,*Qbe_Vbei,*Qbe_Vbci,*Qbex,*Qbex_Vbex,*Qbc,*Qbc_Vbci
	,*Qbcx,*Qbcx_Vbcx,*Qbep,*Qbep_Vbep,*Qbep_Vbci,*Qbeo,*Qbeo_Vbe
	,*Qbco,*Qbco_Vbc,*Ibcp,*Ibcp_Vbcp,*Iccp,*Iccp_Vbep,*Iccp_Vbci
	,*Iccp_Vbcp,*Irs,*Irs_Vrs,*Qbcp,*Qbcp_Vbcp,*SCALE;
{
double	Vtv,IVEF,IVER,IIKF,IIKR,IIKP,IVO;
double	IHRCF,IVTF,IITF,slTF,dv0,dvh,dvh_Vbei;
double	xvar1,xvar2,pwq,qlo,qlo_Vbei,qhi,qhi_dvh;
double	qhi_Vbei,xvar1_Vbei,xvar3,xvar3_xvar1,xvar3_Vbei,qlo_xvar3,qdbe;
double	qdbe_qlo,qdbe_Vbei,qdbe_qhi,mv0,vl0,q0,dv;
double	dv_Vbei,mv,mv_dv,mv_Vbei,vl,vl_dv,vl_Vbei;
double	vl_mv,xvar1_vl,qdbe_vl,dvh_Vbex,qlo_Vbex,qhi_Vbex,xvar1_Vbex;
double	xvar3_Vbex,qdbex,qdbex_qlo,qdbex_Vbex,qdbex_qhi,dv_Vbex,mv_Vbex;
double	vl_Vbex,qdbex_vl,dvh_Vbci,qlo_Vbci,qhi_Vbci,xvar1_Vbci,xvar3_Vbci;
double	qdbc,qdbc_qlo,qdbc_Vbci,qdbc_qhi,vn0,vnl0,qlo0;
double	vn,vn_Vbci,vnl,vnl_vn,vnl_Vbci,vl_vnl,vl_Vbci;
double	sel,sel_vnl,sel_Vbci,crt,cmx,cl,cl_sel;
double	cl_Vbci,ql,ql_Vbci,ql_vl,ql_cl,qdbc_ql,dv_Vbci;
double	mv_Vbci,qdbc_vl,dvh_Vbep,qlo_Vbep,qhi_Vbep,xvar1_Vbep,xvar3_Vbep;
double	qdbep,qdbep_qlo,qdbep_Vbep,qdbep_qhi,vn_Vbep,vnl_Vbep,vl_Vbep;
double	sel_Vbep,cl_Vbep,ql_Vbep,qdbep_ql,dv_Vbep,mv_Vbep,qdbep_vl;
double	dvh_Vbcp,qlo_Vbcp,qhi_Vbcp,xvar1_Vbcp,xvar3_Vbcp,qdbcp,qdbcp_qlo;
double	qdbcp_Vbcp,qdbcp_Vbep,qdbcp_qhi,dv_Vbcp,mv_Vbcp,vl_Vbcp,qdbcp_vl;
double	argi,argi_Vbei,expi,expi_argi,expi_Vbei,Ifi,Ifi_expi;
double	Ifi_Vbei,argi_Vbci,expi_Vbci,Iri,Iri_expi,Iri_Vbci,q1z;
double	q1z_qdbe,q1z_Vbei,q1z_qdbc,q1z_Vbci,q1,q1_q1z,q1_Vbei;
double	q1_Vbci,q2,q2_Ifi,q2_Vbei,q2_Iri,q2_Vbci,xvar3_q1;
double	xvar1_xvar3,xvar1_q2,xvar4,xvar4_xvar1,xvar4_Vbei,xvar4_Vbci,qb;
double	qb_q1,qb_Vbei,qb_Vbci,qb_xvar4,xvar2_xvar1,xvar2_Vbei,xvar2_Vbci;
double	qb_xvar2,Itzr_Iri,Itzr_qb,Itzf_Ifi,Itzf_qb,argi_Vbep,expi_Vbep;
double	argx,argx_Vbci,expx,expx_argx,expx_Vbci,Ifp,Ifp_expi;
double	Ifp_Vbep,Ifp_expx,Ifp_Vbci,q2p,q2p_Ifp,q2p_Vbep,q2p_Vbci;
double	qbp,qbp_q2p,qbp_Vbep,qbp_Vbci,argi_Vbcp,expi_Vbcp,Irp;
double	Irp_expi,Irp_Vbcp,Iccp_Ifp,Iccp_Irp,Iccp_qbp,argn,argn_Vbei;
double	expn,expn_argn,expn_Vbei,argx_Vbei,expx_Vbei,Ibe_expi,Ibe_expn;
double	Ibe_expx,argi_Vbex,expi_Vbex,argn_Vbex,expn_Vbex,argx_Vbex,expx_Vbex;
double	Ibex_expi,Ibex_expn,Ibex_expx,argn_Vbci,expn_Vbci,Ibcj,Ibcj_expi;
double	Ibcj_Vbci,Ibcj_expn,argn_Vbep,expn_Vbep,Ibep_expi,Ibep_expn,xvar3_vl;
double	avalf,avalf_vl,avalf_Vbci,avalf_xvar4,Igc,Igc_Itzf,Igc_Vbei;
double	Igc_Vbci,Igc_Itzr,Igc_Ibcj,Igc_avalf,Ibc_Ibcj,Ibc_Igc,argx_Vbcx;
double	expx_Vbcx,Kbci,Kbci_expi,Kbci_Vbci,Kbcx,Kbcx_expx,Kbcx_Vbcx;
double	rKp1,rKp1_Kbci,rKp1_Vbci,rKp1_Kbcx,rKp1_Vbcx,xvar1_rKp1,xvar1_Vbcx;
double	Iohm,Iohm_Vrci,Iohm_Kbci,Iohm_Vbci,Iohm_Kbcx,Iohm_Vbcx,Iohm_xvar1;
double	derf,derf_Iohm,derf_Vrci,derf_Vbci,derf_Vbcx,Irci_Iohm,Irci_derf;
double	Irbi_qb,Irbp_qbp,argn_Vbcp,expn_Vbcp,Ibcp_expi,Ibcp_expn,sgIf;
double	rIf,rIf_Ifi,rIf_Vbei,mIf,mIf_rIf,mIf_Vbei,tff;
double	tff_q1,tff_Vbei,tff_Vbci,tff_xvar2,tff_mIf,Qbe_qdbe,Qbe_tff;
double	Qbe_Ifi,Qbe_qb,Qbex_qdbex,Qbc_qdbc,Qbc_Iri,Qbc_Kbci,Qbcx_Kbcx;
double	Qbep_qdbep,Qbep_Ifp,Qbcp_qdbcp;
double	TNOM,RCX,RCI,VO,GAMM,HRCF,RBX;
double	RBI,RE,RS,RBP,IS,NF,NR;
double	FC,CBEO,CJE,PE,ME,AJE,CBCO;
double	CJC,QCO,CJEP,PC,MC,AJC,CJCP;
double	PS,MS,AJS,IBEI,WBE,NEI,IBEN;
double	NEN,IBCI,NCI,IBCN,NCN,AVC1,AVC2;
double	ISP,WSP,NFP,IBEIP,IBENP,IBCIP,NCIP;
double	IBCNP,NCNP,VEF,VER,IKF,IKR,IKP;
double	TF,QTF,XTF,VTF,ITF,TR,VRT;
double	ART,CCSO,QBM,NKF,ISRR,VBBE,NBBE;
double	IBBE,EBBE;

/*	Map parameter array into symbolic names */

	TNOM=p[0];
	RCX=p[1];
	RCI=p[2];
	VO=p[3];
	GAMM=p[4];
	HRCF=p[5];
	RBX=p[6];
	RBI=p[7];
	RE=p[8];
	RS=p[9];
	RBP=p[10];
	IS=p[11];
	NF=p[12];
	NR=p[13];
	FC=p[14];
	CBEO=p[15];
	CJE=p[16];
	PE=p[17];
	ME=p[18];
	AJE=p[19];
	CBCO=p[20];
	CJC=p[21];
	QCO=p[22];
	CJEP=p[23];
	PC=p[24];
	MC=p[25];
	AJC=p[26];
	CJCP=p[27];
	PS=p[28];
	MS=p[29];
	AJS=p[30];
	IBEI=p[31];
	WBE=p[32];
	NEI=p[33];
	IBEN=p[34];
	NEN=p[35];
	IBCI=p[36];
	NCI=p[37];
	IBCN=p[38];
	NCN=p[39];
	AVC1=p[40];
	AVC2=p[41];
	ISP=p[42];
	WSP=p[43];
	NFP=p[44];
	IBEIP=p[45];
	IBENP=p[46];
	IBCIP=p[47];
	NCIP=p[48];
	IBCNP=p[49];
	NCNP=p[50];
	VEF=p[51];
	VER=p[52];
	IKF=p[53];
	IKR=p[54];
	IKP=p[55];
	TF=p[56];
	QTF=p[57];
	XTF=p[58];
	VTF=p[59];
	ITF=p[60];
	TR=p[61];
	VRT=p[85];
	ART=p[86];
	CCSO=p[87];
	QBM=p[88];
	NKF=p[89];
	ISRR=p[94];
	VBBE=p[98];
	NBBE=p[99];
	IBBE=p[100];
	EBBE=p[104];

/*	Function and derivative code */

	Vtv=1.380662e-23*(2.731500e+02+TNOM)/1.602189e-19;
	if(VEF>0.0){
		IVEF=1.0/VEF;
	}else{
		IVEF=0.0;
	}
	if(VER>0.0){
		IVER=1.0/VER;
	}else{
		IVER=0.0;
	}
	if(IKF>0.0){
		IIKF=1.0/IKF;
	}else{
		IIKF=0.0;
	}
	if(IKR>0.0){
		IIKR=1.0/IKR;
	}else{
		IIKR=0.0;
	}
	if(IKP>0.0){
		IIKP=1.0/IKP;
	}else{
		IIKP=0.0;
	}
	if(VO>0.0){
		IVO=1.0/VO;
	}else{
		IVO=0.0;
	}
	if(HRCF>0.0){
		IHRCF=1.0/HRCF;
	}else{
		IHRCF=0.0;
	}
	if(VTF>0.0){
		IVTF=1.0/VTF;
	}else{
		IVTF=0.0;
	}
	if(ITF>0.0){
		IITF=1.0/ITF;
	}else{
		IITF=0.0;
	}
	if(ITF>0.0){
		slTF=0.0;
	}else{
		slTF=1.0;
	}
	dv0=-PE*FC;
	if(AJE<=0.0){
		dvh=(*Vbei)+dv0;
		dvh_Vbei=1.0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-ME);
			pwq=pow(xvar1,xvar2);
			qlo=PE*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME);
			qlo_Vbei=0.0;
			qhi=dvh*(1.0-FC+0.5*ME*dvh/PE)*pwq;
			qhi_dvh=(0.5*dvh*ME/PE-FC+1.0)*pwq+0.5*dvh*ME*pwq/PE;
			qhi_Vbei=qhi_dvh*dvh_Vbei;
		}else{
			xvar1=(1.0-(*Vbei)/PE);
			xvar1_Vbei=-1.0/PE;
			xvar2=(1.0-ME);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbei=xvar3_xvar1*xvar1_Vbei;
			qlo=PE*(1.0-xvar3)/(1.0-ME);
			qlo_xvar3=-PE/(1.0-ME);
			qlo_Vbei=qlo_xvar3*xvar3_Vbei;
			qhi=0.0;
			qhi_Vbei=0.0;
		}
		qdbe=qlo+qhi;
		qdbe_qlo=1.0;
		qdbe_qhi=1.0;
		qdbe_Vbei=qdbe_qlo*qlo_Vbei;
		qdbe_Vbei=qdbe_Vbei+qdbe_qhi*qhi_Vbei;
	}else{
		mv0=sqrt(dv0*dv0+4.0*AJE*AJE);
		vl0=-0.5*(dv0+mv0);
		xvar1=(1.0-vl0/PE);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		q0=-PE*xvar3/(1.0-ME);
		dv=(*Vbei)+dv0;
		dv_Vbei=1.0;
		mv=sqrt(dv*dv+4.0*AJE*AJE);
		mv_dv=dv/sqrt((dv*dv)+4.0*(AJE*AJE));
		mv_Vbei=mv_dv*dv_Vbei;
		vl=0.5*(dv-mv)-dv0;
		vl_dv=0.5;
		vl_mv=-0.5;
		vl_Vbei=vl_dv*dv_Vbei;
		vl_Vbei=vl_Vbei+vl_mv*mv_Vbei;
		xvar1=(1.0-vl/PE);
		xvar1_vl=-1.0/PE;
		xvar1_Vbei=xvar1_vl*vl_Vbei;
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		xvar3_xvar1=xvar3*xvar2/xvar1;
		xvar3_Vbei=xvar3_xvar1*xvar1_Vbei;
		qlo=-PE*xvar3/(1.0-ME);
		qlo_xvar3=-PE/(1.0-ME);
		qlo_Vbei=qlo_xvar3*xvar3_Vbei;
		xvar1=(1.0-FC);
		xvar2=(-ME);
		xvar3=pow(xvar1,xvar2);
		qdbe=qlo+xvar3*((*Vbei)-vl+vl0)-q0;
		qdbe_qlo=1.0;
		qdbe_Vbei=xvar3;
		qdbe_vl=-xvar3;
		qdbe_Vbei=qdbe_Vbei+qdbe_qlo*qlo_Vbei;
		qdbe_Vbei=qdbe_Vbei+qdbe_vl*vl_Vbei;
	}
	dv0=-PE*FC;
	if(AJE<=0.0){
		dvh=(*Vbex)+dv0;
		dvh_Vbex=1.0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-ME);
			pwq=pow(xvar1,xvar2);
			qlo=PE*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME);
			qlo_Vbex=0.0;
			qhi=dvh*(1.0-FC+0.5*ME*dvh/PE)*pwq;
			qhi_dvh=(0.5*dvh*ME/PE-FC+1.0)*pwq+0.5*dvh*ME*pwq/PE;
			qhi_Vbex=qhi_dvh*dvh_Vbex;
		}else{
			xvar1=(1.0-(*Vbex)/PE);
			xvar1_Vbex=-1.0/PE;
			xvar2=(1.0-ME);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbex=xvar3_xvar1*xvar1_Vbex;
			qlo=PE*(1.0-xvar3)/(1.0-ME);
			qlo_xvar3=-PE/(1.0-ME);
			qlo_Vbex=qlo_xvar3*xvar3_Vbex;
			qhi=0.0;
			qhi_Vbex=0.0;
		}
		qdbex=qlo+qhi;
		qdbex_qlo=1.0;
		qdbex_qhi=1.0;
		qdbex_Vbex=qdbex_qlo*qlo_Vbex;
		qdbex_Vbex=qdbex_Vbex+qdbex_qhi*qhi_Vbex;
	}else{
		mv0=sqrt(dv0*dv0+4.0*AJE*AJE);
		vl0=-0.5*(dv0+mv0);
		xvar1=(1.0-vl0/PE);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		q0=-PE*xvar3/(1.0-ME);
		dv=(*Vbex)+dv0;
		dv_Vbex=1.0;
		mv=sqrt(dv*dv+4.0*AJE*AJE);
		mv_dv=dv/sqrt((dv*dv)+4.0*(AJE*AJE));
		mv_Vbex=mv_dv*dv_Vbex;
		vl=0.5*(dv-mv)-dv0;
		vl_dv=0.5;
		vl_mv=-0.5;
		vl_Vbex=vl_dv*dv_Vbex;
		vl_Vbex=vl_Vbex+vl_mv*mv_Vbex;
		xvar1=(1.0-vl/PE);
		xvar1_vl=-1.0/PE;
		xvar1_Vbex=xvar1_vl*vl_Vbex;
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		xvar3_xvar1=xvar3*xvar2/xvar1;
		xvar3_Vbex=xvar3_xvar1*xvar1_Vbex;
		qlo=-PE*xvar3/(1.0-ME);
		qlo_xvar3=-PE/(1.0-ME);
		qlo_Vbex=qlo_xvar3*xvar3_Vbex;
		xvar1=(1.0-FC);
		xvar2=(-ME);
		xvar3=pow(xvar1,xvar2);
		qdbex=qlo+xvar3*((*Vbex)-vl+vl0)-q0;
		qdbex_qlo=1.0;
		qdbex_Vbex=xvar3;
		qdbex_vl=-xvar3;
		qdbex_Vbex=qdbex_Vbex+qdbex_qlo*qlo_Vbex;
		qdbex_Vbex=qdbex_Vbex+qdbex_vl*vl_Vbex;
	}
	dv0=-PC*FC;
	if(AJC<=0.0){
		dvh=(*Vbci)+dv0;
		dvh_Vbci=1.0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-MC);
			pwq=pow(xvar1,xvar2);
			qlo=PC*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC);
			qlo_Vbci=0.0;
			qhi=dvh*(1.0-FC+0.5*MC*dvh/PC)*pwq;
			qhi_dvh=(0.5*dvh*MC/PC-FC+1.0)*pwq+0.5*dvh*MC*pwq/PC;
			qhi_Vbci=qhi_dvh*dvh_Vbci;
		}else{
			if((VRT>0.0)&&((*Vbci)<-VRT)){
				xvar1=(1.0+VRT/PC);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PC*(1.0-xvar3*(1.0-((1.0-MC)*((*Vbci)+VRT))/(PC+VRT)))/(1.0-MC);
				qlo_Vbci=PC*xvar3/(VRT+PC);
			}else{
				xvar1=(1.0-(*Vbci)/PC);
				xvar1_Vbci=-1.0/PC;
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				xvar3_xvar1=xvar3*xvar2/xvar1;
				xvar3_Vbci=xvar3_xvar1*xvar1_Vbci;
				qlo=PC*(1.0-xvar3)/(1.0-MC);
				qlo_xvar3=-PC/(1.0-MC);
				qlo_Vbci=qlo_xvar3*xvar3_Vbci;
			}
			qhi=0.0;
			qhi_Vbci=0.0;
		}
		qdbc=qlo+qhi;
		qdbc_qlo=1.0;
		qdbc_qhi=1.0;
		qdbc_Vbci=qdbc_qlo*qlo_Vbci;
		qdbc_Vbci=qdbc_Vbci+qdbc_qhi*qhi_Vbci;
	}else{
		if((VRT>0.0)&&(ART>0.0)){
			vn0=(VRT+dv0)/(VRT-dv0);
			vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn0+1.0)*(vn0+1.0)+4.0*ART*ART));
			vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl0/PC);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo0=PC*(1.0-xvar3)/(1.0-MC);
			vn=(2.0*(*Vbci)+VRT+dv0)/(VRT-dv0);
			vn_Vbci=2.0/(VRT-dv0);
			vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0)*(vn+1.0)+4.0*ART*ART));
			vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))-2.0*vn*((vn+1.0)/sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC))));
			vnl_Vbci=vnl_vn*vn_Vbci;
			vl=0.5*(vnl*(VRT-dv0)-VRT-dv0);
			vl_vnl=0.5*(VRT-dv0);
			vl_Vbci=vl_vnl*vnl_Vbci;
			xvar1=(1.0-vl/PC);
			xvar1_vl=-1.0/PC;
			xvar1_Vbci=xvar1_vl*vl_Vbci;
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbci=xvar3_xvar1*xvar1_Vbci;
			qlo=PC*(1.0-xvar3)/(1.0-MC);
			qlo_xvar3=-PC/(1.0-MC);
			qlo_Vbci=qlo_xvar3*xvar3_Vbci;
			sel=0.5*(vnl+1.0);
			sel_vnl=0.5;
			sel_Vbci=sel_vnl*vnl_Vbci;
			xvar1=(1.0+VRT/PC);
			xvar2=(-MC);
			crt=pow(xvar1,xvar2);
			xvar1=(1.0+dv0/PC);
			xvar2=(-MC);
			cmx=pow(xvar1,xvar2);
			cl=(1.0-sel)*crt+sel*cmx;
			cl_sel=cmx-crt;
			cl_Vbci=cl_sel*sel_Vbci;
			ql=((*Vbci)-vl+vl0)*cl;
			ql_Vbci=cl;
			ql_vl=-cl;
			ql_cl=vl0-vl+(*Vbci);
			ql_Vbci=ql_Vbci+ql_vl*vl_Vbci;
			ql_Vbci=ql_Vbci+ql_cl*cl_Vbci;
			qdbc=ql+qlo-qlo0;
			qdbc_ql=1.0;
			qdbc_qlo=1.0;
			qdbc_Vbci=qdbc_ql*ql_Vbci;
			qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci;
		}else{
			mv0=sqrt(dv0*dv0+4.0*AJC*AJC);
			vl0=-0.5*(dv0+mv0);
			xvar1=(1.0-vl0/PC);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			q0=-PC*xvar3/(1.0-MC);
			dv=(*Vbci)+dv0;
			dv_Vbci=1.0;
			mv=sqrt(dv*dv+4.0*AJC*AJC);
			mv_dv=dv/sqrt((dv*dv)+4.0*(AJC*AJC));
			mv_Vbci=mv_dv*dv_Vbci;
			vl=0.5*(dv-mv)-dv0;
			vl_dv=0.5;
			vl_mv=-0.5;
			vl_Vbci=vl_dv*dv_Vbci;
			vl_Vbci=vl_Vbci+vl_mv*mv_Vbci;
			xvar1=(1.0-vl/PC);
			xvar1_vl=-1.0/PC;
			xvar1_Vbci=xvar1_vl*vl_Vbci;
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbci=xvar3_xvar1*xvar1_Vbci;
			qlo=-PC*xvar3/(1.0-MC);
			qlo_xvar3=-PC/(1.0-MC);
			qlo_Vbci=qlo_xvar3*xvar3_Vbci;
			xvar1=(1.0-FC);
			xvar2=(-MC);
			xvar3=pow(xvar1,xvar2);
			qdbc=qlo+xvar3*((*Vbci)-vl+vl0)-q0;
			qdbc_qlo=1.0;
			qdbc_Vbci=xvar3;
			qdbc_vl=-xvar3;
			qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci;
			qdbc_Vbci=qdbc_Vbci+qdbc_vl*vl_Vbci;
		}
	}
	dv0=-PC*FC;
	if(AJC<=0.0){
		dvh=(*Vbep)+dv0;
		dvh_Vbep=1.0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-MC);
			pwq=pow(xvar1,xvar2);
			qlo=PC*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC);
			qlo_Vbep=0.0;
			qhi=dvh*(1.0-FC+0.5*MC*dvh/PC)*pwq;
			qhi_dvh=(0.5*dvh*MC/PC-FC+1.0)*pwq+0.5*dvh*MC*pwq/PC;
			qhi_Vbep=qhi_dvh*dvh_Vbep;
		}else{
			if((VRT>0.0)&&((*Vbep)<-VRT)){
				xvar1=(1.0+VRT/PC);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PC*(1.0-xvar3*(1.0-((1.0-MC)*((*Vbep)+VRT))/(PC+VRT)))/(1.0-MC);
				qlo_Vbep=PC*xvar3/(VRT+PC);
			}else{
				xvar1=(1.0-(*Vbep)/PC);
				xvar1_Vbep=-1.0/PC;
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				xvar3_xvar1=xvar3*xvar2/xvar1;
				xvar3_Vbep=xvar3_xvar1*xvar1_Vbep;
				qlo=PC*(1.0-xvar3)/(1.0-MC);
				qlo_xvar3=-PC/(1.0-MC);
				qlo_Vbep=qlo_xvar3*xvar3_Vbep;
			}
			qhi=0.0;
			qhi_Vbep=0.0;
		}
		qdbep=qlo+qhi;
		qdbep_qlo=1.0;
		qdbep_qhi=1.0;
		qdbep_Vbep=qdbep_qlo*qlo_Vbep;
		qdbep_Vbep=qdbep_Vbep+qdbep_qhi*qhi_Vbep;
	}else{
		if((VRT>0.0)&&(ART>0.0)){
			vn0=(VRT+dv0)/(VRT-dv0);
			vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn0+1.0)*(vn0+1.0)+4.0*ART*ART));
			vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl0/PC);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo0=PC*(1.0-xvar3)/(1.0-MC);
			vn=(2.0*(*Vbep)+VRT+dv0)/(VRT-dv0);
			vn_Vbep=2.0/(VRT-dv0);
			vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0)*(vn+1.0)+4.0*ART*ART));
			vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))-2.0*vn*((vn+1.0)/sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC))));
			vnl_Vbep=vnl_vn*vn_Vbep;
			vl=0.5*(vnl*(VRT-dv0)-VRT-dv0);
			vl_vnl=0.5*(VRT-dv0);
			vl_Vbep=vl_vnl*vnl_Vbep;
			xvar1=(1.0-vl/PC);
			xvar1_vl=-1.0/PC;
			xvar1_Vbep=xvar1_vl*vl_Vbep;
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbep=xvar3_xvar1*xvar1_Vbep;
			qlo=PC*(1.0-xvar3)/(1.0-MC);
			qlo_xvar3=-PC/(1.0-MC);
			qlo_Vbep=qlo_xvar3*xvar3_Vbep;
			sel=0.5*(vnl+1.0);
			sel_vnl=0.5;
			sel_Vbep=sel_vnl*vnl_Vbep;
			xvar1=(1.0+VRT/PC);
			xvar2=(-MC);
			crt=pow(xvar1,xvar2);
			xvar1=(1.0+dv0/PC);
			xvar2=(-MC);
			cmx=pow(xvar1,xvar2);
			cl=(1.0-sel)*crt+sel*cmx;
			cl_sel=cmx-crt;
			cl_Vbep=cl_sel*sel_Vbep;
			ql=((*Vbep)-vl+vl0)*cl;
			ql_Vbep=cl;
			ql_vl=-cl;
			ql_cl=vl0-vl+(*Vbep);
			ql_Vbep=ql_Vbep+ql_vl*vl_Vbep;
			ql_Vbep=ql_Vbep+ql_cl*cl_Vbep;
			qdbep=ql+qlo-qlo0;
			qdbep_ql=1.0;
			qdbep_qlo=1.0;
			qdbep_Vbep=qdbep_ql*ql_Vbep;
			qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep;
		}else{
			mv0=sqrt(dv0*dv0+4.0*AJC*AJC);
			vl0=-0.5*(dv0+mv0);
			xvar1=(1.0-vl0/PC);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			q0=-PC*xvar3/(1.0-MC);
			dv=(*Vbep)+dv0;
			dv_Vbep=1.0;
			mv=sqrt(dv*dv+4.0*AJC*AJC);
			mv_dv=dv/sqrt((dv*dv)+4.0*(AJC*AJC));
			mv_Vbep=mv_dv*dv_Vbep;
			vl=0.5*(dv-mv)-dv0;
			vl_dv=0.5;
			vl_mv=-0.5;
			vl_Vbep=vl_dv*dv_Vbep;
			vl_Vbep=vl_Vbep+vl_mv*mv_Vbep;
			xvar1=(1.0-vl/PC);
			xvar1_vl=-1.0/PC;
			xvar1_Vbep=xvar1_vl*vl_Vbep;
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbep=xvar3_xvar1*xvar1_Vbep;
			qlo=-PC*xvar3/(1.0-MC);
			qlo_xvar3=-PC/(1.0-MC);
			qlo_Vbep=qlo_xvar3*xvar3_Vbep;
			xvar1=(1.0-FC);
			xvar2=(-MC);
			xvar3=pow(xvar1,xvar2);
			qdbep=qlo+xvar3*((*Vbep)-vl+vl0)-q0;
			qdbep_qlo=1.0;
			qdbep_Vbep=xvar3;
			qdbep_vl=-xvar3;
			qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep;
			qdbep_Vbep=qdbep_Vbep+qdbep_vl*vl_Vbep;
		}
	}
	if(CJCP>0.0){
		dv0=-PS*FC;
		if(AJS<=0.0){
			dvh=(*Vbcp)+dv0;
			dvh_Vbcp=1.0;
			if(dvh>0.0){
				xvar1=(1.0-FC);
				xvar2=(-1.0-MS);
				pwq=pow(xvar1,xvar2);
				qlo=PS*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MS);
				qlo_Vbep=0.0;
				qlo_Vbcp=0.0;
				qhi=dvh*(1.0-FC+0.5*MS*dvh/PS)*pwq;
				qhi_dvh=(0.5*dvh*MS/PS-FC+1.0)*pwq+0.5*dvh*MS*pwq/PS;
				qhi_Vbep=0.0;
				qhi_Vbcp=qhi_dvh*dvh_Vbcp;
			}else{
				xvar1=(1.0-(*Vbcp)/PS);
				xvar1_Vbcp=-1.0/PS;
				xvar2=(1.0-MS);
				xvar3=pow(xvar1,xvar2);
				xvar3_xvar1=xvar3*xvar2/xvar1;
				xvar3_Vbcp=xvar3_xvar1*xvar1_Vbcp;
				qlo=PS*(1.0-xvar3)/(1.0-MS);
				qlo_xvar3=-PS/(1.0-MS);
				qlo_Vbep=0.0;
				qlo_Vbcp=qlo_xvar3*xvar3_Vbcp;
				qhi=0.0;
				qhi_Vbep=0.0;
				qhi_Vbcp=0.0;
			}
			qdbcp=qlo+qhi;
			qdbcp_qlo=1.0;
			qdbcp_qhi=1.0;
			qdbcp_Vbcp=qdbcp_qlo*qlo_Vbcp;
			qdbcp_Vbep=qdbcp_qlo*qlo_Vbep;
			qdbcp_Vbep=qdbcp_Vbep+qdbcp_qhi*qhi_Vbep;
			qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_qhi*qhi_Vbcp;
		}else{
			mv0=sqrt(dv0*dv0+4.0*AJS*AJS);
			vl0=-0.5*(dv0+mv0);
			xvar1=(1.0-vl0/PS);
			xvar2=(1.0-MS);
			xvar3=pow(xvar1,xvar2);
			q0=-PS*xvar3/(1.0-MS);
			dv=(*Vbcp)+dv0;
			dv_Vbcp=1.0;
			mv=sqrt(dv*dv+4.0*AJS*AJS);
			mv_dv=dv/sqrt((dv*dv)+4.0*(AJS*AJS));
			mv_Vbcp=mv_dv*dv_Vbcp;
			vl=0.5*(dv-mv)-dv0;
			vl_dv=0.5;
			vl_mv=-0.5;
			vl_Vbcp=vl_dv*dv_Vbcp;
			vl_Vbcp=vl_Vbcp+vl_mv*mv_Vbcp;
			xvar1=(1.0-vl/PS);
			xvar1_vl=-1.0/PS;
			xvar1_Vbcp=xvar1_vl*vl_Vbcp;
			xvar2=(1.0-MS);
			xvar3=pow(xvar1,xvar2);
			xvar3_xvar1=xvar3*xvar2/xvar1;
			xvar3_Vbcp=xvar3_xvar1*xvar1_Vbcp;
			qlo=-PS*xvar3/(1.0-MS);
			qlo_xvar3=-PS/(1.0-MS);
			qlo_Vbep=0.0;
			qlo_Vbcp=qlo_xvar3*xvar3_Vbcp;
			xvar1=(1.0-FC);
			xvar2=(-MS);
			xvar3=pow(xvar1,xvar2);
			qdbcp=qlo+xvar3*((*Vbcp)-vl+vl0)-q0;
			qdbcp_qlo=1.0;
			qdbcp_Vbcp=xvar3;
			qdbcp_vl=-xvar3;
			qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_qlo*qlo_Vbcp;
			qdbcp_Vbep=qdbcp_qlo*qlo_Vbep;
			qdbcp_Vbcp=qdbcp_Vbcp+qdbcp_vl*vl_Vbcp;
		}
	}else{
		qdbcp=0.0;
		qdbcp_Vbcp=0.0;
	}
	argi=(*Vbei)/(NF*Vtv);
	argi_Vbei=1.0/(NF*Vtv);
	expi=exp(argi);
	expi_argi=expi;
	expi_Vbei=expi_argi*argi_Vbei;
	Ifi=IS*(expi-1.0);
	Ifi_expi=IS;
	Ifi_Vbei=Ifi_expi*expi_Vbei;
	argi=(*Vbci)/(NR*Vtv);
	argi_Vbci=1.0/(NR*Vtv);
	expi=exp(argi);
	expi_argi=expi;
	expi_Vbci=expi_argi*argi_Vbci;
	Iri=IS*ISRR*(expi-1.0);
	Iri_expi=IS*ISRR;
	Iri_Vbci=Iri_expi*expi_Vbci;
	q1z=1.0+qdbe*IVER+qdbc*IVEF;
	q1z_qdbe=IVER;
	q1z_qdbc=IVEF;
	q1z_Vbei=q1z_qdbe*qdbe_Vbei;
	q1z_Vbci=q1z_qdbc*qdbc_Vbci;
	q1=0.5*(sqrt((q1z-1.0e-4)*(q1z-1.0e-4)+1.0e-8)+q1z-1.0e-4)+1.0e-4;
	q1_q1z=0.5*((q1z-1.0e-4)/sqrt(((q1z-1.0e-4)*(q1z-1.0e-4))+1.0e-8)+1.0);
	q1_Vbei=q1_q1z*q1z_Vbei;
	q1_Vbci=q1_q1z*q1z_Vbci;
	q2=Ifi*IIKF+Iri*IIKR;
	q2_Ifi=IIKF;
	q2_Iri=IIKR;
	q2_Vbei=q2_Ifi*Ifi_Vbei;
	q2_Vbci=q2_Iri*Iri_Vbci;
	if(QBM<0.5){
		xvar2=1.0/NKF;
		xvar3=pow(q1,xvar2);
		xvar3_q1=xvar3*xvar2/q1;
		xvar3_Vbei=xvar3_q1*q1_Vbei;
		xvar3_Vbci=xvar3_q1*q1_Vbci;
		xvar1=(xvar3+4.0*q2);
		xvar1_xvar3=1.0;
		xvar1_q2=4.0;
		xvar1_Vbei=xvar1_xvar3*xvar3_Vbei;
		xvar1_Vbci=xvar1_xvar3*xvar3_Vbci;
		xvar1_Vbei=xvar1_Vbei+xvar1_q2*q2_Vbei;
		xvar1_Vbci=xvar1_Vbci+xvar1_q2*q2_Vbci;
		xvar4=pow(xvar1,NKF);
		xvar4_xvar1=xvar4*NKF/xvar1;
		xvar4_Vbei=xvar4_xvar1*xvar1_Vbei;
		xvar4_Vbci=xvar4_xvar1*xvar1_Vbci;
		qb=0.5*(q1+xvar4);
		qb_q1=0.5;
		qb_xvar4=0.5;
		qb_Vbei=qb_q1*q1_Vbei;
		qb_Vbci=qb_q1*q1_Vbci;
		qb_Vbei=qb_Vbei+qb_xvar4*xvar4_Vbei;
		qb_Vbci=qb_Vbci+qb_xvar4*xvar4_Vbci;
	}else{
		xvar1=(1.0+4.0*q2);
		xvar1_q2=4.0;
		xvar1_Vbei=xvar1_q2*q2_Vbei;
		xvar1_Vbci=xvar1_q2*q2_Vbci;
		xvar2=pow(xvar1,NKF);
		xvar2_xvar1=xvar2*NKF/xvar1;
		xvar2_Vbei=xvar2_xvar1*xvar1_Vbei;
		xvar2_Vbci=xvar2_xvar1*xvar1_Vbci;
		qb=0.5*q1*(1.0+xvar2);
		qb_q1=0.5*(xvar2+1.0);
		qb_xvar2=0.5*q1;
		qb_Vbei=qb_q1*q1_Vbei;
		qb_Vbci=qb_q1*q1_Vbci;
		qb_Vbei=qb_Vbei+qb_xvar2*xvar2_Vbei;
		qb_Vbci=qb_Vbci+qb_xvar2*xvar2_Vbci;
	}
	(*Itzr)=Iri/qb;
	Itzr_Iri=1.0/qb;
	Itzr_qb=-Iri/(qb*qb);
	*Itzr_Vbci=Itzr_Iri*Iri_Vbci;
	*Itzr_Vbei=Itzr_qb*qb_Vbei;
	*Itzr_Vbci=(*Itzr_Vbci)+Itzr_qb*qb_Vbci;
	(*Itzf)=Ifi/qb;
	Itzf_Ifi=1.0/qb;
	Itzf_qb=-Ifi/(qb*qb);
	*Itzf_Vbei=Itzf_Ifi*Ifi_Vbei;
	*Itzf_Vbei=(*Itzf_Vbei)+Itzf_qb*qb_Vbei;
	*Itzf_Vbci=Itzf_qb*qb_Vbci;
	if(ISP>0.0){
		argi=(*Vbep)/(NFP*Vtv);
		argi_Vbep=1.0/(NFP*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbep=expi_argi*argi_Vbep;
		argx=(*Vbci)/(NFP*Vtv);
		argx_Vbci=1.0/(NFP*Vtv);
		expx=exp(argx);
		expx_argx=expx;
		expx_Vbci=expx_argx*argx_Vbci;
		Ifp=ISP*(WSP*expi+(1.0-WSP)*expx-1.0);
		Ifp_expi=ISP*WSP;
		Ifp_expx=ISP*(1.0-WSP);
		Ifp_Vbep=Ifp_expi*expi_Vbep;
		Ifp_Vbci=Ifp_expx*expx_Vbci;
		q2p=Ifp*IIKP;
		q2p_Ifp=IIKP;
		q2p_Vbep=q2p_Ifp*Ifp_Vbep;
		q2p_Vbci=q2p_Ifp*Ifp_Vbci;
		qbp=0.5*(1.0+sqrt(1.0+4.0*q2p));
		qbp_q2p=1.0/sqrt(4.0*q2p+1.0);
		qbp_Vbep=qbp_q2p*q2p_Vbep;
		qbp_Vbci=qbp_q2p*q2p_Vbci;
		argi=(*Vbcp)/(NFP*Vtv);
		argi_Vbcp=1.0/(NFP*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbcp=expi_argi*argi_Vbcp;
		Irp=ISP*(expi-1.0);
		Irp_expi=ISP;
		Irp_Vbcp=Irp_expi*expi_Vbcp;
		(*Iccp)=(Ifp-Irp)/qbp;
		Iccp_Ifp=1.0/qbp;
		Iccp_Irp=-1.0/qbp;
		Iccp_qbp=-(Ifp-Irp)/(qbp*qbp);
		*Iccp_Vbep=Iccp_Ifp*Ifp_Vbep;
		*Iccp_Vbci=Iccp_Ifp*Ifp_Vbci;
		*Iccp_Vbcp=Iccp_Irp*Irp_Vbcp;
		*Iccp_Vbep=(*Iccp_Vbep)+Iccp_qbp*qbp_Vbep;
		*Iccp_Vbci=(*Iccp_Vbci)+Iccp_qbp*qbp_Vbci;
	}else{
		Ifp=0.0;
		Ifp_Vbep=0.0;
		Ifp_Vbci=0.0;
		qbp=1.0;
		qbp_Vbep=0.0;
		qbp_Vbci=0.0;
		(*Iccp)=0.0;
		*Iccp_Vbep=0.0;
		*Iccp_Vbci=0.0;
		*Iccp_Vbcp=0.0;
	}
	if(WBE==1.0){
		argi=(*Vbei)/(NEI*Vtv);
		argi_Vbei=1.0/(NEI*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbei=expi_argi*argi_Vbei;
		argn=(*Vbei)/(NEN*Vtv);
		argn_Vbei=1.0/(NEN*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbei=expn_argn*argn_Vbei;
		if(VBBE>0.0){
			argx=(-VBBE-(*Vbei))/(NBBE*Vtv);
			argx_Vbei=-1.0/(NBBE*Vtv);
			expx=exp(argx);
			expx_argx=expx;
			expx_Vbei=expx_argx*argx_Vbei;
			(*Ibe)=IBEI*(expi-1.0)+IBEN*(expn-1.0)-IBBE*(expx-EBBE);
			Ibe_expi=IBEI;
			Ibe_expn=IBEN;
			Ibe_expx=-IBBE;
			*Ibe_Vbei=Ibe_expi*expi_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expn*expn_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expx*expx_Vbei;
		}else{
			(*Ibe)=IBEI*(expi-1.0)+IBEN*(expn-1.0);
			Ibe_expi=IBEI;
			Ibe_expn=IBEN;
			*Ibe_Vbei=Ibe_expi*expi_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expn*expn_Vbei;
		}
		(*Ibex)=0.0;
		*Ibex_Vbex=0.0;
	}else if(WBE==0.0){
		(*Ibe)=0.0;
		*Ibe_Vbei=0.0;
		argi=(*Vbex)/(NEI*Vtv);
		argi_Vbex=1.0/(NEI*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbex=expi_argi*argi_Vbex;
		argn=(*Vbex)/(NEN*Vtv);
		argn_Vbex=1.0/(NEN*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbex=expn_argn*argn_Vbex;
		if(VBBE>0.0){
			argx=(-VBBE-(*Vbex))/(NBBE*Vtv);
			argx_Vbex=-1.0/(NBBE*Vtv);
			expx=exp(argx);
			expx_argx=expx;
			expx_Vbex=expx_argx*argx_Vbex;
			(*Ibex)=IBEI*(expi-1.0)+IBEN*(expn-1.0)-IBBE*(expx-EBBE);
			Ibex_expi=IBEI;
			Ibex_expn=IBEN;
			Ibex_expx=-IBBE;
			*Ibex_Vbex=Ibex_expi*expi_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expn*expn_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expx*expx_Vbex;
		}else{
			(*Ibex)=IBEI*(expi-1.0)+IBEN*(expn-1.0);
			Ibex_expi=IBEI;
			Ibex_expn=IBEN;
			*Ibex_Vbex=Ibex_expi*expi_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expn*expn_Vbex;
		}
	}else{
		argi=(*Vbei)/(NEI*Vtv);
		argi_Vbei=1.0/(NEI*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbei=expi_argi*argi_Vbei;
		argn=(*Vbei)/(NEN*Vtv);
		argn_Vbei=1.0/(NEN*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbei=expn_argn*argn_Vbei;
		if(VBBE>0.0){
			argx=(-VBBE-(*Vbei))/(NBBE*Vtv);
			argx_Vbei=-1.0/(NBBE*Vtv);
			expx=exp(argx);
			expx_argx=expx;
			expx_Vbei=expx_argx*argx_Vbei;
			(*Ibe)=WBE*(IBEI*(expi-1.0)+IBEN*(expn-1.0)-IBBE*(expx-EBBE));
			Ibe_expi=IBEI*WBE;
			Ibe_expn=IBEN*WBE;
			Ibe_expx=-IBBE*WBE;
			*Ibe_Vbei=Ibe_expi*expi_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expn*expn_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expx*expx_Vbei;
		}else{
			(*Ibe)=WBE*(IBEI*(expi-1.0)+IBEN*(expn-1.0));
			Ibe_expi=IBEI*WBE;
			Ibe_expn=IBEN*WBE;
			*Ibe_Vbei=Ibe_expi*expi_Vbei;
			*Ibe_Vbei=(*Ibe_Vbei)+Ibe_expn*expn_Vbei;
		}
		argi=(*Vbex)/(NEI*Vtv);
		argi_Vbex=1.0/(NEI*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbex=expi_argi*argi_Vbex;
		argn=(*Vbex)/(NEN*Vtv);
		argn_Vbex=1.0/(NEN*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbex=expn_argn*argn_Vbex;
		if(VBBE>0.0){
			argx=(-VBBE-(*Vbex))/(NBBE*Vtv);
			argx_Vbex=-1.0/(NBBE*Vtv);
			expx=exp(argx);
			expx_argx=expx;
			expx_Vbex=expx_argx*argx_Vbex;
			(*Ibex)=(1.0-WBE)*(IBEI*(expi-1.0)+IBEN*(expn-1.0)-IBBE*(expx-EBBE));
			Ibex_expi=IBEI*(1.0-WBE);
			Ibex_expn=IBEN*(1.0-WBE);
			Ibex_expx=-IBBE*(1.0-WBE);
			*Ibex_Vbex=Ibex_expi*expi_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expn*expn_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expx*expx_Vbex;
		}else{
			(*Ibex)=(1.0-WBE)*(IBEI*(expi-1.0)+IBEN*(expn-1.0));
			Ibex_expi=IBEI*(1.0-WBE);
			Ibex_expn=IBEN*(1.0-WBE);
			*Ibex_Vbex=Ibex_expi*expi_Vbex;
			*Ibex_Vbex=(*Ibex_Vbex)+Ibex_expn*expn_Vbex;
		}
	}
	argi=(*Vbci)/(NCI*Vtv);
	argi_Vbci=1.0/(NCI*Vtv);
	expi=exp(argi);
	expi_argi=expi;
	expi_Vbci=expi_argi*argi_Vbci;
	argn=(*Vbci)/(NCN*Vtv);
	argn_Vbci=1.0/(NCN*Vtv);
	expn=exp(argn);
	expn_argn=expn;
	expn_Vbci=expn_argn*argn_Vbci;
	Ibcj=IBCI*(expi-1.0)+IBCN*(expn-1.0);
	Ibcj_expi=IBCI;
	Ibcj_expn=IBCN;
	Ibcj_Vbci=Ibcj_expi*expi_Vbci;
	Ibcj_Vbci=Ibcj_Vbci+Ibcj_expn*expn_Vbci;
	if((IBEIP>0.0)||(IBENP>0.0)){
		argi=(*Vbep)/(NCI*Vtv);
		argi_Vbep=1.0/(NCI*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbep=expi_argi*argi_Vbep;
		argn=(*Vbep)/(NCN*Vtv);
		argn_Vbep=1.0/(NCN*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbep=expn_argn*argn_Vbep;
		(*Ibep)=IBEIP*(expi-1.0)+IBENP*(expn-1.0);
		Ibep_expi=IBEIP;
		Ibep_expn=IBENP;
		*Ibep_Vbep=Ibep_expi*expi_Vbep;
		*Ibep_Vbep=(*Ibep_Vbep)+Ibep_expn*expn_Vbep;
	}else{
		(*Ibep)=0.0;
		*Ibep_Vbep=0.0;
	}
	if(AVC1>0.0){
		vl=0.5*(sqrt((PC-(*Vbci))*(PC-(*Vbci))+0.01)+(PC-(*Vbci)));
		vl_Vbci=0.5*(-(PC-(*Vbci))/sqrt(((PC-(*Vbci))*(PC-(*Vbci)))+0.01)-1.0);
		xvar2=(MC-1.0);
		xvar3=pow(vl,xvar2);
		xvar3_vl=xvar3*xvar2/vl;
		xvar3_Vbci=xvar3_vl*vl_Vbci;
		xvar1=-AVC2*xvar3;
		xvar1_xvar3=-AVC2;
		xvar1_Vbci=xvar1_xvar3*xvar3_Vbci;
		xvar4=exp(xvar1);
		xvar4_xvar1=xvar4;
		xvar4_Vbci=xvar4_xvar1*xvar1_Vbci;
		avalf=AVC1*vl*xvar4;
		avalf_vl=AVC1*xvar4;
		avalf_xvar4=AVC1*vl;
		avalf_Vbci=avalf_vl*vl_Vbci;
		avalf_Vbci=avalf_Vbci+avalf_xvar4*xvar4_Vbci;
		Igc=((*Itzf)-(*Itzr)-Ibcj)*avalf;
		Igc_Itzf=avalf;
		Igc_Itzr=-avalf;
		Igc_Ibcj=-avalf;
		Igc_avalf=-(*Itzr)+(*Itzf)-Ibcj;
		Igc_Vbei=Igc_Itzf*(*Itzf_Vbei);
		Igc_Vbci=Igc_Itzf*(*Itzf_Vbci);
		Igc_Vbci=Igc_Vbci+Igc_Itzr*(*Itzr_Vbci);
		Igc_Vbei=Igc_Vbei+Igc_Itzr*(*Itzr_Vbei);
		Igc_Vbci=Igc_Vbci+Igc_Ibcj*Ibcj_Vbci;
		Igc_Vbci=Igc_Vbci+Igc_avalf*avalf_Vbci;
	}else{
		Igc=0.0;
		Igc_Vbei=0.0;
		Igc_Vbci=0.0;
	}
	(*Ibc)=Ibcj-Igc;
	Ibc_Ibcj=1.0;
	Ibc_Igc=-1.0;
	*Ibc_Vbci=Ibc_Ibcj*Ibcj_Vbci;
	*Ibc_Vbei=Ibc_Igc*Igc_Vbei;
	*Ibc_Vbci=(*Ibc_Vbci)+Ibc_Igc*Igc_Vbci;
	if(RCX>0.0){
		(*Ircx)=(*Vrcx)/RCX;
		*Ircx_Vrcx=1.0/RCX;
	}else{
		(*Ircx)=0.0;
		*Ircx_Vrcx=0.0;
	}
	argi=(*Vbci)/Vtv;
	argi_Vbci=1.0/Vtv;
	expi=exp(argi);
	expi_argi=expi;
	expi_Vbci=expi_argi*argi_Vbci;
	argx=(*Vbcx)/Vtv;
	argx_Vbcx=1.0/Vtv;
	expx=exp(argx);
	expx_argx=expx;
	expx_Vbcx=expx_argx*argx_Vbcx;
	Kbci=sqrt(1.0+GAMM*expi);
	Kbci_expi=GAMM/(2.0*sqrt(expi*GAMM+1.0));
	Kbci_Vbci=Kbci_expi*expi_Vbci;
	Kbcx=sqrt(1.0+GAMM*expx);
	Kbcx_expx=GAMM/(2.0*sqrt(expx*GAMM+1.0));
	Kbcx_Vbcx=Kbcx_expx*expx_Vbcx;
	if(RCI>0.0){
		rKp1=(Kbci+1.0)/(Kbcx+1.0);
		rKp1_Kbci=1.0/(Kbcx+1.0);
		rKp1_Kbcx=-(Kbci+1.0)/((Kbcx+1.0)*(Kbcx+1.0));
		rKp1_Vbci=rKp1_Kbci*Kbci_Vbci;
		rKp1_Vbcx=rKp1_Kbcx*Kbcx_Vbcx;
		xvar1=log(rKp1);
		xvar1_rKp1=1.0/rKp1;
		xvar1_Vbci=xvar1_rKp1*rKp1_Vbci;
		xvar1_Vbcx=xvar1_rKp1*rKp1_Vbcx;
		Iohm=((*Vrci)+Vtv*(Kbci-Kbcx-xvar1))/RCI;
		Iohm_Vrci=1.0/RCI;
		Iohm_Kbci=Vtv/RCI;
		Iohm_Kbcx=-Vtv/RCI;
		Iohm_xvar1=-Vtv/RCI;
		Iohm_Vbci=Iohm_Kbci*Kbci_Vbci;
		Iohm_Vbcx=Iohm_Kbcx*Kbcx_Vbcx;
		Iohm_Vbci=Iohm_Vbci+Iohm_xvar1*xvar1_Vbci;
		Iohm_Vbcx=Iohm_Vbcx+Iohm_xvar1*xvar1_Vbcx;
		derf=IVO*RCI*Iohm/(1.0+0.5*IVO*IHRCF*sqrt((*Vrci)*(*Vrci)+0.01));
		derf_Iohm=IVO*RCI/(0.5*IHRCF*IVO*sqrt(((*Vrci)*(*Vrci))+0.01)+1.0);
		derf_Vrci=-0.5*IHRCF*Iohm*(IVO*IVO)*RCI*(*Vrci)/(sqrt(((*Vrci)*(*Vrci))+0.01)*((0.5*IHRCF*IVO*sqrt(((*Vrci)*(*Vrci))+0.01)+1.0)*(0.5*IHRCF*IVO*sqrt(((*Vrci)*(*Vrci))+0.01)+1.0)));
		derf_Vrci=derf_Vrci+derf_Iohm*Iohm_Vrci;
		derf_Vbci=derf_Iohm*Iohm_Vbci;
		derf_Vbcx=derf_Iohm*Iohm_Vbcx;
		(*Irci)=Iohm/sqrt(1.0+derf*derf);
		Irci_Iohm=1.0/sqrt((derf*derf)+1.0);
		Irci_derf=-derf*Iohm/pow(((derf*derf)+1.0),(3.0/2.0));
		*Irci_Vrci=Irci_Iohm*Iohm_Vrci;
		*Irci_Vbci=Irci_Iohm*Iohm_Vbci;
		*Irci_Vbcx=Irci_Iohm*Iohm_Vbcx;
		*Irci_Vrci=(*Irci_Vrci)+Irci_derf*derf_Vrci;
		*Irci_Vbci=(*Irci_Vbci)+Irci_derf*derf_Vbci;
		*Irci_Vbcx=(*Irci_Vbcx)+Irci_derf*derf_Vbcx;
	}else{
		(*Irci)=0.0;
		*Irci_Vrci=0.0;
		*Irci_Vbci=0.0;
		*Irci_Vbcx=0.0;
	}
	if(RBX>0.0){
		(*Irbx)=(*Vrbx)/RBX;
		*Irbx_Vrbx=1.0/RBX;
	}else{
		(*Irbx)=0.0;
		*Irbx_Vrbx=0.0;
	}
	if(RBI>0.0){
		(*Irbi)=(*Vrbi)*qb/RBI;
		*Irbi_Vrbi=qb/RBI;
		Irbi_qb=(*Vrbi)/RBI;
		*Irbi_Vbei=Irbi_qb*qb_Vbei;
		*Irbi_Vbci=Irbi_qb*qb_Vbci;
	}else{
		(*Irbi)=0.0;
		*Irbi_Vrbi=0.0;
		*Irbi_Vbei=0.0;
		*Irbi_Vbci=0.0;
	}
	if(RE>0.0){
		(*Ire)=(*Vre)/RE;
		*Ire_Vre=1.0/RE;
	}else{
		(*Ire)=0.0;
		*Ire_Vre=0.0;
	}
	if(RBP>0.0){
		(*Irbp)=(*Vrbp)*qbp/RBP;
		*Irbp_Vrbp=qbp/RBP;
		Irbp_qbp=(*Vrbp)/RBP;
		*Irbp_Vbep=Irbp_qbp*qbp_Vbep;
		*Irbp_Vbci=Irbp_qbp*qbp_Vbci;
	}else{
		(*Irbp)=0.0;
		*Irbp_Vrbp=0.0;
		*Irbp_Vbep=0.0;
		*Irbp_Vbci=0.0;
	}
	if((IBCIP>0.0)||(IBCNP>0.0)){
		argi=(*Vbcp)/(NCIP*Vtv);
		argi_Vbcp=1.0/(NCIP*Vtv);
		expi=exp(argi);
		expi_argi=expi;
		expi_Vbcp=expi_argi*argi_Vbcp;
		argn=(*Vbcp)/(NCNP*Vtv);
		argn_Vbcp=1.0/(NCNP*Vtv);
		expn=exp(argn);
		expn_argn=expn;
		expn_Vbcp=expn_argn*argn_Vbcp;
		(*Ibcp)=IBCIP*(expi-1.0)+IBCNP*(expn-1.0);
		Ibcp_expi=IBCIP;
		Ibcp_expn=IBCNP;
		*Ibcp_Vbcp=Ibcp_expi*expi_Vbcp;
		*Ibcp_Vbcp=(*Ibcp_Vbcp)+Ibcp_expn*expn_Vbcp;
	}else{
		(*Ibcp)=0.0;
		*Ibcp_Vbcp=0.0;
	}
	if(RS>0.0){
		(*Irs)=(*Vrs)/RS;
		*Irs_Vrs=1.0/RS;
	}else{
		(*Irs)=0.0;
		*Irs_Vrs=0.0;
	}
	if(Ifi>0.0){
		sgIf=1.0;
	}else{
		sgIf=0.0;
	}
	rIf=Ifi*sgIf*IITF;
	rIf_Ifi=IITF*sgIf;
	rIf_Vbei=rIf_Ifi*Ifi_Vbei;
	mIf=rIf/(rIf+1.0);
	mIf_rIf=1.0/(rIf+1.0)-rIf/((rIf+1.0)*(rIf+1.0));
	mIf_Vbei=mIf_rIf*rIf_Vbei;
	xvar1=(*Vbci)*IVTF/1.44;
	xvar1_Vbci=0.6944444*IVTF;
	xvar2=exp(xvar1);
	xvar2_xvar1=xvar2;
	xvar2_Vbci=xvar2_xvar1*xvar1_Vbci;
	tff=TF*(1.0+QTF*q1)*(1.0+XTF*xvar2*(slTF+mIf*mIf)*sgIf);
	tff_q1=QTF*TF*(sgIf*(slTF+(mIf*mIf))*XTF*xvar2+1.0);
	tff_xvar2=(q1*QTF+1.0)*sgIf*(slTF+(mIf*mIf))*TF*XTF;
	tff_mIf=2.0*mIf*(q1*QTF+1.0)*sgIf*TF*XTF*xvar2;
	tff_Vbei=tff_q1*q1_Vbei;
	tff_Vbci=tff_q1*q1_Vbci;
	tff_Vbci=tff_Vbci+tff_xvar2*xvar2_Vbci;
	tff_Vbei=tff_Vbei+tff_mIf*mIf_Vbei;
	(*Qbe)=CJE*qdbe*WBE+tff*Ifi/qb;
	Qbe_qdbe=CJE*WBE;
	Qbe_tff=Ifi/qb;
	Qbe_Ifi=tff/qb;
	Qbe_qb=-Ifi*tff/(qb*qb);
	*Qbe_Vbei=Qbe_qdbe*qdbe_Vbei;
	*Qbe_Vbei=(*Qbe_Vbei)+Qbe_tff*tff_Vbei;
	*Qbe_Vbci=Qbe_tff*tff_Vbci;
	*Qbe_Vbei=(*Qbe_Vbei)+Qbe_Ifi*Ifi_Vbei;
	*Qbe_Vbei=(*Qbe_Vbei)+Qbe_qb*qb_Vbei;
	*Qbe_Vbci=(*Qbe_Vbci)+Qbe_qb*qb_Vbci;
	(*Qbex)=CJE*qdbex*(1.0-WBE);
	Qbex_qdbex=CJE*(1.0-WBE);
	*Qbex_Vbex=Qbex_qdbex*qdbex_Vbex;
	(*Qbc)=CJC*qdbc+TR*Iri+QCO*Kbci;
	Qbc_qdbc=CJC;
	Qbc_Iri=TR;
	Qbc_Kbci=QCO;
	*Qbc_Vbci=Qbc_qdbc*qdbc_Vbci;
	*Qbc_Vbci=(*Qbc_Vbci)+Qbc_Iri*Iri_Vbci;
	*Qbc_Vbci=(*Qbc_Vbci)+Qbc_Kbci*Kbci_Vbci;
	(*Qbcx)=QCO*Kbcx;
	Qbcx_Kbcx=QCO;
	*Qbcx_Vbcx=Qbcx_Kbcx*Kbcx_Vbcx;
	(*Qbep)=CJEP*qdbep+TR*Ifp;
	Qbep_qdbep=CJEP;
	Qbep_Ifp=TR;
	*Qbep_Vbep=Qbep_qdbep*qdbep_Vbep;
	*Qbep_Vbep=(*Qbep_Vbep)+Qbep_Ifp*Ifp_Vbep;
	*Qbep_Vbci=Qbep_Ifp*Ifp_Vbci;
	(*Qbcp)=CJCP*qdbcp+CCSO*(*Vbcp);
	Qbcp_qdbcp=CJCP;
	*Qbcp_Vbcp=CCSO;
	*Qbcp_Vbcp=(*Qbcp_Vbcp)+Qbcp_qdbcp*qdbcp_Vbcp;
	(*Qbeo)=(*Vbe)*CBEO;
	*Qbeo_Vbe=CBEO;
	(*Qbco)=(*Vbc)*CBCO;
	*Qbco_Vbc=CBCO;

/*	Scale outputs */

	if((*SCALE)!=1.0){
		*Ibe=(*SCALE)*(*Ibe);
		*Ibe_Vbei=(*SCALE)*(*Ibe_Vbei);
		*Ibex=(*SCALE)*(*Ibex);
		*Ibex_Vbex=(*SCALE)*(*Ibex_Vbex);
		*Itzf=(*SCALE)*(*Itzf);
		*Itzf_Vbei=(*SCALE)*(*Itzf_Vbei);
		*Itzf_Vbci=(*SCALE)*(*Itzf_Vbci);
		*Itzr=(*SCALE)*(*Itzr);
		*Itzr_Vbci=(*SCALE)*(*Itzr_Vbci);
		*Itzr_Vbei=(*SCALE)*(*Itzr_Vbei);
		*Ibc=(*SCALE)*(*Ibc);
		*Ibc_Vbci=(*SCALE)*(*Ibc_Vbci);
		*Ibc_Vbei=(*SCALE)*(*Ibc_Vbei);
		*Ibep=(*SCALE)*(*Ibep);
		*Ibep_Vbep=(*SCALE)*(*Ibep_Vbep);
		*Ircx=(*SCALE)*(*Ircx);
		*Ircx_Vrcx=(*SCALE)*(*Ircx_Vrcx);
		*Irci=(*SCALE)*(*Irci);
		*Irci_Vrci=(*SCALE)*(*Irci_Vrci);
		*Irci_Vbci=(*SCALE)*(*Irci_Vbci);
		*Irci_Vbcx=(*SCALE)*(*Irci_Vbcx);
		*Irbx=(*SCALE)*(*Irbx);
		*Irbx_Vrbx=(*SCALE)*(*Irbx_Vrbx);
		*Irbi=(*SCALE)*(*Irbi);
		*Irbi_Vrbi=(*SCALE)*(*Irbi_Vrbi);
		*Irbi_Vbei=(*SCALE)*(*Irbi_Vbei);
		*Irbi_Vbci=(*SCALE)*(*Irbi_Vbci);
		*Ire=(*SCALE)*(*Ire);
		*Ire_Vre=(*SCALE)*(*Ire_Vre);
		*Irbp=(*SCALE)*(*Irbp);
		*Irbp_Vrbp=(*SCALE)*(*Irbp_Vrbp);
		*Irbp_Vbep=(*SCALE)*(*Irbp_Vbep);
		*Irbp_Vbci=(*SCALE)*(*Irbp_Vbci);
		*Qbe=(*SCALE)*(*Qbe);
		*Qbe_Vbei=(*SCALE)*(*Qbe_Vbei);
		*Qbe_Vbci=(*SCALE)*(*Qbe_Vbci);
		*Qbex=(*SCALE)*(*Qbex);
		*Qbex_Vbex=(*SCALE)*(*Qbex_Vbex);
		*Qbc=(*SCALE)*(*Qbc);
		*Qbc_Vbci=(*SCALE)*(*Qbc_Vbci);
		*Qbcx=(*SCALE)*(*Qbcx);
		*Qbcx_Vbcx=(*SCALE)*(*Qbcx_Vbcx);
		*Qbep=(*SCALE)*(*Qbep);
		*Qbep_Vbep=(*SCALE)*(*Qbep_Vbep);
		*Qbep_Vbci=(*SCALE)*(*Qbep_Vbci);
		*Qbeo=(*SCALE)*(*Qbeo);
		*Qbeo_Vbe=(*SCALE)*(*Qbeo_Vbe);
		*Qbco=(*SCALE)*(*Qbco);
		*Qbco_Vbc=(*SCALE)*(*Qbco_Vbc);
		*Ibcp=(*SCALE)*(*Ibcp);
		*Ibcp_Vbcp=(*SCALE)*(*Ibcp_Vbcp);
		*Iccp=(*SCALE)*(*Iccp);
		*Iccp_Vbep=(*SCALE)*(*Iccp_Vbep);
		*Iccp_Vbci=(*SCALE)*(*Iccp_Vbci);
		*Iccp_Vbcp=(*SCALE)*(*Iccp_Vbcp);
		*Irs=(*SCALE)*(*Irs);
		*Irs_Vrs=(*SCALE)*(*Irs_Vrs);
		*Qbcp=(*SCALE)*(*Qbcp);
		*Qbcp_Vbcp=(*SCALE)*(*Qbcp_Vbcp);
	}
	return(0);
}
