      subroutine vbic_3T_et_xf_fj(p,Vrth,Vbei,Vbex,Vbci,Vbep,Vrxf,Vrcx
     +,Vbcx,Vrci,Vrbx,Vrbi,Vre,Vrbp,Vbe,Vbc,Vcei,Vcxf,Ibe,Ibe_Vrth
     +,Ibe_Vbei,Ibex,Ibex_Vrth,Ibex_Vbex,Itxf,Itxf_Vrxf,Itzr,Itzr_Vrth
     +,Itzr_Vbci,Itzr_Vbei,Ibc,Ibc_Vrth,Ibc_Vbci,Ibc_Vrxf,Ibc_Vbei,Ibep
     +,Ibep_Vrth,Ibep_Vbep,Ircx,Ircx_Vrcx,Ircx_Vrth,Irci,Irci_Vrci
     +,Irci_Vrth,Irci_Vbci,Irci_Vbcx,Irbx,Irbx_Vrbx,Irbx_Vrth,Irbi
     +,Irbi_Vrbi,Irbi_Vrth,Irbi_Vbei,Irbi_Vbci,Ire,Ire_Vre,Ire_Vrth,Irbp
     +,Irbp_Vrbp,Irbp_Vrth,Irbp_Vbep,Irbp_Vbci,Qbe,Qbe_Vrth,Qbe_Vbei
     +,Qbe_Vbci,Qbex,Qbex_Vrth,Qbex_Vbex,Qbc,Qbc_Vrth,Qbc_Vbci,Qbcx
     +,Qbcx_Vrth,Qbcx_Vbcx,Qbep,Qbep_Vrth,Qbep_Vbep,Qbep_Vbci,Qbeo
     +,Qbeo_Vbe,Qbco,Qbco_Vbc,Irth,Irth_Vrth,Ith,Ith_Vrth,Ith_Vbei
     +,Ith_Vbci,Ith_Vrxf,Ith_Vcei,Ith_Vbex,Ith_Vbep,Ith_Vrcx,Ith_Vrci
     +,Ith_Vbcx,Ith_Vrbx,Ith_Vrbi,Ith_Vre,Ith_Vrbp,Qcth,Qcth_Vrth,Ixzf
     +,Ixzf_Vrth,Ixzf_Vbei,Ixzf_Vbci,Ixxf,Ixxf_Vrxf,Qcxf,Qcxf_Vcxf,Flxf
     +,Flxf_Vrxf,SCALE)
      implicit double precision (a-z)
      double precision p(108)
c
c     Map parameter array into symbolic names
c
      TNOM=p(1)
      RCX=p(2)
      RCI=p(3)
      VO=p(4)
      GAMM=p(5)
      HRCF=p(6)
      RBX=p(7)
      RBI=p(8)
      RE=p(9)
      RS=p(10)
      RBP=p(11)
      IS=p(12)
      NF=p(13)
      NR=p(14)
      FC=p(15)
      CBEO=p(16)
      CJE=p(17)
      PE=p(18)
      ME=p(19)
      AJE=p(20)
      CBCO=p(21)
      CJC=p(22)
      QCO=p(23)
      CJEP=p(24)
      PC=p(25)
      MC=p(26)
      AJC=p(27)
      CJCP=p(28)
      PS=p(29)
      MS=p(30)
      IBEI=p(32)
      WBE=p(33)
      NEI=p(34)
      IBEN=p(35)
      NEN=p(36)
      IBCI=p(37)
      NCI=p(38)
      IBCN=p(39)
      NCN=p(40)
      AVC1=p(41)
      AVC2=p(42)
      ISP=p(43)
      WSP=p(44)
      NFP=p(45)
      IBEIP=p(46)
      IBENP=p(47)
      IBCIP=p(48)
      NCIP=p(49)
      IBCNP=p(50)
      NCNP=p(51)
      VEF=p(52)
      VER=p(53)
      IKF=p(54)
      IKR=p(55)
      IKP=p(56)
      TF=p(57)
      QTF=p(58)
      XTF=p(59)
      VTF=p(60)
      ITF=p(61)
      TR=p(62)
      TD=p(63)
      XRE=p(67)
      XRBI=p(68)
      XRCI=p(69)
      XRS=p(70)
      XVO=p(71)
      EA=p(72)
      EAIE=p(73)
      EAIC=p(74)
      EAIS=p(75)
      EANE=p(76)
      EANC=p(77)
      EANS=p(78)
      XIS=p(79)
      XII=p(80)
      XIN=p(81)
      TNF=p(82)
      TAVC=p(83)
      RTH=p(84)
      CTH=p(85)
      VRT=p(86)
      ART=p(87)
      QBM=p(89)
      NKF=p(90)
      XIKF=p(91)
      XRCX=p(92)
      XRBX=p(93)
      XRBP=p(94)
      ISRR=p(95)
      XISR=p(96)
      DEAR=p(97)
      EAP=p(98)
      VBBE=p(99)
      NBBE=p(100)
      IBBE=p(101)
      TVBBE1=p(102)
      TVBBE2=p(103)
      TNBBE=p(104)
c
c     Function and derivative code
c
      Tini=2.731500e+02+TNOM
      Tdev=(2.731500e+02+TNOM)+Vrth
      Tdev_Vrth=1.0
      Vtv=1.380662e-23*Tdev/1.602189e-19
      Vtv_Tdev=8.617347e-5
      Vtv_Vrth=Vtv_Tdev*Tdev_Vrth
      rT=Tdev/Tini
      rT_Tdev=1.0/Tini
      rT_Vrth=rT_Tdev*Tdev_Vrth
      dT=Tdev-Tini
      dT_Tdev=1.0
      dT_Vrth=dT_Tdev*Tdev_Vrth
      xvar1=rT**XIKF
      xvar1_rT=xvar1*XIKF/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      IKFatT=IKF*xvar1
      IKFatT_xvar1=IKF
      IKFatT_Vrth=IKFatT_xvar1*xvar1_Vrth
      xvar1=rT**XRCX
      xvar1_rT=xvar1*XRCX/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RCXatT=RCX*xvar1
      RCXatT_xvar1=RCX
      RCXatT_Vrth=RCXatT_xvar1*xvar1_Vrth
      xvar1=rT**XRCI
      xvar1_rT=xvar1*XRCI/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RCIatT=RCI*xvar1
      RCIatT_xvar1=RCI
      RCIatT_Vrth=RCIatT_xvar1*xvar1_Vrth
      xvar1=rT**XRBX
      xvar1_rT=xvar1*XRBX/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RBXatT=RBX*xvar1
      RBXatT_xvar1=RBX
      RBXatT_Vrth=RBXatT_xvar1*xvar1_Vrth
      xvar1=rT**XRBI
      xvar1_rT=xvar1*XRBI/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RBIatT=RBI*xvar1
      RBIatT_xvar1=RBI
      RBIatT_Vrth=RBIatT_xvar1*xvar1_Vrth
      xvar1=rT**XRE
      xvar1_rT=xvar1*XRE/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      REatT=RE*xvar1
      REatT_xvar1=RE
      REatT_Vrth=REatT_xvar1*xvar1_Vrth
      xvar1=rT**XRS
      xvar1_rT=xvar1*XRS/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RSatT=RS*xvar1
      RSatT_xvar1=RS
      RSatT_Vrth=RSatT_xvar1*xvar1_Vrth
      xvar1=rT**XRBP
      xvar1_rT=xvar1*XRBP/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      RBPatT=RBP*xvar1
      RBPatT_xvar1=RBP
      RBPatT_Vrth=RBPatT_xvar1*xvar1_Vrth
      xvar2=rT**XIS
      xvar2_rT=xvar2*XIS/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EA*(1.0-rT)/Vtv
      xvar3_rT=EA/Vtv
      xvar3_Vtv=EA*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NF)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      ISatT=IS*xvar6
      ISatT_xvar6=IS
      ISatT_Vrth=ISatT_xvar6*xvar6_Vrth
      xvar2=rT**XISR
      xvar2_rT=xvar2*XISR/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-DEAR*(1.0-rT)/Vtv
      xvar3_rT=DEAR/Vtv
      xvar3_Vtv=DEAR*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NR)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      ISRRatT=ISRR*xvar6
      ISRRatT_xvar6=ISRR
      ISRRatT_Vrth=ISRRatT_xvar6*xvar6_Vrth
      xvar2=rT**XIS
      xvar2_rT=xvar2*XIS/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EAP*(1.0-rT)/Vtv
      xvar3_rT=EAP/Vtv
      xvar3_Vtv=EAP*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NFP)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      ISPatT=ISP*xvar6
      ISPatT_xvar6=ISP
      ISPatT_Vrth=ISPatT_xvar6*xvar6_Vrth
      xvar2=rT**XII
      xvar2_rT=xvar2*XII/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EAIE*(1.0-rT)/Vtv
      xvar3_rT=EAIE/Vtv
      xvar3_Vtv=EAIE*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NEI)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBEIatT=IBEI*xvar6
      IBEIatT_xvar6=IBEI
      IBEIatT_Vrth=IBEIatT_xvar6*xvar6_Vrth
      xvar2=rT**XIN
      xvar2_rT=xvar2*XIN/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EANE*(1.0-rT)/Vtv
      xvar3_rT=EANE/Vtv
      xvar3_Vtv=EANE*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NEN)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBENatT=IBEN*xvar6
      IBENatT_xvar6=IBEN
      IBENatT_Vrth=IBENatT_xvar6*xvar6_Vrth
      xvar2=rT**XII
      xvar2_rT=xvar2*XII/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EAIC*(1.0-rT)/Vtv
      xvar3_rT=EAIC/Vtv
      xvar3_Vtv=EAIC*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCI)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBCIatT=IBCI*xvar6
      IBCIatT_xvar6=IBCI
      IBCIatT_Vrth=IBCIatT_xvar6*xvar6_Vrth
      xvar2=rT**XIN
      xvar2_rT=xvar2*XIN/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EANC*(1.0-rT)/Vtv
      xvar3_rT=EANC/Vtv
      xvar3_Vtv=EANC*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCN)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBCNatT=IBCN*xvar6
      IBCNatT_xvar6=IBCN
      IBCNatT_Vrth=IBCNatT_xvar6*xvar6_Vrth
      xvar2=rT**XII
      xvar2_rT=xvar2*XII/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EAIC*(1.0-rT)/Vtv
      xvar3_rT=EAIC/Vtv
      xvar3_Vtv=EAIC*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCI)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBEIPatT=IBEIP*xvar6
      IBEIPatT_xvar6=IBEIP
      IBEIPatT_Vrth=IBEIPatT_xvar6*xvar6_Vrth
      xvar2=rT**XIN
      xvar2_rT=xvar2*XIN/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EANC*(1.0-rT)/Vtv
      xvar3_rT=EANC/Vtv
      xvar3_Vtv=EANC*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCN)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBENPatT=IBENP*xvar6
      IBENPatT_xvar6=IBENP
      IBENPatT_Vrth=IBENPatT_xvar6*xvar6_Vrth
      xvar2=rT**XII
      xvar2_rT=xvar2*XII/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EAIS*(1.0-rT)/Vtv
      xvar3_rT=EAIS/Vtv
      xvar3_Vtv=EAIS*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCIP)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBCIPatT=IBCIP*xvar6
      IBCIPatT_xvar6=IBCIP
      IBCIPatT_Vrth=IBCIPatT_xvar6*xvar6_Vrth
      xvar2=rT**XIN
      xvar2_rT=xvar2*XIN/rT
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar3=-EANS*(1.0-rT)/Vtv
      xvar3_rT=EANS/Vtv
      xvar3_Vtv=EANS*(1.0-rT)/(Vtv*Vtv)
      xvar3_Vrth=xvar3_rT*rT_Vrth
      xvar3_Vrth=xvar3_Vrth+xvar3_Vtv*Vtv_Vrth
      xvar4=exp(xvar3)
      xvar4_xvar3=xvar4
      xvar4_Vrth=xvar4_xvar3*xvar3_Vrth
      xvar1=(xvar2*xvar4)
      xvar1_xvar2=xvar4
      xvar1_xvar4=xvar2
      xvar1_Vrth=xvar1_xvar2*xvar2_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar4*xvar4_Vrth
      xvar5=(1.0/NCNP)
      xvar6=xvar1**xvar5
      xvar6_xvar1=xvar6*xvar5/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      IBCNPatT=IBCNP*xvar6
      IBCNPatT_xvar6=IBCNP
      IBCNPatT_Vrth=IBCNPatT_xvar6*xvar6_Vrth
      NFatT=NF*(1.0+dT*TNF)
      NFatT_dT=NF*TNF
      NFatT_Vrth=NFatT_dT*dT_Vrth
      NRatT=NR*(1.0+dT*TNF)
      NRatT_dT=NR*TNF
      NRatT_Vrth=NRatT_dT*dT_Vrth
      AVC2atT=AVC2*(1.0+dT*TAVC)
      AVC2atT_dT=AVC2*TAVC
      AVC2atT_Vrth=AVC2atT_dT*dT_Vrth
      VBBEatT=VBBE*(1.0+dT*(TVBBE1+dT*TVBBE2))
      VBBEatT_dT=(2.0*dT*TVBBE2+TVBBE1)*VBBE
      VBBEatT_Vrth=VBBEatT_dT*dT_Vrth
      NBBEatT=NBBE*(1.0+dT*TNBBE)
      NBBEatT_dT=NBBE*TNBBE
      NBBEatT_Vrth=NBBEatT_dT*dT_Vrth
      xvar2=0.5*PE*rT/Vtv
      xvar2_rT=0.5*PE/Vtv
      xvar2_Vtv=-0.5*PE*rT/(Vtv*Vtv)
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar4=-0.5*PE*rT/Vtv
      xvar4_rT=-0.5*PE/Vtv
      xvar4_Vtv=0.5*PE*rT/(Vtv*Vtv)
      xvar4_Vrth=xvar4_rT*rT_Vrth
      xvar4_Vrth=xvar4_Vrth+xvar4_Vtv*Vtv_Vrth
      xvar5=exp(xvar4)
      xvar5_xvar4=xvar5
      xvar5_Vrth=xvar5_xvar4*xvar4_Vrth
      xvar1=xvar3-xvar5
      xvar1_xvar3=1.0
      xvar1_xvar5=-1.0
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar5*xvar5_Vrth
      xvar6=log(xvar1)
      xvar6_xvar1=1.0/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      psiio=2.0*(Vtv/rT)*xvar6
      psiio_Vtv=2.0*xvar6/rT
      psiio_rT=-2.0*Vtv*xvar6/(rT*rT)
      psiio_xvar6=2.0*Vtv/rT
      psiio_Vrth=psiio_Vtv*Vtv_Vrth
      psiio_Vrth=psiio_Vrth+psiio_rT*rT_Vrth
      psiio_Vrth=psiio_Vrth+psiio_xvar6*xvar6_Vrth
      xvar1=log(rT)
      xvar1_rT=1.0/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      psiin=psiio*rT-3.0*Vtv*xvar1-EAIE*(rT-1.0)
      psiin_psiio=rT
      psiin_rT=psiio-EAIE
      psiin_Vtv=-3.0*xvar1
      psiin_xvar1=-3.0*Vtv
      psiin_Vrth=psiin_psiio*psiio_Vrth
      psiin_Vrth=psiin_Vrth+psiin_rT*rT_Vrth
      psiin_Vrth=psiin_Vrth+psiin_Vtv*Vtv_Vrth
      psiin_Vrth=psiin_Vrth+psiin_xvar1*xvar1_Vrth
      xvar2=-psiin/Vtv
      xvar2_psiin=-1.0/Vtv
      xvar2_Vtv=psiin/(Vtv*Vtv)
      xvar2_Vrth=xvar2_psiin*psiin_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3))
      xvar1_xvar3=1.0/sqrt(4.0*xvar3+1.0)
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar4=log(xvar1)
      xvar4_xvar1=1.0/xvar1
      xvar4_Vrth=xvar4_xvar1*xvar1_Vrth
      PEatT=psiin+2.0*Vtv*xvar4
      PEatT_psiin=1.0
      PEatT_Vtv=2.0*xvar4
      PEatT_xvar4=2.0*Vtv
      PEatT_Vrth=PEatT_psiin*psiin_Vrth
      PEatT_Vrth=PEatT_Vrth+PEatT_Vtv*Vtv_Vrth
      PEatT_Vrth=PEatT_Vrth+PEatT_xvar4*xvar4_Vrth
      xvar2=0.5*PC*rT/Vtv
      xvar2_rT=0.5*PC/Vtv
      xvar2_Vtv=-0.5*PC*rT/(Vtv*Vtv)
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar4=-0.5*PC*rT/Vtv
      xvar4_rT=-0.5*PC/Vtv
      xvar4_Vtv=0.5*PC*rT/(Vtv*Vtv)
      xvar4_Vrth=xvar4_rT*rT_Vrth
      xvar4_Vrth=xvar4_Vrth+xvar4_Vtv*Vtv_Vrth
      xvar5=exp(xvar4)
      xvar5_xvar4=xvar5
      xvar5_Vrth=xvar5_xvar4*xvar4_Vrth
      xvar1=xvar3-xvar5
      xvar1_xvar3=1.0
      xvar1_xvar5=-1.0
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar5*xvar5_Vrth
      xvar6=log(xvar1)
      xvar6_xvar1=1.0/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      psiio=2.0*(Vtv/rT)*xvar6
      psiio_Vtv=2.0*xvar6/rT
      psiio_rT=-2.0*Vtv*xvar6/(rT*rT)
      psiio_xvar6=2.0*Vtv/rT
      psiio_Vrth=psiio_Vtv*Vtv_Vrth
      psiio_Vrth=psiio_Vrth+psiio_rT*rT_Vrth
      psiio_Vrth=psiio_Vrth+psiio_xvar6*xvar6_Vrth
      xvar1=log(rT)
      xvar1_rT=1.0/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      psiin=psiio*rT-3.0*Vtv*xvar1-EAIC*(rT-1.0)
      psiin_psiio=rT
      psiin_rT=psiio-EAIC
      psiin_Vtv=-3.0*xvar1
      psiin_xvar1=-3.0*Vtv
      psiin_Vrth=psiin_psiio*psiio_Vrth
      psiin_Vrth=psiin_Vrth+psiin_rT*rT_Vrth
      psiin_Vrth=psiin_Vrth+psiin_Vtv*Vtv_Vrth
      psiin_Vrth=psiin_Vrth+psiin_xvar1*xvar1_Vrth
      xvar2=-psiin/Vtv
      xvar2_psiin=-1.0/Vtv
      xvar2_Vtv=psiin/(Vtv*Vtv)
      xvar2_Vrth=xvar2_psiin*psiin_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3))
      xvar1_xvar3=1.0/sqrt(4.0*xvar3+1.0)
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar4=log(xvar1)
      xvar4_xvar1=1.0/xvar1
      xvar4_Vrth=xvar4_xvar1*xvar1_Vrth
      PCatT=psiin+2.0*Vtv*xvar4
      PCatT_psiin=1.0
      PCatT_Vtv=2.0*xvar4
      PCatT_xvar4=2.0*Vtv
      PCatT_Vrth=PCatT_psiin*psiin_Vrth
      PCatT_Vrth=PCatT_Vrth+PCatT_Vtv*Vtv_Vrth
      PCatT_Vrth=PCatT_Vrth+PCatT_xvar4*xvar4_Vrth
      xvar2=0.5*PS*rT/Vtv
      xvar2_rT=0.5*PS/Vtv
      xvar2_Vtv=-0.5*PS*rT/(Vtv*Vtv)
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar4=-0.5*PS*rT/Vtv
      xvar4_rT=-0.5*PS/Vtv
      xvar4_Vtv=0.5*PS*rT/(Vtv*Vtv)
      xvar4_Vrth=xvar4_rT*rT_Vrth
      xvar4_Vrth=xvar4_Vrth+xvar4_Vtv*Vtv_Vrth
      xvar5=exp(xvar4)
      xvar5_xvar4=xvar5
      xvar5_Vrth=xvar5_xvar4*xvar4_Vrth
      xvar1=xvar3-xvar5
      xvar1_xvar3=1.0
      xvar1_xvar5=-1.0
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_xvar5*xvar5_Vrth
      xvar6=log(xvar1)
      xvar6_xvar1=1.0/xvar1
      xvar6_Vrth=xvar6_xvar1*xvar1_Vrth
      psiio=2.0*(Vtv/rT)*xvar6
      psiio_Vtv=2.0*xvar6/rT
      psiio_rT=-2.0*Vtv*xvar6/(rT*rT)
      psiio_xvar6=2.0*Vtv/rT
      psiio_Vrth=psiio_Vtv*Vtv_Vrth
      psiio_Vrth=psiio_Vrth+psiio_rT*rT_Vrth
      psiio_Vrth=psiio_Vrth+psiio_xvar6*xvar6_Vrth
      xvar1=log(rT)
      xvar1_rT=1.0/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      psiin=psiio*rT-3.0*Vtv*xvar1-EAIS*(rT-1.0)
      psiin_psiio=rT
      psiin_rT=psiio-EAIS
      psiin_Vtv=-3.0*xvar1
      psiin_xvar1=-3.0*Vtv
      psiin_Vrth=psiin_psiio*psiio_Vrth
      psiin_Vrth=psiin_Vrth+psiin_rT*rT_Vrth
      psiin_Vrth=psiin_Vrth+psiin_Vtv*Vtv_Vrth
      psiin_Vrth=psiin_Vrth+psiin_xvar1*xvar1_Vrth
      xvar2=-psiin/Vtv
      xvar2_psiin=-1.0/Vtv
      xvar2_Vtv=psiin/(Vtv*Vtv)
      xvar2_Vrth=xvar2_psiin*psiin_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3))
      xvar1_xvar3=1.0/sqrt(4.0*xvar3+1.0)
      xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
      xvar4=log(xvar1)
      xvar4_xvar1=1.0/xvar1
      xvar4_Vrth=xvar4_xvar1*xvar1_Vrth
      PSatT=psiin+2.0*Vtv*xvar4
      PSatT_psiin=1.0
      PSatT_Vtv=2.0*xvar4
      PSatT_xvar4=2.0*Vtv
      PSatT_Vrth=PSatT_psiin*psiin_Vrth
      PSatT_Vrth=PSatT_Vrth+PSatT_Vtv*Vtv_Vrth
      PSatT_Vrth=PSatT_Vrth+PSatT_xvar4*xvar4_Vrth
      xvar1=PE/PEatT
      xvar1_PEatT=-PE/(PEatT*PEatT)
      xvar1_Vrth=xvar1_PEatT*PEatT_Vrth
      xvar2=xvar1**ME
      xvar2_xvar1=xvar2*ME/xvar1
      xvar2_Vrth=xvar2_xvar1*xvar1_Vrth
      CJEatT=CJE*xvar2
      CJEatT_xvar2=CJE
      CJEatT_Vrth=CJEatT_xvar2*xvar2_Vrth
      xvar1=PC/PCatT
      xvar1_PCatT=-PC/(PCatT*PCatT)
      xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
      xvar2=xvar1**MC
      xvar2_xvar1=xvar2*MC/xvar1
      xvar2_Vrth=xvar2_xvar1*xvar1_Vrth
      CJCatT=CJC*xvar2
      CJCatT_xvar2=CJC
      CJCatT_Vrth=CJCatT_xvar2*xvar2_Vrth
      xvar1=PC/PCatT
      xvar1_PCatT=-PC/(PCatT*PCatT)
      xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
      xvar2=xvar1**MC
      xvar2_xvar1=xvar2*MC/xvar1
      xvar2_Vrth=xvar2_xvar1*xvar1_Vrth
      CJEPatT=CJEP*xvar2
      CJEPatT_xvar2=CJEP
      CJEPatT_Vrth=CJEPatT_xvar2*xvar2_Vrth
      xvar1=PS/PSatT
      xvar1_PSatT=-PS/(PSatT*PSatT)
      xvar1_Vrth=xvar1_PSatT*PSatT_Vrth
      xvar2=xvar1**MS
      xvar2_xvar1=xvar2*MS/xvar1
      xvar2_Vrth=xvar2_xvar1*xvar1_Vrth
      CJCPatT=CJCP*xvar2
      CJCPatT_xvar2=CJCP
      CJCPatT_Vrth=CJCPatT_xvar2*xvar2_Vrth
      xvar1=rT**XIS
      xvar1_rT=xvar1*XIS/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      xvar2=-EA*(1.0-rT)/Vtv
      xvar2_rT=EA/Vtv
      xvar2_Vtv=EA*(1.0-rT)/(Vtv*Vtv)
      xvar2_Vrth=xvar2_rT*rT_Vrth
      xvar2_Vrth=xvar2_Vrth+xvar2_Vtv*Vtv_Vrth
      xvar3=exp(xvar2)
      xvar3_xvar2=xvar3
      xvar3_Vrth=xvar3_xvar2*xvar2_Vrth
      GAMMatT=GAMM*xvar1*xvar3
      GAMMatT_xvar1=GAMM*xvar3
      GAMMatT_xvar3=GAMM*xvar1
      GAMMatT_Vrth=GAMMatT_xvar1*xvar1_Vrth
      GAMMatT_Vrth=GAMMatT_Vrth+GAMMatT_xvar3*xvar3_Vrth
      xvar1=rT**XVO
      xvar1_rT=xvar1*XVO/rT
      xvar1_Vrth=xvar1_rT*rT_Vrth
      VOatT=VO*xvar1
      VOatT_xvar1=VO
      VOatT_Vrth=VOatT_xvar1*xvar1_Vrth
      xvar1=-VBBEatT/(NBBEatT*Vtv)
      xvar1_VBBEatT=-1.0/(NBBEatT*Vtv)
      xvar1_NBBEatT=VBBEatT/((NBBEatT*NBBEatT)*Vtv)
      xvar1_Vtv=VBBEatT/(NBBEatT*(Vtv*Vtv))
      xvar1_Vrth=xvar1_VBBEatT*VBBEatT_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_NBBEatT*NBBEatT_Vrth
      xvar1_Vrth=xvar1_Vrth+xvar1_Vtv*Vtv_Vrth
      EBBEatT=exp(xvar1)
      EBBEatT_xvar1=EBBEatT
      EBBEatT_Vrth=EBBEatT_xvar1*xvar1_Vrth
      if(VEF.GT.0.0)then
         IVEF=1.0/VEF
      else
         IVEF=0.0
      endif
      if(VER.GT.0.0)then
         IVER=1.0/VER
      else
         IVER=0.0
      endif
      if(IKF.GT.0.0)then
         IIKF=1.0/IKFatT
         IIKF_IKFatT=-1.0/(IKFatT*IKFatT)
         IIKF_Vrth=IIKF_IKFatT*IKFatT_Vrth
      else
         IIKF=0.0
         IIKF_Vrth=0.0
      endif
      if(IKR.GT.0.0)then
         IIKR=1.0/IKR
      else
         IIKR=0.0
      endif
      if(IKP.GT.0.0)then
         IIKP=1.0/IKP
      else
         IIKP=0.0
      endif
      if(VO.GT.0.0)then
         IVO=1.0/VOatT
         IVO_VOatT=-1.0/(VOatT*VOatT)
         IVO_Vrth=IVO_VOatT*VOatT_Vrth
      else
         IVO=0.0
         IVO_Vrth=0.0
      endif
      if(HRCF.GT.0.0)then
         IHRCF=1.0/HRCF
      else
         IHRCF=0.0
      endif
      if(VTF.GT.0.0)then
         IVTF=1.0/VTF
      else
         IVTF=0.0
      endif
      if(ITF.GT.0.0)then
         IITF=1.0/ITF
      else
         IITF=0.0
      endif
      if(ITF.GT.0.0)then
         slTF=0.0
      else
         slTF=1.0
      endif
      if(TD.GT.0.0)then
         LEP=TD/3.0
      else
         LEP=0.0
      endif
      if(TD.GT.0.0)then
         CEP=TD
      else
         CEP=0.0
      endif
      dv0=-PEatT*FC
      dv0_PEatT=-FC
      dv0_Vrth=dv0_PEatT*PEatT_Vrth
      if(AJE.LE.0.0)then
         dvh=Vbei+dv0
         dvh_Vbei=1.0
         dvh_dv0=1.0
         dvh_Vrth=dvh_dv0*dv0_Vrth
         if(dvh.GT.0.0)then
            xvar1=(1.0-FC)
            xvar2=(-1.0-ME)
            pwq=xvar1**xvar2
            qlo=PEatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME)
            qlo_PEatT=(1.0-((1.0-FC)*(1.0-FC))*pwq)/(1.0-ME)
            qlo_Vbei=0.0
            qlo_Vrth=qlo_PEatT*PEatT_Vrth
            qhi=dvh*(1.0-FC+0.5*ME*dvh/PEatT)*pwq
            qhi_dvh=(0.5*dvh*ME/PEatT-FC+1.0)*pwq+0.5*dvh*ME*pwq/PEatT
            qhi_PEatT=-0.5*(dvh*dvh)*ME*pwq/(PEatT*PEatT)
            qhi_Vbei=qhi_dvh*dvh_Vbei
            qhi_Vrth=qhi_dvh*dvh_Vrth
            qhi_Vrth=qhi_Vrth+qhi_PEatT*PEatT_Vrth
         else
            xvar1=(1.0-Vbei/PEatT)
            xvar1_Vbei=-1.0/PEatT
            xvar1_PEatT=Vbei/(PEatT*PEatT)
            xvar1_Vrth=xvar1_PEatT*PEatT_Vrth
            xvar2=(1.0-ME)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbei=xvar3_xvar1*xvar1_Vbei
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=PEatT*(1.0-xvar3)/(1.0-ME)
            qlo_PEatT=(1.0-xvar3)/(1.0-ME)
            qlo_xvar3=-PEatT/(1.0-ME)
            qlo_Vrth=qlo_PEatT*PEatT_Vrth
            qlo_Vbei=qlo_xvar3*xvar3_Vbei
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            qhi=0.0
            qhi_Vbei=0.0
            qhi_Vrth=0.0
         endif
         qdbe=qlo+qhi
         qdbe_qlo=1.0
         qdbe_qhi=1.0
         qdbe_Vrth=qdbe_qlo*qlo_Vrth
         qdbe_Vbei=qdbe_qlo*qlo_Vbei
         qdbe_Vbei=qdbe_Vbei+qdbe_qhi*qhi_Vbei
         qdbe_Vrth=qdbe_Vrth+qdbe_qhi*qhi_Vrth
      else
         mv0=sqrt(dv0*dv0+4.0*AJE*AJE)
         mv0_dv0=dv0/sqrt((dv0*dv0)+4.0*(AJE*AJE))
         mv0_Vrth=mv0_dv0*dv0_Vrth
         vl0=-0.5*(dv0+mv0)
         vl0_dv0=-0.5
         vl0_mv0=-0.5
         vl0_Vrth=vl0_dv0*dv0_Vrth
         vl0_Vrth=vl0_Vrth+vl0_mv0*mv0_Vrth
         xvar1=(1.0-vl0/PEatT)
         xvar1_vl0=-1.0/PEatT
         xvar1_PEatT=vl0/(PEatT*PEatT)
         xvar1_Vrth=xvar1_vl0*vl0_Vrth
         xvar1_Vrth=xvar1_Vrth+xvar1_PEatT*PEatT_Vrth
         xvar2=(1.0-ME)
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
         q0=-PEatT*xvar3/(1.0-ME)
         q0_PEatT=-xvar3/(1.0-ME)
         q0_xvar3=-PEatT/(1.0-ME)
         q0_Vrth=q0_PEatT*PEatT_Vrth
         q0_Vrth=q0_Vrth+q0_xvar3*xvar3_Vrth
         dv=Vbei+dv0
         dv_Vbei=1.0
         dv_dv0=1.0
         dv_Vrth=dv_dv0*dv0_Vrth
         mv=sqrt(dv*dv+4.0*AJE*AJE)
         mv_dv=dv/sqrt((dv*dv)+4.0*(AJE*AJE))
         mv_Vbei=mv_dv*dv_Vbei
         mv_Vrth=mv_dv*dv_Vrth
         vl=0.5*(dv-mv)-dv0
         vl_dv=0.5
         vl_mv=-0.5
         vl_dv0=-1.0
         vl_Vbei=vl_dv*dv_Vbei
         vl_Vrth=vl_dv*dv_Vrth
         vl_Vbei=vl_Vbei+vl_mv*mv_Vbei
         vl_Vrth=vl_Vrth+vl_mv*mv_Vrth
         vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
         xvar1=(1.0-vl/PEatT)
         xvar1_vl=-1.0/PEatT
         xvar1_PEatT=vl/(PEatT*PEatT)
         xvar1_Vbei=xvar1_vl*vl_Vbei
         xvar1_Vrth=xvar1_vl*vl_Vrth
         xvar1_Vrth=xvar1_Vrth+xvar1_PEatT*PEatT_Vrth
         xvar2=(1.0-ME)
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vbei=xvar3_xvar1*xvar1_Vbei
         xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
         qlo=-PEatT*xvar3/(1.0-ME)
         qlo_PEatT=-xvar3/(1.0-ME)
         qlo_xvar3=-PEatT/(1.0-ME)
         qlo_Vrth=qlo_PEatT*PEatT_Vrth
         qlo_Vbei=qlo_xvar3*xvar3_Vbei
         qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
         xvar1=(1.0-FC)
         xvar2=(-ME)
         xvar3=xvar1**xvar2
         qdbe=qlo+xvar3*(Vbei-vl+vl0)-q0
         qdbe_qlo=1.0
         qdbe_Vbei=xvar3
         qdbe_vl=-xvar3
         qdbe_vl0=xvar3
         qdbe_q0=-1.0
         qdbe_Vrth=qdbe_qlo*qlo_Vrth
         qdbe_Vbei=qdbe_Vbei+qdbe_qlo*qlo_Vbei
         qdbe_Vbei=qdbe_Vbei+qdbe_vl*vl_Vbei
         qdbe_Vrth=qdbe_Vrth+qdbe_vl*vl_Vrth
         qdbe_Vrth=qdbe_Vrth+qdbe_vl0*vl0_Vrth
         qdbe_Vrth=qdbe_Vrth+qdbe_q0*q0_Vrth
      endif
      dv0=-PEatT*FC
      dv0_PEatT=-FC
      dv0_Vrth=dv0_PEatT*PEatT_Vrth
      if(AJE.LE.0.0)then
         dvh=Vbex+dv0
         dvh_Vbex=1.0
         dvh_dv0=1.0
         dvh_Vrth=dvh_dv0*dv0_Vrth
         if(dvh.GT.0.0)then
            xvar1=(1.0-FC)
            xvar2=(-1.0-ME)
            pwq=xvar1**xvar2
            qlo=PEatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME)
            qlo_PEatT=(1.0-((1.0-FC)*(1.0-FC))*pwq)/(1.0-ME)
            qlo_Vbex=0.0
            qlo_Vrth=qlo_PEatT*PEatT_Vrth
            qhi=dvh*(1.0-FC+0.5*ME*dvh/PEatT)*pwq
            qhi_dvh=(0.5*dvh*ME/PEatT-FC+1.0)*pwq+0.5*dvh*ME*pwq/PEatT
            qhi_PEatT=-0.5*(dvh*dvh)*ME*pwq/(PEatT*PEatT)
            qhi_Vbex=qhi_dvh*dvh_Vbex
            qhi_Vrth=qhi_dvh*dvh_Vrth
            qhi_Vrth=qhi_Vrth+qhi_PEatT*PEatT_Vrth
         else
            xvar1=(1.0-Vbex/PEatT)
            xvar1_Vbex=-1.0/PEatT
            xvar1_PEatT=Vbex/(PEatT*PEatT)
            xvar1_Vrth=xvar1_PEatT*PEatT_Vrth
            xvar2=(1.0-ME)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbex=xvar3_xvar1*xvar1_Vbex
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=PEatT*(1.0-xvar3)/(1.0-ME)
            qlo_PEatT=(1.0-xvar3)/(1.0-ME)
            qlo_xvar3=-PEatT/(1.0-ME)
            qlo_Vrth=qlo_PEatT*PEatT_Vrth
            qlo_Vbex=qlo_xvar3*xvar3_Vbex
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            qhi=0.0
            qhi_Vbex=0.0
            qhi_Vrth=0.0
         endif
         qdbex=qlo+qhi
         qdbex_qlo=1.0
         qdbex_qhi=1.0
         qdbex_Vrth=qdbex_qlo*qlo_Vrth
         qdbex_Vbex=qdbex_qlo*qlo_Vbex
         qdbex_Vbex=qdbex_Vbex+qdbex_qhi*qhi_Vbex
         qdbex_Vrth=qdbex_Vrth+qdbex_qhi*qhi_Vrth
      else
         mv0=sqrt(dv0*dv0+4.0*AJE*AJE)
         mv0_dv0=dv0/sqrt((dv0*dv0)+4.0*(AJE*AJE))
         mv0_Vrth=mv0_dv0*dv0_Vrth
         vl0=-0.5*(dv0+mv0)
         vl0_dv0=-0.5
         vl0_mv0=-0.5
         vl0_Vrth=vl0_dv0*dv0_Vrth
         vl0_Vrth=vl0_Vrth+vl0_mv0*mv0_Vrth
         xvar1=(1.0-vl0/PEatT)
         xvar1_vl0=-1.0/PEatT
         xvar1_PEatT=vl0/(PEatT*PEatT)
         xvar1_Vrth=xvar1_vl0*vl0_Vrth
         xvar1_Vrth=xvar1_Vrth+xvar1_PEatT*PEatT_Vrth
         xvar2=(1.0-ME)
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
         q0=-PEatT*xvar3/(1.0-ME)
         q0_PEatT=-xvar3/(1.0-ME)
         q0_xvar3=-PEatT/(1.0-ME)
         q0_Vrth=q0_PEatT*PEatT_Vrth
         q0_Vrth=q0_Vrth+q0_xvar3*xvar3_Vrth
         dv=Vbex+dv0
         dv_Vbex=1.0
         dv_dv0=1.0
         dv_Vrth=dv_dv0*dv0_Vrth
         mv=sqrt(dv*dv+4.0*AJE*AJE)
         mv_dv=dv/sqrt((dv*dv)+4.0*(AJE*AJE))
         mv_Vbex=mv_dv*dv_Vbex
         mv_Vrth=mv_dv*dv_Vrth
         vl=0.5*(dv-mv)-dv0
         vl_dv=0.5
         vl_mv=-0.5
         vl_dv0=-1.0
         vl_Vbex=vl_dv*dv_Vbex
         vl_Vrth=vl_dv*dv_Vrth
         vl_Vbex=vl_Vbex+vl_mv*mv_Vbex
         vl_Vrth=vl_Vrth+vl_mv*mv_Vrth
         vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
         xvar1=(1.0-vl/PEatT)
         xvar1_vl=-1.0/PEatT
         xvar1_PEatT=vl/(PEatT*PEatT)
         xvar1_Vbex=xvar1_vl*vl_Vbex
         xvar1_Vrth=xvar1_vl*vl_Vrth
         xvar1_Vrth=xvar1_Vrth+xvar1_PEatT*PEatT_Vrth
         xvar2=(1.0-ME)
         xvar3=xvar1**xvar2
         xvar3_xvar1=xvar3*xvar2/xvar1
         xvar3_Vbex=xvar3_xvar1*xvar1_Vbex
         xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
         qlo=-PEatT*xvar3/(1.0-ME)
         qlo_PEatT=-xvar3/(1.0-ME)
         qlo_xvar3=-PEatT/(1.0-ME)
         qlo_Vrth=qlo_PEatT*PEatT_Vrth
         qlo_Vbex=qlo_xvar3*xvar3_Vbex
         qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
         xvar1=(1.0-FC)
         xvar2=(-ME)
         xvar3=xvar1**xvar2
         qdbex=qlo+xvar3*(Vbex-vl+vl0)-q0
         qdbex_qlo=1.0
         qdbex_Vbex=xvar3
         qdbex_vl=-xvar3
         qdbex_vl0=xvar3
         qdbex_q0=-1.0
         qdbex_Vrth=qdbex_qlo*qlo_Vrth
         qdbex_Vbex=qdbex_Vbex+qdbex_qlo*qlo_Vbex
         qdbex_Vbex=qdbex_Vbex+qdbex_vl*vl_Vbex
         qdbex_Vrth=qdbex_Vrth+qdbex_vl*vl_Vrth
         qdbex_Vrth=qdbex_Vrth+qdbex_vl0*vl0_Vrth
         qdbex_Vrth=qdbex_Vrth+qdbex_q0*q0_Vrth
      endif
      dv0=-PCatT*FC
      dv0_PCatT=-FC
      dv0_Vrth=dv0_PCatT*PCatT_Vrth
      if(AJC.LE.0.0)then
         dvh=Vbci+dv0
         dvh_Vbci=1.0
         dvh_dv0=1.0
         dvh_Vrth=dvh_dv0*dv0_Vrth
         if(dvh.GT.0.0)then
            xvar1=(1.0-FC)
            xvar2=(-1.0-MC)
            pwq=xvar1**xvar2
            qlo=PCatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC)
            qlo_PCatT=(1.0-((1.0-FC)*(1.0-FC))*pwq)/(1.0-MC)
            qlo_Vbci=0.0
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qhi=dvh*(1.0-FC+0.5*MC*dvh/PCatT)*pwq
            qhi_dvh=(0.5*dvh*MC/PCatT-FC+1.0)*pwq+0.5*dvh*MC*pwq/PCatT
            qhi_PCatT=-0.5*(dvh*dvh)*MC*pwq/(PCatT*PCatT)
            qhi_Vbci=qhi_dvh*dvh_Vbci
            qhi_Vrth=qhi_dvh*dvh_Vrth
            qhi_Vrth=qhi_Vrth+qhi_PCatT*PCatT_Vrth
         else
            if((VRT.GT.0.0).AND.(Vbci.LT.-VRT))then
               xvar1=(1.0+VRT/PCatT)
               xvar1_PCatT=-VRT/(PCatT*PCatT)
               xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
               xvar2=(1.0-MC)
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
               qlo=PCatT*(1.0-xvar3*(1.0-((1.0-MC)*(Vbci+VRT))/(PCatT+VR
     +T)))/(1.0-MC)
               qlo_PCatT=(1.0-(1.0-(1.0-MC)*(VRT+Vbci)/(VRT+PCatT))*xvar
     +3)/(1.0-MC)-PCatT*(VRT+Vbci)*xvar3/((VRT+PCatT)*(VRT+PCatT))
               qlo_xvar3=PCatT*((1.0-MC)*(VRT+Vbci)/(VRT+PCatT)-1.0)/(1.
     +0-MC)
               qlo_Vbci=PCatT*xvar3/(VRT+PCatT)
               qlo_Vrth=qlo_PCatT*PCatT_Vrth
               qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            else
               xvar1=(1.0-Vbci/PCatT)
               xvar1_Vbci=-1.0/PCatT
               xvar1_PCatT=Vbci/(PCatT*PCatT)
               xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
               xvar2=(1.0-MC)
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
               xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
               qlo=PCatT*(1.0-xvar3)/(1.0-MC)
               qlo_PCatT=(1.0-xvar3)/(1.0-MC)
               qlo_xvar3=-PCatT/(1.0-MC)
               qlo_Vrth=qlo_PCatT*PCatT_Vrth
               qlo_Vbci=qlo_xvar3*xvar3_Vbci
               qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            endif
            qhi=0.0
            qhi_Vbci=0.0
            qhi_Vrth=0.0
         endif
         qdbc=qlo+qhi
         qdbc_qlo=1.0
         qdbc_qhi=1.0
         qdbc_Vrth=qdbc_qlo*qlo_Vrth
         qdbc_Vbci=qdbc_qlo*qlo_Vbci
         qdbc_Vbci=qdbc_Vbci+qdbc_qhi*qhi_Vbci
         qdbc_Vrth=qdbc_Vrth+qdbc_qhi*qhi_Vrth
      else
         if((VRT.GT.0.0).AND.(ART.GT.0.0))then
            vn0=(VRT+dv0)/(VRT-dv0)
            vn0_dv0=(VRT+dv0)/((VRT-dv0)*(VRT-dv0))+1.0/(VRT-dv0)
            vn0_Vrth=vn0_dv0*dv0_Vrth
            vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn
     +0+1.0)*(vn0+1.0)+4.0*ART*ART))
            vnl0_vn0=2.0/(sqrt(((vn0+1.0)*(vn0+1.0))+4.0*(ART*ART))+sqrt
     +(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC)))-2.0*vn0*((vn0+1.0)/sqrt(((v
     +n0+1.0)*(vn0+1.0))+4.0*(ART*ART))+(vn0-1.0)/sqrt(((vn0-1.0)*(vn0-1
     +.0))+4.0*(AJC*AJC)))/((sqrt(((vn0+1.0)*(vn0+1.0))+4.0*(ART*ART))+s
     +qrt(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn0+1.0)*(vn0+1.
     +0))+4.0*(ART*ART))+sqrt(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC))))
            vnl0_Vrth=vnl0_vn0*vn0_Vrth
            vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0)
            vl0_vnl0=0.5*(VRT-dv0)
            vl0_dv0=0.5*(-vnl0-1.0)
            vl0_Vrth=vl0_vnl0*vnl0_Vrth
            vl0_Vrth=vl0_Vrth+vl0_dv0*dv0_Vrth
            xvar1=(1.0-vl0/PCatT)
            xvar1_vl0=-1.0/PCatT
            xvar1_PCatT=vl0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_vl0*vl0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo0=PCatT*(1.0-xvar3)/(1.0-MC)
            qlo0_PCatT=(1.0-xvar3)/(1.0-MC)
            qlo0_xvar3=-PCatT/(1.0-MC)
            qlo0_Vrth=qlo0_PCatT*PCatT_Vrth
            qlo0_Vrth=qlo0_Vrth+qlo0_xvar3*xvar3_Vrth
            vn=(2.0*Vbci+VRT+dv0)/(VRT-dv0)
            vn_Vbci=2.0/(VRT-dv0)
            vn_dv0=(VRT+2.0*Vbci+dv0)/((VRT-dv0)*(VRT-dv0))+1.0/(VRT-dv0
     +)
            vn_Vrth=vn_dv0*dv0_Vrth
            vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0
     +)*(vn+1.0)+4.0*ART*ART))
            vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((v
     +n-1.0)*(vn-1.0))+4.0*(AJC*AJC)))-2.0*vn*((vn+1.0)/sqrt(((vn+1.0)*(
     +vn+1.0))+4.0*(ART*ART))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC
     +*AJC)))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(
     +vn-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+
     +sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC))))
            vnl_Vbci=vnl_vn*vn_Vbci
            vnl_Vrth=vnl_vn*vn_Vrth
            vl=0.5*(vnl*(VRT-dv0)-VRT-dv0)
            vl_vnl=0.5*(VRT-dv0)
            vl_dv0=0.5*(-vnl-1.0)
            vl_Vbci=vl_vnl*vnl_Vbci
            vl_Vrth=vl_vnl*vnl_Vrth
            vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
            xvar1=(1.0-vl/PCatT)
            xvar1_vl=-1.0/PCatT
            xvar1_PCatT=vl/(PCatT*PCatT)
            xvar1_Vbci=xvar1_vl*vl_Vbci
            xvar1_Vrth=xvar1_vl*vl_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=PCatT*(1.0-xvar3)/(1.0-MC)
            qlo_PCatT=(1.0-xvar3)/(1.0-MC)
            qlo_xvar3=-PCatT/(1.0-MC)
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qlo_Vbci=qlo_xvar3*xvar3_Vbci
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            sel=0.5*(vnl+1.0)
            sel_vnl=0.5
            sel_Vbci=sel_vnl*vnl_Vbci
            sel_Vrth=sel_vnl*vnl_Vrth
            xvar1=(1.0+VRT/PCatT)
            xvar1_PCatT=-VRT/(PCatT*PCatT)
            xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
            xvar2=(-MC)
            crt=xvar1**xvar2
            crt_xvar1=crt*xvar2/xvar1
            crt_Vrth=crt_xvar1*xvar1_Vrth
            xvar1=(1.0+dv0/PCatT)
            xvar1_dv0=1.0/PCatT
            xvar1_PCatT=-dv0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_dv0*dv0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(-MC)
            cmx=xvar1**xvar2
            cmx_xvar1=cmx*xvar2/xvar1
            cmx_Vrth=cmx_xvar1*xvar1_Vrth
            cl=(1.0-sel)*crt+sel*cmx
            cl_sel=cmx-crt
            cl_crt=1.0-sel
            cl_cmx=sel
            cl_Vbci=cl_sel*sel_Vbci
            cl_Vrth=cl_sel*sel_Vrth
            cl_Vrth=cl_Vrth+cl_crt*crt_Vrth
            cl_Vrth=cl_Vrth+cl_cmx*cmx_Vrth
            ql=(Vbci-vl+vl0)*cl
            ql_Vbci=cl
            ql_vl=-cl
            ql_vl0=cl
            ql_cl=vl0-vl+Vbci
            ql_Vbci=ql_Vbci+ql_vl*vl_Vbci
            ql_Vrth=ql_vl*vl_Vrth
            ql_Vrth=ql_Vrth+ql_vl0*vl0_Vrth
            ql_Vbci=ql_Vbci+ql_cl*cl_Vbci
            ql_Vrth=ql_Vrth+ql_cl*cl_Vrth
            qdbc=ql+qlo-qlo0
            qdbc_ql=1.0
            qdbc_qlo=1.0
            qdbc_qlo0=-1.0
            qdbc_Vbci=qdbc_ql*ql_Vbci
            qdbc_Vrth=qdbc_ql*ql_Vrth
            qdbc_Vrth=qdbc_Vrth+qdbc_qlo*qlo_Vrth
            qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci
            qdbc_Vrth=qdbc_Vrth+qdbc_qlo0*qlo0_Vrth
         else
            mv0=sqrt(dv0*dv0+4.0*AJC*AJC)
            mv0_dv0=dv0/sqrt((dv0*dv0)+4.0*(AJC*AJC))
            mv0_Vrth=mv0_dv0*dv0_Vrth
            vl0=-0.5*(dv0+mv0)
            vl0_dv0=-0.5
            vl0_mv0=-0.5
            vl0_Vrth=vl0_dv0*dv0_Vrth
            vl0_Vrth=vl0_Vrth+vl0_mv0*mv0_Vrth
            xvar1=(1.0-vl0/PCatT)
            xvar1_vl0=-1.0/PCatT
            xvar1_PCatT=vl0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_vl0*vl0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            q0=-PCatT*xvar3/(1.0-MC)
            q0_PCatT=-xvar3/(1.0-MC)
            q0_xvar3=-PCatT/(1.0-MC)
            q0_Vrth=q0_PCatT*PCatT_Vrth
            q0_Vrth=q0_Vrth+q0_xvar3*xvar3_Vrth
            dv=Vbci+dv0
            dv_Vbci=1.0
            dv_dv0=1.0
            dv_Vrth=dv_dv0*dv0_Vrth
            mv=sqrt(dv*dv+4.0*AJC*AJC)
            mv_dv=dv/sqrt((dv*dv)+4.0*(AJC*AJC))
            mv_Vbci=mv_dv*dv_Vbci
            mv_Vrth=mv_dv*dv_Vrth
            vl=0.5*(dv-mv)-dv0
            vl_dv=0.5
            vl_mv=-0.5
            vl_dv0=-1.0
            vl_Vbci=vl_dv*dv_Vbci
            vl_Vrth=vl_dv*dv_Vrth
            vl_Vbci=vl_Vbci+vl_mv*mv_Vbci
            vl_Vrth=vl_Vrth+vl_mv*mv_Vrth
            vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
            xvar1=(1.0-vl/PCatT)
            xvar1_vl=-1.0/PCatT
            xvar1_PCatT=vl/(PCatT*PCatT)
            xvar1_Vbci=xvar1_vl*vl_Vbci
            xvar1_Vrth=xvar1_vl*vl_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbci=xvar3_xvar1*xvar1_Vbci
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=-PCatT*xvar3/(1.0-MC)
            qlo_PCatT=-xvar3/(1.0-MC)
            qlo_xvar3=-PCatT/(1.0-MC)
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qlo_Vbci=qlo_xvar3*xvar3_Vbci
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            xvar1=(1.0-FC)
            xvar2=(-MC)
            xvar3=xvar1**xvar2
            qdbc=qlo+xvar3*(Vbci-vl+vl0)-q0
            qdbc_qlo=1.0
            qdbc_Vbci=xvar3
            qdbc_vl=-xvar3
            qdbc_vl0=xvar3
            qdbc_q0=-1.0
            qdbc_Vrth=qdbc_qlo*qlo_Vrth
            qdbc_Vbci=qdbc_Vbci+qdbc_qlo*qlo_Vbci
            qdbc_Vbci=qdbc_Vbci+qdbc_vl*vl_Vbci
            qdbc_Vrth=qdbc_Vrth+qdbc_vl*vl_Vrth
            qdbc_Vrth=qdbc_Vrth+qdbc_vl0*vl0_Vrth
            qdbc_Vrth=qdbc_Vrth+qdbc_q0*q0_Vrth
         endif
      endif
      dv0=-PCatT*FC
      dv0_PCatT=-FC
      dv0_Vrth=dv0_PCatT*PCatT_Vrth
      if(AJC.LE.0.0)then
         dvh=Vbep+dv0
         dvh_Vbep=1.0
         dvh_dv0=1.0
         dvh_Vrth=dvh_dv0*dv0_Vrth
         if(dvh.GT.0.0)then
            xvar1=(1.0-FC)
            xvar2=(-1.0-MC)
            pwq=xvar1**xvar2
            qlo=PCatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC)
            qlo_PCatT=(1.0-((1.0-FC)*(1.0-FC))*pwq)/(1.0-MC)
            qlo_Vbep=0.0
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qhi=dvh*(1.0-FC+0.5*MC*dvh/PCatT)*pwq
            qhi_dvh=(0.5*dvh*MC/PCatT-FC+1.0)*pwq+0.5*dvh*MC*pwq/PCatT
            qhi_PCatT=-0.5*(dvh*dvh)*MC*pwq/(PCatT*PCatT)
            qhi_Vbep=qhi_dvh*dvh_Vbep
            qhi_Vrth=qhi_dvh*dvh_Vrth
            qhi_Vrth=qhi_Vrth+qhi_PCatT*PCatT_Vrth
         else
            if((VRT.GT.0.0).AND.(Vbep.LT.-VRT))then
               xvar1=(1.0+VRT/PCatT)
               xvar1_PCatT=-VRT/(PCatT*PCatT)
               xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
               xvar2=(1.0-MC)
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
               qlo=PCatT*(1.0-xvar3*(1.0-((1.0-MC)*(Vbep+VRT))/(PCatT+VR
     +T)))/(1.0-MC)
               qlo_PCatT=(1.0-(1.0-(1.0-MC)*(VRT+Vbep)/(VRT+PCatT))*xvar
     +3)/(1.0-MC)-PCatT*(VRT+Vbep)*xvar3/((VRT+PCatT)*(VRT+PCatT))
               qlo_xvar3=PCatT*((1.0-MC)*(VRT+Vbep)/(VRT+PCatT)-1.0)/(1.
     +0-MC)
               qlo_Vbep=PCatT*xvar3/(VRT+PCatT)
               qlo_Vrth=qlo_PCatT*PCatT_Vrth
               qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            else
               xvar1=(1.0-Vbep/PCatT)
               xvar1_Vbep=-1.0/PCatT
               xvar1_PCatT=Vbep/(PCatT*PCatT)
               xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
               xvar2=(1.0-MC)
               xvar3=xvar1**xvar2
               xvar3_xvar1=xvar3*xvar2/xvar1
               xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
               xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
               qlo=PCatT*(1.0-xvar3)/(1.0-MC)
               qlo_PCatT=(1.0-xvar3)/(1.0-MC)
               qlo_xvar3=-PCatT/(1.0-MC)
               qlo_Vrth=qlo_PCatT*PCatT_Vrth
               qlo_Vbep=qlo_xvar3*xvar3_Vbep
               qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            endif
            qhi=0.0
            qhi_Vbep=0.0
            qhi_Vrth=0.0
         endif
         qdbep=qlo+qhi
         qdbep_qlo=1.0
         qdbep_qhi=1.0
         qdbep_Vrth=qdbep_qlo*qlo_Vrth
         qdbep_Vbep=qdbep_qlo*qlo_Vbep
         qdbep_Vbep=qdbep_Vbep+qdbep_qhi*qhi_Vbep
         qdbep_Vrth=qdbep_Vrth+qdbep_qhi*qhi_Vrth
      else
         if((VRT.GT.0.0).AND.(ART.GT.0.0))then
            vn0=(VRT+dv0)/(VRT-dv0)
            vn0_dv0=(VRT+dv0)/((VRT-dv0)*(VRT-dv0))+1.0/(VRT-dv0)
            vn0_Vrth=vn0_dv0*dv0_Vrth
            vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn
     +0+1.0)*(vn0+1.0)+4.0*ART*ART))
            vnl0_vn0=2.0/(sqrt(((vn0+1.0)*(vn0+1.0))+4.0*(ART*ART))+sqrt
     +(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC)))-2.0*vn0*((vn0+1.0)/sqrt(((v
     +n0+1.0)*(vn0+1.0))+4.0*(ART*ART))+(vn0-1.0)/sqrt(((vn0-1.0)*(vn0-1
     +.0))+4.0*(AJC*AJC)))/((sqrt(((vn0+1.0)*(vn0+1.0))+4.0*(ART*ART))+s
     +qrt(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn0+1.0)*(vn0+1.
     +0))+4.0*(ART*ART))+sqrt(((vn0-1.0)*(vn0-1.0))+4.0*(AJC*AJC))))
            vnl0_Vrth=vnl0_vn0*vn0_Vrth
            vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0)
            vl0_vnl0=0.5*(VRT-dv0)
            vl0_dv0=0.5*(-vnl0-1.0)
            vl0_Vrth=vl0_vnl0*vnl0_Vrth
            vl0_Vrth=vl0_Vrth+vl0_dv0*dv0_Vrth
            xvar1=(1.0-vl0/PCatT)
            xvar1_vl0=-1.0/PCatT
            xvar1_PCatT=vl0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_vl0*vl0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo0=PCatT*(1.0-xvar3)/(1.0-MC)
            qlo0_PCatT=(1.0-xvar3)/(1.0-MC)
            qlo0_xvar3=-PCatT/(1.0-MC)
            qlo0_Vrth=qlo0_PCatT*PCatT_Vrth
            qlo0_Vrth=qlo0_Vrth+qlo0_xvar3*xvar3_Vrth
            vn=(2.0*Vbep+VRT+dv0)/(VRT-dv0)
            vn_Vbep=2.0/(VRT-dv0)
            vn_dv0=(VRT+2.0*Vbep+dv0)/((VRT-dv0)*(VRT-dv0))+1.0/(VRT-dv0
     +)
            vn_Vrth=vn_dv0*dv0_Vrth
            vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0
     +)*(vn+1.0)+4.0*ART*ART))
            vnl_vn=2.0/(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((v
     +n-1.0)*(vn-1.0))+4.0*(AJC*AJC)))-2.0*vn*((vn+1.0)/sqrt(((vn+1.0)*(
     +vn+1.0))+4.0*(ART*ART))+(vn-1.0)/sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC
     +*AJC)))/((sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+sqrt(((vn-1.0)*(
     +vn-1.0))+4.0*(AJC*AJC)))*(sqrt(((vn+1.0)*(vn+1.0))+4.0*(ART*ART))+
     +sqrt(((vn-1.0)*(vn-1.0))+4.0*(AJC*AJC))))
            vnl_Vbep=vnl_vn*vn_Vbep
            vnl_Vrth=vnl_vn*vn_Vrth
            vl=0.5*(vnl*(VRT-dv0)-VRT-dv0)
            vl_vnl=0.5*(VRT-dv0)
            vl_dv0=0.5*(-vnl-1.0)
            vl_Vbep=vl_vnl*vnl_Vbep
            vl_Vrth=vl_vnl*vnl_Vrth
            vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
            xvar1=(1.0-vl/PCatT)
            xvar1_vl=-1.0/PCatT
            xvar1_PCatT=vl/(PCatT*PCatT)
            xvar1_Vbep=xvar1_vl*vl_Vbep
            xvar1_Vrth=xvar1_vl*vl_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=PCatT*(1.0-xvar3)/(1.0-MC)
            qlo_PCatT=(1.0-xvar3)/(1.0-MC)
            qlo_xvar3=-PCatT/(1.0-MC)
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qlo_Vbep=qlo_xvar3*xvar3_Vbep
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            sel=0.5*(vnl+1.0)
            sel_vnl=0.5
            sel_Vbep=sel_vnl*vnl_Vbep
            sel_Vrth=sel_vnl*vnl_Vrth
            xvar1=(1.0+VRT/PCatT)
            xvar1_PCatT=-VRT/(PCatT*PCatT)
            xvar1_Vrth=xvar1_PCatT*PCatT_Vrth
            xvar2=(-MC)
            crt=xvar1**xvar2
            crt_xvar1=crt*xvar2/xvar1
            crt_Vrth=crt_xvar1*xvar1_Vrth
            xvar1=(1.0+dv0/PCatT)
            xvar1_dv0=1.0/PCatT
            xvar1_PCatT=-dv0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_dv0*dv0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(-MC)
            cmx=xvar1**xvar2
            cmx_xvar1=cmx*xvar2/xvar1
            cmx_Vrth=cmx_xvar1*xvar1_Vrth
            cl=(1.0-sel)*crt+sel*cmx
            cl_sel=cmx-crt
            cl_crt=1.0-sel
            cl_cmx=sel
            cl_Vbep=cl_sel*sel_Vbep
            cl_Vrth=cl_sel*sel_Vrth
            cl_Vrth=cl_Vrth+cl_crt*crt_Vrth
            cl_Vrth=cl_Vrth+cl_cmx*cmx_Vrth
            ql=(Vbep-vl+vl0)*cl
            ql_Vbep=cl
            ql_vl=-cl
            ql_vl0=cl
            ql_cl=vl0-vl+Vbep
            ql_Vbep=ql_Vbep+ql_vl*vl_Vbep
            ql_Vrth=ql_vl*vl_Vrth
            ql_Vrth=ql_Vrth+ql_vl0*vl0_Vrth
            ql_Vbep=ql_Vbep+ql_cl*cl_Vbep
            ql_Vrth=ql_Vrth+ql_cl*cl_Vrth
            qdbep=ql+qlo-qlo0
            qdbep_ql=1.0
            qdbep_qlo=1.0
            qdbep_qlo0=-1.0
            qdbep_Vbep=qdbep_ql*ql_Vbep
            qdbep_Vrth=qdbep_ql*ql_Vrth
            qdbep_Vrth=qdbep_Vrth+qdbep_qlo*qlo_Vrth
            qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep
            qdbep_Vrth=qdbep_Vrth+qdbep_qlo0*qlo0_Vrth
         else
            mv0=sqrt(dv0*dv0+4.0*AJC*AJC)
            mv0_dv0=dv0/sqrt((dv0*dv0)+4.0*(AJC*AJC))
            mv0_Vrth=mv0_dv0*dv0_Vrth
            vl0=-0.5*(dv0+mv0)
            vl0_dv0=-0.5
            vl0_mv0=-0.5
            vl0_Vrth=vl0_dv0*dv0_Vrth
            vl0_Vrth=vl0_Vrth+vl0_mv0*mv0_Vrth
            xvar1=(1.0-vl0/PCatT)
            xvar1_vl0=-1.0/PCatT
            xvar1_PCatT=vl0/(PCatT*PCatT)
            xvar1_Vrth=xvar1_vl0*vl0_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            q0=-PCatT*xvar3/(1.0-MC)
            q0_PCatT=-xvar3/(1.0-MC)
            q0_xvar3=-PCatT/(1.0-MC)
            q0_Vrth=q0_PCatT*PCatT_Vrth
            q0_Vrth=q0_Vrth+q0_xvar3*xvar3_Vrth
            dv=Vbep+dv0
            dv_Vbep=1.0
            dv_dv0=1.0
            dv_Vrth=dv_dv0*dv0_Vrth
            mv=sqrt(dv*dv+4.0*AJC*AJC)
            mv_dv=dv/sqrt((dv*dv)+4.0*(AJC*AJC))
            mv_Vbep=mv_dv*dv_Vbep
            mv_Vrth=mv_dv*dv_Vrth
            vl=0.5*(dv-mv)-dv0
            vl_dv=0.5
            vl_mv=-0.5
            vl_dv0=-1.0
            vl_Vbep=vl_dv*dv_Vbep
            vl_Vrth=vl_dv*dv_Vrth
            vl_Vbep=vl_Vbep+vl_mv*mv_Vbep
            vl_Vrth=vl_Vrth+vl_mv*mv_Vrth
            vl_Vrth=vl_Vrth+vl_dv0*dv0_Vrth
            xvar1=(1.0-vl/PCatT)
            xvar1_vl=-1.0/PCatT
            xvar1_PCatT=vl/(PCatT*PCatT)
            xvar1_Vbep=xvar1_vl*vl_Vbep
            xvar1_Vrth=xvar1_vl*vl_Vrth
            xvar1_Vrth=xvar1_Vrth+xvar1_PCatT*PCatT_Vrth
            xvar2=(1.0-MC)
            xvar3=xvar1**xvar2
            xvar3_xvar1=xvar3*xvar2/xvar1
            xvar3_Vbep=xvar3_xvar1*xvar1_Vbep
            xvar3_Vrth=xvar3_xvar1*xvar1_Vrth
            qlo=-PCatT*xvar3/(1.0-MC)
            qlo_PCatT=-xvar3/(1.0-MC)
            qlo_xvar3=-PCatT/(1.0-MC)
            qlo_Vrth=qlo_PCatT*PCatT_Vrth
            qlo_Vbep=qlo_xvar3*xvar3_Vbep
            qlo_Vrth=qlo_Vrth+qlo_xvar3*xvar3_Vrth
            xvar1=(1.0-FC)
            xvar2=(-MC)
            xvar3=xvar1**xvar2
            qdbep=qlo+xvar3*(Vbep-vl+vl0)-q0
            qdbep_qlo=1.0
            qdbep_Vbep=xvar3
            qdbep_vl=-xvar3
            qdbep_vl0=xvar3
            qdbep_q0=-1.0
            qdbep_Vrth=qdbep_qlo*qlo_Vrth
            qdbep_Vbep=qdbep_Vbep+qdbep_qlo*qlo_Vbep
            qdbep_Vbep=qdbep_Vbep+qdbep_vl*vl_Vbep
            qdbep_Vrth=qdbep_Vrth+qdbep_vl*vl_Vrth
            qdbep_Vrth=qdbep_Vrth+qdbep_vl0*vl0_Vrth
            qdbep_Vrth=qdbep_Vrth+qdbep_q0*q0_Vrth
         endif
      endif
      argi=Vbei/(NFatT*Vtv)
      argi_Vbei=1.0/(NFatT*Vtv)
      argi_NFatT=-Vbei/((NFatT*NFatT)*Vtv)
      argi_Vtv=-Vbei/(NFatT*(Vtv*Vtv))
      argi_Vrth=argi_NFatT*NFatT_Vrth
      argi_Vrth=argi_Vrth+argi_Vtv*Vtv_Vrth
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbei=expi_argi*argi_Vbei
      expi_Vrth=expi_argi*argi_Vrth
      Ifi=ISatT*(expi-1.0)
      Ifi_ISatT=expi-1.0
      Ifi_expi=ISatT
      Ifi_Vrth=Ifi_ISatT*ISatT_Vrth
      Ifi_Vbei=Ifi_expi*expi_Vbei
      Ifi_Vrth=Ifi_Vrth+Ifi_expi*expi_Vrth
      argi=Vbci/(NRatT*Vtv)
      argi_Vbci=1.0/(NRatT*Vtv)
      argi_NRatT=-Vbci/((NRatT*NRatT)*Vtv)
      argi_Vtv=-Vbci/(NRatT*(Vtv*Vtv))
      argi_Vrth=argi_NRatT*NRatT_Vrth
      argi_Vrth=argi_Vrth+argi_Vtv*Vtv_Vrth
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      expi_Vrth=expi_argi*argi_Vrth
      Iri=ISatT*ISRRatT*(expi-1.0)
      Iri_ISatT=(expi-1.0)*ISRRatT
      Iri_ISRRatT=(expi-1.0)*ISatT
      Iri_expi=ISatT*ISRRatT
      Iri_Vrth=Iri_ISatT*ISatT_Vrth
      Iri_Vrth=Iri_Vrth+Iri_ISRRatT*ISRRatT_Vrth
      Iri_Vbci=Iri_expi*expi_Vbci
      Iri_Vrth=Iri_Vrth+Iri_expi*expi_Vrth
      q1z=1.0+qdbe*IVER+qdbc*IVEF
      q1z_qdbe=IVER
      q1z_qdbc=IVEF
      q1z_Vrth=q1z_qdbe*qdbe_Vrth
      q1z_Vbei=q1z_qdbe*qdbe_Vbei
      q1z_Vrth=q1z_Vrth+q1z_qdbc*qdbc_Vrth
      q1z_Vbci=q1z_qdbc*qdbc_Vbci
      q1=0.5*(sqrt((q1z-1.0e-4)*(q1z-1.0e-4)+1.0e-8)+q1z-1.0e-4)+1.0e-4
      q1_q1z=0.5*((q1z-1.0e-4)/sqrt(((q1z-1.0e-4)*(q1z-1.0e-4))+1.0e-8)+
     +1.0)
      q1_Vrth=q1_q1z*q1z_Vrth
      q1_Vbei=q1_q1z*q1z_Vbei
      q1_Vbci=q1_q1z*q1z_Vbci
      q2=Ifi*IIKF+Iri*IIKR
      q2_Ifi=IIKF
      q2_IIKF=Ifi
      q2_Iri=IIKR
      q2_Vrth=q2_Ifi*Ifi_Vrth
      q2_Vbei=q2_Ifi*Ifi_Vbei
      q2_Vrth=q2_Vrth+q2_IIKF*IIKF_Vrth
      q2_Vrth=q2_Vrth+q2_Iri*Iri_Vrth
      q2_Vbci=q2_Iri*Iri_Vbci
      if(QBM.LT.0.5)then
         xvar2=1.0/NKF
         xvar3=q1**xvar2
         xvar3_q1=xvar3*xvar2/q1
         xvar3_Vrth=xvar3_q1*q1_Vrth
         xvar3_Vbei=xvar3_q1*q1_Vbei
         xvar3_Vbci=xvar3_q1*q1_Vbci
         xvar1=(xvar3+4.0*q2)
         xvar1_xvar3=1.0
         xvar1_q2=4.0
         xvar1_Vrth=xvar1_xvar3*xvar3_Vrth
         xvar1_Vbei=xvar1_xvar3*xvar3_Vbei
         xvar1_Vbci=xvar1_xvar3*xvar3_Vbci
         xvar1_Vrth=xvar1_Vrth+xvar1_q2*q2_Vrth
         xvar1_Vbei=xvar1_Vbei+xvar1_q2*q2_Vbei
         xvar1_Vbci=xvar1_Vbci+xvar1_q2*q2_Vbci
         xvar4=xvar1**NKF
         xvar4_xvar1=xvar4*NKF/xvar1
         xvar4_Vrth=xvar4_xvar1*xvar1_Vrth
         xvar4_Vbei=xvar4_xvar1*xvar1_Vbei
         xvar4_Vbci=xvar4_xvar1*xvar1_Vbci
         qb=0.5*(q1+xvar4)
         qb_q1=0.5
         qb_xvar4=0.5
         qb_Vrth=qb_q1*q1_Vrth
         qb_Vbei=qb_q1*q1_Vbei
         qb_Vbci=qb_q1*q1_Vbci
         qb_Vrth=qb_Vrth+qb_xvar4*xvar4_Vrth
         qb_Vbei=qb_Vbei+qb_xvar4*xvar4_Vbei
         qb_Vbci=qb_Vbci+qb_xvar4*xvar4_Vbci
      else
         xvar1=(1.0+4.0*q2)
         xvar1_q2=4.0
         xvar1_Vrth=xvar1_q2*q2_Vrth
         xvar1_Vbei=xvar1_q2*q2_Vbei
         xvar1_Vbci=xvar1_q2*q2_Vbci
         xvar2=xvar1**NKF
         xvar2_xvar1=xvar2*NKF/xvar1
         xvar2_Vrth=xvar2_xvar1*xvar1_Vrth
         xvar2_Vbei=xvar2_xvar1*xvar1_Vbei
         xvar2_Vbci=xvar2_xvar1*xvar1_Vbci
         qb=0.5*q1*(1.0+xvar2)
         qb_q1=0.5*(xvar2+1.0)
         qb_xvar2=0.5*q1
         qb_Vrth=qb_q1*q1_Vrth
         qb_Vbei=qb_q1*q1_Vbei
         qb_Vbci=qb_q1*q1_Vbci
         qb_Vrth=qb_Vrth+qb_xvar2*xvar2_Vrth
         qb_Vbei=qb_Vbei+qb_xvar2*xvar2_Vbei
         qb_Vbci=qb_Vbci+qb_xvar2*xvar2_Vbci
      endif
      Itzr=Iri/qb
      Itzr_Iri=1.0/qb
      Itzr_qb=-Iri/(qb*qb)
      Itzr_Vrth=Itzr_Iri*Iri_Vrth
      Itzr_Vbci=Itzr_Iri*Iri_Vbci
      Itzr_Vrth=Itzr_Vrth+Itzr_qb*qb_Vrth
      Itzr_Vbei=Itzr_qb*qb_Vbei
      Itzr_Vbci=Itzr_Vbci+Itzr_qb*qb_Vbci
      Itzf=Ifi/qb
      Itzf_Ifi=1.0/qb
      Itzf_qb=-Ifi/(qb*qb)
      Itzf_Vrth=Itzf_Ifi*Ifi_Vrth
      Itzf_Vbei=Itzf_Ifi*Ifi_Vbei
      Itzf_Vrth=Itzf_Vrth+Itzf_qb*qb_Vrth
      Itzf_Vbei=Itzf_Vbei+Itzf_qb*qb_Vbei
      Itzf_Vbci=Itzf_qb*qb_Vbci
      Ixzf=-Itzf
      Ixzf_Itzf=-1.0
      Ixzf_Vrth=Ixzf_Itzf*Itzf_Vrth
      Ixzf_Vbei=Ixzf_Itzf*Itzf_Vbei
      Ixzf_Vbci=Ixzf_Itzf*Itzf_Vbci
      Itxf=Vrxf
      Itxf_Vrxf=1.0
      Ixxf=Vrxf
      Ixxf_Vrxf=1.0
      if(ISP.GT.0.0)then
         argi=Vbep/(NFP*Vtv)
         argi_Vbep=1.0/(NFP*Vtv)
         argi_Vtv=-Vbep/(NFP*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbep=expi_argi*argi_Vbep
         expi_Vrth=expi_argi*argi_Vrth
         argx=Vbci/(NFP*Vtv)
         argx_Vbci=1.0/(NFP*Vtv)
         argx_Vtv=-Vbci/(NFP*(Vtv*Vtv))
         argx_Vrth=argx_Vtv*Vtv_Vrth
         if(argx.GT.100.0)then
            expx_argx=exp(100.0)
            expx=expx_argx*(1.0+(argx-100.0))
         elseif(argx.LT.-100.0)then
            expx_argx=exp(-100.0)
            expx=expx_argx*(1.0+(argx+100.0))
         else
            expx=exp(argx)
            expx_argx=expx
         endif
         expx_Vbci=expx_argx*argx_Vbci
         expx_Vrth=expx_argx*argx_Vrth
         Ifp=ISPatT*(WSP*expi+(1.0-WSP)*expx-1.0)
         Ifp_ISPatT=expi*WSP+expx*(1.0-WSP)-1.0
         Ifp_expi=ISPatT*WSP
         Ifp_expx=ISPatT*(1.0-WSP)
         Ifp_Vrth=Ifp_ISPatT*ISPatT_Vrth
         Ifp_Vbep=Ifp_expi*expi_Vbep
         Ifp_Vrth=Ifp_Vrth+Ifp_expi*expi_Vrth
         Ifp_Vbci=Ifp_expx*expx_Vbci
         Ifp_Vrth=Ifp_Vrth+Ifp_expx*expx_Vrth
         q2p=Ifp*IIKP
         q2p_Ifp=IIKP
         q2p_Vrth=q2p_Ifp*Ifp_Vrth
         q2p_Vbep=q2p_Ifp*Ifp_Vbep
         q2p_Vbci=q2p_Ifp*Ifp_Vbci
         qbp=0.5*(1.0+sqrt(1.0+4.0*q2p))
         qbp_q2p=1.0/sqrt(4.0*q2p+1.0)
         qbp_Vrth=qbp_q2p*q2p_Vrth
         qbp_Vbep=qbp_q2p*q2p_Vbep
         qbp_Vbci=qbp_q2p*q2p_Vbci
      else
         Ifp=0.0
         Ifp_Vrth=0.0
         Ifp_Vbep=0.0
         Ifp_Vbci=0.0
         qbp=1.0
         qbp_Vrth=0.0
         qbp_Vbep=0.0
         qbp_Vbci=0.0
      endif
      if(WBE.EQ.1.0)then
         argi=Vbei/(NEI*Vtv)
         argi_Vbei=1.0/(NEI*Vtv)
         argi_Vtv=-Vbei/(NEI*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbei=expi_argi*argi_Vbei
         expi_Vrth=expi_argi*argi_Vrth
         argn=Vbei/(NEN*Vtv)
         argn_Vbei=1.0/(NEN*Vtv)
         argn_Vtv=-Vbei/(NEN*(Vtv*Vtv))
         argn_Vrth=argn_Vtv*Vtv_Vrth
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbei=expn_argn*argn_Vbei
         expn_Vrth=expn_argn*argn_Vrth
         if(VBBE.GT.0.0)then
            argx=(-VBBEatT-Vbei)/(NBBEatT*Vtv)
            argx_VBBEatT=-1.0/(NBBEatT*Vtv)
            argx_Vbei=-1.0/(NBBEatT*Vtv)
            argx_NBBEatT=-(-Vbei-VBBEatT)/((NBBEatT*NBBEatT)*Vtv)
            argx_Vtv=-(-Vbei-VBBEatT)/(NBBEatT*(Vtv*Vtv))
            argx_Vrth=argx_VBBEatT*VBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_NBBEatT*NBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_Vtv*Vtv_Vrth
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vrth=expx_argx*argx_Vrth
            expx_Vbei=expx_argx*argx_Vbei
            Ibe=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEatT
     +)
            Ibe_IBEIatT=expi-1.0
            Ibe_expi=IBEIatT
            Ibe_IBENatT=expn-1.0
            Ibe_expn=IBENatT
            Ibe_expx=-IBBE
            Ibe_EBBEatT=IBBE
            Ibe_Vrth=Ibe_IBEIatT*IBEIatT_Vrth
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expi*expi_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_IBENatT*IBENatT_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expn*expn_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_expx*expx_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expx*expx_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_EBBEatT*EBBEatT_Vrth
         else
            Ibe=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)
            Ibe_IBEIatT=expi-1.0
            Ibe_expi=IBEIatT
            Ibe_IBENatT=expn-1.0
            Ibe_expn=IBENatT
            Ibe_Vrth=Ibe_IBEIatT*IBEIatT_Vrth
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expi*expi_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_IBENatT*IBENatT_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expn*expn_Vrth
         endif
         Ibex=0.0
         Ibex_Vrth=0.0
         Ibex_Vbex=0.0
      elseif(WBE.EQ.0.0)then
         Ibe=0.0
         Ibe_Vrth=0.0
         Ibe_Vbei=0.0
         argi=Vbex/(NEI*Vtv)
         argi_Vbex=1.0/(NEI*Vtv)
         argi_Vtv=-Vbex/(NEI*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbex=expi_argi*argi_Vbex
         expi_Vrth=expi_argi*argi_Vrth
         argn=Vbex/(NEN*Vtv)
         argn_Vbex=1.0/(NEN*Vtv)
         argn_Vtv=-Vbex/(NEN*(Vtv*Vtv))
         argn_Vrth=argn_Vtv*Vtv_Vrth
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbex=expn_argn*argn_Vbex
         expn_Vrth=expn_argn*argn_Vrth
         if(VBBE.GT.0.0)then
            argx=(-VBBEatT-Vbex)/(NBBEatT*Vtv)
            argx_VBBEatT=-1.0/(NBBEatT*Vtv)
            argx_Vbex=-1.0/(NBBEatT*Vtv)
            argx_NBBEatT=-(-Vbex-VBBEatT)/((NBBEatT*NBBEatT)*Vtv)
            argx_Vtv=-(-Vbex-VBBEatT)/(NBBEatT*(Vtv*Vtv))
            argx_Vrth=argx_VBBEatT*VBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_NBBEatT*NBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_Vtv*Vtv_Vrth
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vrth=expx_argx*argx_Vrth
            expx_Vbex=expx_argx*argx_Vbex
            Ibex=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEat
     +T)
            Ibex_IBEIatT=expi-1.0
            Ibex_expi=IBEIatT
            Ibex_IBENatT=expn-1.0
            Ibex_expn=IBENatT
            Ibex_expx=-IBBE
            Ibex_EBBEatT=IBBE
            Ibex_Vrth=Ibex_IBEIatT*IBEIatT_Vrth
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expi*expi_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_IBENatT*IBENatT_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expn*expn_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_expx*expx_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expx*expx_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_EBBEatT*EBBEatT_Vrth
         else
            Ibex=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)
            Ibex_IBEIatT=expi-1.0
            Ibex_expi=IBEIatT
            Ibex_IBENatT=expn-1.0
            Ibex_expn=IBENatT
            Ibex_Vrth=Ibex_IBEIatT*IBEIatT_Vrth
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expi*expi_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_IBENatT*IBENatT_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expn*expn_Vrth
         endif
      else
         argi=Vbei/(NEI*Vtv)
         argi_Vbei=1.0/(NEI*Vtv)
         argi_Vtv=-Vbei/(NEI*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbei=expi_argi*argi_Vbei
         expi_Vrth=expi_argi*argi_Vrth
         argn=Vbei/(NEN*Vtv)
         argn_Vbei=1.0/(NEN*Vtv)
         argn_Vtv=-Vbei/(NEN*(Vtv*Vtv))
         argn_Vrth=argn_Vtv*Vtv_Vrth
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbei=expn_argn*argn_Vbei
         expn_Vrth=expn_argn*argn_Vrth
         if(VBBE.GT.0.0)then
            argx=(-VBBEatT-Vbei)/(NBBEatT*Vtv)
            argx_VBBEatT=-1.0/(NBBEatT*Vtv)
            argx_Vbei=-1.0/(NBBEatT*Vtv)
            argx_NBBEatT=-(-Vbei-VBBEatT)/((NBBEatT*NBBEatT)*Vtv)
            argx_Vtv=-(-Vbei-VBBEatT)/(NBBEatT*(Vtv*Vtv))
            argx_Vrth=argx_VBBEatT*VBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_NBBEatT*NBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_Vtv*Vtv_Vrth
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vrth=expx_argx*argx_Vrth
            expx_Vbei=expx_argx*argx_Vbei
            Ibe=WBE*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EB
     +BEatT))
            Ibe_IBEIatT=(expi-1.0)*WBE
            Ibe_expi=IBEIatT*WBE
            Ibe_IBENatT=(expn-1.0)*WBE
            Ibe_expn=IBENatT*WBE
            Ibe_expx=-IBBE*WBE
            Ibe_EBBEatT=IBBE*WBE
            Ibe_Vrth=Ibe_IBEIatT*IBEIatT_Vrth
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expi*expi_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_IBENatT*IBENatT_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expn*expn_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_expx*expx_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expx*expx_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_EBBEatT*EBBEatT_Vrth
         else
            Ibe=WBE*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0))
            Ibe_IBEIatT=(expi-1.0)*WBE
            Ibe_expi=IBEIatT*WBE
            Ibe_IBENatT=(expn-1.0)*WBE
            Ibe_expn=IBENatT*WBE
            Ibe_Vrth=Ibe_IBEIatT*IBEIatT_Vrth
            Ibe_Vbei=Ibe_expi*expi_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expi*expi_Vrth
            Ibe_Vrth=Ibe_Vrth+Ibe_IBENatT*IBENatT_Vrth
            Ibe_Vbei=Ibe_Vbei+Ibe_expn*expn_Vbei
            Ibe_Vrth=Ibe_Vrth+Ibe_expn*expn_Vrth
         endif
         argi=Vbex/(NEI*Vtv)
         argi_Vbex=1.0/(NEI*Vtv)
         argi_Vtv=-Vbex/(NEI*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbex=expi_argi*argi_Vbex
         expi_Vrth=expi_argi*argi_Vrth
         argn=Vbex/(NEN*Vtv)
         argn_Vbex=1.0/(NEN*Vtv)
         argn_Vtv=-Vbex/(NEN*(Vtv*Vtv))
         argn_Vrth=argn_Vtv*Vtv_Vrth
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbex=expn_argn*argn_Vbex
         expn_Vrth=expn_argn*argn_Vrth
         if(VBBE.GT.0.0)then
            argx=(-VBBEatT-Vbex)/(NBBEatT*Vtv)
            argx_VBBEatT=-1.0/(NBBEatT*Vtv)
            argx_Vbex=-1.0/(NBBEatT*Vtv)
            argx_NBBEatT=-(-Vbex-VBBEatT)/((NBBEatT*NBBEatT)*Vtv)
            argx_Vtv=-(-Vbex-VBBEatT)/(NBBEatT*(Vtv*Vtv))
            argx_Vrth=argx_VBBEatT*VBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_NBBEatT*NBBEatT_Vrth
            argx_Vrth=argx_Vrth+argx_Vtv*Vtv_Vrth
            if(argx.GT.100.0)then
               expx_argx=exp(100.0)
               expx=expx_argx*(1.0+(argx-100.0))
            elseif(argx.LT.-100.0)then
               expx_argx=exp(-100.0)
               expx=expx_argx*(1.0+(argx+100.0))
            else
               expx=exp(argx)
               expx_argx=expx
            endif
            expx_Vrth=expx_argx*argx_Vrth
            expx_Vbex=expx_argx*argx_Vbex
            Ibex=(1.0-WBE)*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(
     +expx-EBBEatT))
            Ibex_IBEIatT=(expi-1.0)*(1.0-WBE)
            Ibex_expi=IBEIatT*(1.0-WBE)
            Ibex_IBENatT=(expn-1.0)*(1.0-WBE)
            Ibex_expn=IBENatT*(1.0-WBE)
            Ibex_expx=-IBBE*(1.0-WBE)
            Ibex_EBBEatT=IBBE*(1.0-WBE)
            Ibex_Vrth=Ibex_IBEIatT*IBEIatT_Vrth
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expi*expi_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_IBENatT*IBENatT_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expn*expn_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_expx*expx_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expx*expx_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_EBBEatT*EBBEatT_Vrth
         else
            Ibex=(1.0-WBE)*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0))
            Ibex_IBEIatT=(expi-1.0)*(1.0-WBE)
            Ibex_expi=IBEIatT*(1.0-WBE)
            Ibex_IBENatT=(expn-1.0)*(1.0-WBE)
            Ibex_expn=IBENatT*(1.0-WBE)
            Ibex_Vrth=Ibex_IBEIatT*IBEIatT_Vrth
            Ibex_Vbex=Ibex_expi*expi_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expi*expi_Vrth
            Ibex_Vrth=Ibex_Vrth+Ibex_IBENatT*IBENatT_Vrth
            Ibex_Vbex=Ibex_Vbex+Ibex_expn*expn_Vbex
            Ibex_Vrth=Ibex_Vrth+Ibex_expn*expn_Vrth
         endif
      endif
      argi=Vbci/(NCI*Vtv)
      argi_Vbci=1.0/(NCI*Vtv)
      argi_Vtv=-Vbci/(NCI*(Vtv*Vtv))
      argi_Vrth=argi_Vtv*Vtv_Vrth
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      expi_Vrth=expi_argi*argi_Vrth
      argn=Vbci/(NCN*Vtv)
      argn_Vbci=1.0/(NCN*Vtv)
      argn_Vtv=-Vbci/(NCN*(Vtv*Vtv))
      argn_Vrth=argn_Vtv*Vtv_Vrth
      if(argn.GT.100.0)then
         expn_argn=exp(100.0)
         expn=expn_argn*(1.0+(argn-100.0))
      elseif(argn.LT.-100.0)then
         expn_argn=exp(-100.0)
         expn=expn_argn*(1.0+(argn+100.0))
      else
         expn=exp(argn)
         expn_argn=expn
      endif
      expn_Vbci=expn_argn*argn_Vbci
      expn_Vrth=expn_argn*argn_Vrth
      Ibcj=IBCIatT*(expi-1.0)+IBCNatT*(expn-1.0)
      Ibcj_IBCIatT=expi-1.0
      Ibcj_expi=IBCIatT
      Ibcj_IBCNatT=expn-1.0
      Ibcj_expn=IBCNatT
      Ibcj_Vrth=Ibcj_IBCIatT*IBCIatT_Vrth
      Ibcj_Vbci=Ibcj_expi*expi_Vbci
      Ibcj_Vrth=Ibcj_Vrth+Ibcj_expi*expi_Vrth
      Ibcj_Vrth=Ibcj_Vrth+Ibcj_IBCNatT*IBCNatT_Vrth
      Ibcj_Vbci=Ibcj_Vbci+Ibcj_expn*expn_Vbci
      Ibcj_Vrth=Ibcj_Vrth+Ibcj_expn*expn_Vrth
      if((IBEIP.GT.0.0).OR.(IBENP.GT.0.0))then
         argi=Vbep/(NCI*Vtv)
         argi_Vbep=1.0/(NCI*Vtv)
         argi_Vtv=-Vbep/(NCI*(Vtv*Vtv))
         argi_Vrth=argi_Vtv*Vtv_Vrth
         if(argi.GT.100.0)then
            expi_argi=exp(100.0)
            expi=expi_argi*(1.0+(argi-100.0))
         elseif(argi.LT.-100.0)then
            expi_argi=exp(-100.0)
            expi=expi_argi*(1.0+(argi+100.0))
         else
            expi=exp(argi)
            expi_argi=expi
         endif
         expi_Vbep=expi_argi*argi_Vbep
         expi_Vrth=expi_argi*argi_Vrth
         argn=Vbep/(NCN*Vtv)
         argn_Vbep=1.0/(NCN*Vtv)
         argn_Vtv=-Vbep/(NCN*(Vtv*Vtv))
         argn_Vrth=argn_Vtv*Vtv_Vrth
         if(argn.GT.100.0)then
            expn_argn=exp(100.0)
            expn=expn_argn*(1.0+(argn-100.0))
         elseif(argn.LT.-100.0)then
            expn_argn=exp(-100.0)
            expn=expn_argn*(1.0+(argn+100.0))
         else
            expn=exp(argn)
            expn_argn=expn
         endif
         expn_Vbep=expn_argn*argn_Vbep
         expn_Vrth=expn_argn*argn_Vrth
         Ibep=IBEIPatT*(expi-1.0)+IBENPatT*(expn-1.0)
         Ibep_IBEIPatT=expi-1.0
         Ibep_expi=IBEIPatT
         Ibep_IBENPatT=expn-1.0
         Ibep_expn=IBENPatT
         Ibep_Vrth=Ibep_IBEIPatT*IBEIPatT_Vrth
         Ibep_Vbep=Ibep_expi*expi_Vbep
         Ibep_Vrth=Ibep_Vrth+Ibep_expi*expi_Vrth
         Ibep_Vrth=Ibep_Vrth+Ibep_IBENPatT*IBENPatT_Vrth
         Ibep_Vbep=Ibep_Vbep+Ibep_expn*expn_Vbep
         Ibep_Vrth=Ibep_Vrth+Ibep_expn*expn_Vrth
      else
         Ibep=0.0
         Ibep_Vrth=0.0
         Ibep_Vbep=0.0
      endif
      if(AVC1.GT.0.0)then
         vl=0.5*(sqrt((PCatT-Vbci)*(PCatT-Vbci)+0.01)+(PCatT-Vbci))
         vl_PCatT=0.5*((PCatT-Vbci)/sqrt(((PCatT-Vbci)*(PCatT-Vbci))+0.0
     +1)+1.0)
         vl_Vbci=0.5*(-(PCatT-Vbci)/sqrt(((PCatT-Vbci)*(PCatT-Vbci))+0.0
     +1)-1.0)
         vl_Vrth=vl_PCatT*PCatT_Vrth
         xvar2=(MC-1.0)
         xvar3=vl**xvar2
         xvar3_vl=xvar3*xvar2/vl
         xvar3_Vrth=xvar3_vl*vl_Vrth
         xvar3_Vbci=xvar3_vl*vl_Vbci
         xvar1=-AVC2atT*xvar3
         xvar1_AVC2atT=-xvar3
         xvar1_xvar3=-AVC2atT
         xvar1_Vrth=xvar1_AVC2atT*AVC2atT_Vrth
         xvar1_Vrth=xvar1_Vrth+xvar1_xvar3*xvar3_Vrth
         xvar1_Vbci=xvar1_xvar3*xvar3_Vbci
         if(xvar1.GT.100.0)then
            xvar4_xvar1=exp(100.0)
            xvar4=xvar4_xvar1*(1.0+(xvar1-100.0))
         elseif(xvar1.LT.-100.0)then
            xvar4_xvar1=exp(-100.0)
            xvar4=xvar4_xvar1*(1.0+(xvar1+100.0))
         else
            xvar4=exp(xvar1)
            xvar4_xvar1=xvar4
         endif
         xvar4_Vrth=xvar4_xvar1*xvar1_Vrth
         xvar4_Vbci=xvar4_xvar1*xvar1_Vbci
         avalf=AVC1*vl*xvar4
         avalf_vl=AVC1*xvar4
         avalf_xvar4=AVC1*vl
         avalf_Vrth=avalf_vl*vl_Vrth
         avalf_Vbci=avalf_vl*vl_Vbci
         avalf_Vrth=avalf_Vrth+avalf_xvar4*xvar4_Vrth
         avalf_Vbci=avalf_Vbci+avalf_xvar4*xvar4_Vbci
         Igc=(Itxf-Itzr-Ibcj)*avalf
         Igc_Itxf=avalf
         Igc_Itzr=-avalf
         Igc_Ibcj=-avalf
         Igc_avalf=-Itzr+Itxf-Ibcj
         Igc_Vrxf=Igc_Itxf*Itxf_Vrxf
         Igc_Vrth=Igc_Itzr*Itzr_Vrth
         Igc_Vbci=Igc_Itzr*Itzr_Vbci
         Igc_Vbei=Igc_Itzr*Itzr_Vbei
         Igc_Vrth=Igc_Vrth+Igc_Ibcj*Ibcj_Vrth
         Igc_Vbci=Igc_Vbci+Igc_Ibcj*Ibcj_Vbci
         Igc_Vrth=Igc_Vrth+Igc_avalf*avalf_Vrth
         Igc_Vbci=Igc_Vbci+Igc_avalf*avalf_Vbci
      else
         Igc=0.0
         Igc_Vrxf=0.0
         Igc_Vrth=0.0
         Igc_Vbci=0.0
         Igc_Vbei=0.0
      endif
      Ibc=Ibcj-Igc
      Ibc_Ibcj=1.0
      Ibc_Igc=-1.0
      Ibc_Vrth=Ibc_Ibcj*Ibcj_Vrth
      Ibc_Vbci=Ibc_Ibcj*Ibcj_Vbci
      Ibc_Vrxf=Ibc_Igc*Igc_Vrxf
      Ibc_Vrth=Ibc_Vrth+Ibc_Igc*Igc_Vrth
      Ibc_Vbci=Ibc_Vbci+Ibc_Igc*Igc_Vbci
      Ibc_Vbei=Ibc_Igc*Igc_Vbei
      if(RCX.GT.0.0)then
         Ircx=Vrcx/RCXatT
         Ircx_Vrcx=1.0/RCXatT
         Ircx_RCXatT=-Vrcx/(RCXatT*RCXatT)
         Ircx_Vrth=Ircx_RCXatT*RCXatT_Vrth
      else
         Ircx=0.0
         Ircx_Vrcx=0.0
         Ircx_Vrth=0.0
      endif
      argi=Vbci/Vtv
      argi_Vbci=1.0/Vtv
      argi_Vtv=-Vbci/(Vtv*Vtv)
      argi_Vrth=argi_Vtv*Vtv_Vrth
      if(argi.GT.100.0)then
         expi_argi=exp(100.0)
         expi=expi_argi*(1.0+(argi-100.0))
      elseif(argi.LT.-100.0)then
         expi_argi=exp(-100.0)
         expi=expi_argi*(1.0+(argi+100.0))
      else
         expi=exp(argi)
         expi_argi=expi
      endif
      expi_Vbci=expi_argi*argi_Vbci
      expi_Vrth=expi_argi*argi_Vrth
      argx=Vbcx/Vtv
      argx_Vbcx=1.0/Vtv
      argx_Vtv=-Vbcx/(Vtv*Vtv)
      argx_Vrth=argx_Vtv*Vtv_Vrth
      if(argx.GT.100.0)then
         expx_argx=exp(100.0)
         expx=expx_argx*(1.0+(argx-100.0))
      elseif(argx.LT.-100.0)then
         expx_argx=exp(-100.0)
         expx=expx_argx*(1.0+(argx+100.0))
      else
         expx=exp(argx)
         expx_argx=expx
      endif
      expx_Vbcx=expx_argx*argx_Vbcx
      expx_Vrth=expx_argx*argx_Vrth
      Kbci=sqrt(1.0+GAMMatT*expi)
      Kbci_GAMMatT=expi/(2.0*sqrt(expi*GAMMatT+1.0))
      Kbci_expi=GAMMatT/(2.0*sqrt(expi*GAMMatT+1.0))
      Kbci_Vrth=Kbci_GAMMatT*GAMMatT_Vrth
      Kbci_Vbci=Kbci_expi*expi_Vbci
      Kbci_Vrth=Kbci_Vrth+Kbci_expi*expi_Vrth
      Kbcx=sqrt(1.0+GAMMatT*expx)
      Kbcx_GAMMatT=expx/(2.0*sqrt(expx*GAMMatT+1.0))
      Kbcx_expx=GAMMatT/(2.0*sqrt(expx*GAMMatT+1.0))
      Kbcx_Vrth=Kbcx_GAMMatT*GAMMatT_Vrth
      Kbcx_Vbcx=Kbcx_expx*expx_Vbcx
      Kbcx_Vrth=Kbcx_Vrth+Kbcx_expx*expx_Vrth
      if(RCI.GT.0.0)then
         rKp1=(Kbci+1.0)/(Kbcx+1.0)
         rKp1_Kbci=1.0/(Kbcx+1.0)
         rKp1_Kbcx=-(Kbci+1.0)/((Kbcx+1.0)*(Kbcx+1.0))
         rKp1_Vrth=rKp1_Kbci*Kbci_Vrth
         rKp1_Vbci=rKp1_Kbci*Kbci_Vbci
         rKp1_Vrth=rKp1_Vrth+rKp1_Kbcx*Kbcx_Vrth
         rKp1_Vbcx=rKp1_Kbcx*Kbcx_Vbcx
         xvar1=log(rKp1)
         xvar1_rKp1=1.0/rKp1
         xvar1_Vrth=xvar1_rKp1*rKp1_Vrth
         xvar1_Vbci=xvar1_rKp1*rKp1_Vbci
         xvar1_Vbcx=xvar1_rKp1*rKp1_Vbcx
         Iohm=(Vrci+Vtv*(Kbci-Kbcx-xvar1))/RCIatT
         Iohm_Vrci=1.0/RCIatT
         Iohm_Vtv=(-xvar1-Kbcx+Kbci)/RCIatT
         Iohm_Kbci=Vtv/RCIatT
         Iohm_Kbcx=-Vtv/RCIatT
         Iohm_xvar1=-Vtv/RCIatT
         Iohm_RCIatT=-(Vtv*(-xvar1-Kbcx+Kbci)+Vrci)/(RCIatT*RCIatT)
         Iohm_Vrth=Iohm_Vtv*Vtv_Vrth
         Iohm_Vrth=Iohm_Vrth+Iohm_Kbci*Kbci_Vrth
         Iohm_Vbci=Iohm_Kbci*Kbci_Vbci
         Iohm_Vrth=Iohm_Vrth+Iohm_Kbcx*Kbcx_Vrth
         Iohm_Vbcx=Iohm_Kbcx*Kbcx_Vbcx
         Iohm_Vrth=Iohm_Vrth+Iohm_xvar1*xvar1_Vrth
         Iohm_Vbci=Iohm_Vbci+Iohm_xvar1*xvar1_Vbci
         Iohm_Vbcx=Iohm_Vbcx+Iohm_xvar1*xvar1_Vbcx
         Iohm_Vrth=Iohm_Vrth+Iohm_RCIatT*RCIatT_Vrth
         derf=IVO*RCIatT*Iohm/(1.0+0.5*IVO*IHRCF*sqrt(Vrci*Vrci+0.01))
         derf_IVO=Iohm*RCIatT/(0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)
     +-0.5*IHRCF*Iohm*IVO*RCIatT*sqrt((Vrci*Vrci)+0.01)/((0.5*IHRCF*IVO*
     +sqrt((Vrci*Vrci)+0.01)+1.0)*(0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+
     +1.0))
         derf_RCIatT=Iohm*IVO/(0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)
         derf_Iohm=IVO*RCIatT/(0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)
         derf_Vrci=-0.5*IHRCF*Iohm*(IVO*IVO)*RCIatT*Vrci/(sqrt((Vrci*Vrc
     +i)+0.01)*((0.5*IHRCF*IVO*sqrt((Vrci*Vrci)+0.01)+1.0)*(0.5*IHRCF*IV
     +O*sqrt((Vrci*Vrci)+0.01)+1.0)))
         derf_Vrth=derf_IVO*IVO_Vrth
         derf_Vrth=derf_Vrth+derf_RCIatT*RCIatT_Vrth
         derf_Vrci=derf_Vrci+derf_Iohm*Iohm_Vrci
         derf_Vrth=derf_Vrth+derf_Iohm*Iohm_Vrth
         derf_Vbci=derf_Iohm*Iohm_Vbci
         derf_Vbcx=derf_Iohm*Iohm_Vbcx
         Irci=Iohm/sqrt(1.0+derf*derf)
         Irci_Iohm=1.0/sqrt((derf*derf)+1.0)
         Irci_derf=-derf*Iohm/(((derf*derf)+1.0)**(3.0/2.0))
         Irci_Vrci=Irci_Iohm*Iohm_Vrci
         Irci_Vrth=Irci_Iohm*Iohm_Vrth
         Irci_Vbci=Irci_Iohm*Iohm_Vbci
         Irci_Vbcx=Irci_Iohm*Iohm_Vbcx
         Irci_Vrth=Irci_Vrth+Irci_derf*derf_Vrth
         Irci_Vrci=Irci_Vrci+Irci_derf*derf_Vrci
         Irci_Vbci=Irci_Vbci+Irci_derf*derf_Vbci
         Irci_Vbcx=Irci_Vbcx+Irci_derf*derf_Vbcx
      else
         Irci=0.0
         Irci_Vrci=0.0
         Irci_Vrth=0.0
         Irci_Vbci=0.0
         Irci_Vbcx=0.0
      endif
      if(RBX.GT.0.0)then
         Irbx=Vrbx/RBXatT
         Irbx_Vrbx=1.0/RBXatT
         Irbx_RBXatT=-Vrbx/(RBXatT*RBXatT)
         Irbx_Vrth=Irbx_RBXatT*RBXatT_Vrth
      else
         Irbx=0.0
         Irbx_Vrbx=0.0
         Irbx_Vrth=0.0
      endif
      if(RBI.GT.0.0)then
         Irbi=Vrbi*qb/RBIatT
         Irbi_Vrbi=qb/RBIatT
         Irbi_qb=Vrbi/RBIatT
         Irbi_RBIatT=-qb*Vrbi/(RBIatT*RBIatT)
         Irbi_Vrth=Irbi_qb*qb_Vrth
         Irbi_Vbei=Irbi_qb*qb_Vbei
         Irbi_Vbci=Irbi_qb*qb_Vbci
         Irbi_Vrth=Irbi_Vrth+Irbi_RBIatT*RBIatT_Vrth
      else
         Irbi=0.0
         Irbi_Vrbi=0.0
         Irbi_Vrth=0.0
         Irbi_Vbei=0.0
         Irbi_Vbci=0.0
      endif
      if(RE.GT.0.0)then
         Ire=Vre/REatT
         Ire_Vre=1.0/REatT
         Ire_REatT=-Vre/(REatT*REatT)
         Ire_Vrth=Ire_REatT*REatT_Vrth
      else
         Ire=0.0
         Ire_Vre=0.0
         Ire_Vrth=0.0
      endif
      if(RBP.GT.0.0)then
         Irbp=Vrbp*qbp/RBPatT
         Irbp_Vrbp=qbp/RBPatT
         Irbp_qbp=Vrbp/RBPatT
         Irbp_RBPatT=-qbp*Vrbp/(RBPatT*RBPatT)
         Irbp_Vrth=Irbp_qbp*qbp_Vrth
         Irbp_Vbep=Irbp_qbp*qbp_Vbep
         Irbp_Vbci=Irbp_qbp*qbp_Vbci
         Irbp_Vrth=Irbp_Vrth+Irbp_RBPatT*RBPatT_Vrth
      else
         Irbp=0.0
         Irbp_Vrbp=0.0
         Irbp_Vrth=0.0
         Irbp_Vbep=0.0
         Irbp_Vbci=0.0
      endif
      if(Ifi.GT.0.0)then
         sgIf=1.0
      else
         sgIf=0.0
      endif
      rIf=Ifi*sgIf*IITF
      rIf_Ifi=IITF*sgIf
      rIf_Vrth=rIf_Ifi*Ifi_Vrth
      rIf_Vbei=rIf_Ifi*Ifi_Vbei
      mIf=rIf/(rIf+1.0)
      mIf_rIf=1.0/(rIf+1.0)-rIf/((rIf+1.0)*(rIf+1.0))
      mIf_Vrth=mIf_rIf*rIf_Vrth
      mIf_Vbei=mIf_rIf*rIf_Vbei
      xvar1=Vbci*IVTF/1.44
      xvar1_Vbci=0.6944444*IVTF
      if(xvar1.GT.100.0)then
         xvar2_xvar1=exp(100.0)
         xvar2=xvar2_xvar1*(1.0+(xvar1-100.0))
      elseif(xvar1.LT.-100.0)then
         xvar2_xvar1=exp(-100.0)
         xvar2=xvar2_xvar1*(1.0+(xvar1+100.0))
      else
         xvar2=exp(xvar1)
         xvar2_xvar1=xvar2
      endif
      xvar2_Vbci=xvar2_xvar1*xvar1_Vbci
      tff=TF*(1.0+QTF*q1)*(1.0+XTF*xvar2*(slTF+mIf*mIf)*sgIf)
      tff_q1=QTF*TF*(sgIf*(slTF+(mIf*mIf))*XTF*xvar2+1.0)
      tff_xvar2=(q1*QTF+1.0)*sgIf*(slTF+(mIf*mIf))*TF*XTF
      tff_mIf=2.0*mIf*(q1*QTF+1.0)*sgIf*TF*XTF*xvar2
      tff_Vrth=tff_q1*q1_Vrth
      tff_Vbei=tff_q1*q1_Vbei
      tff_Vbci=tff_q1*q1_Vbci
      tff_Vbci=tff_Vbci+tff_xvar2*xvar2_Vbci
      tff_Vrth=tff_Vrth+tff_mIf*mIf_Vrth
      tff_Vbei=tff_Vbei+tff_mIf*mIf_Vbei
      Qbe=CJEatT*qdbe*WBE+tff*Ifi/qb
      Qbe_CJEatT=qdbe*WBE
      Qbe_qdbe=CJEatT*WBE
      Qbe_tff=Ifi/qb
      Qbe_Ifi=tff/qb
      Qbe_qb=-Ifi*tff/(qb*qb)
      Qbe_Vrth=Qbe_CJEatT*CJEatT_Vrth
      Qbe_Vrth=Qbe_Vrth+Qbe_qdbe*qdbe_Vrth
      Qbe_Vbei=Qbe_qdbe*qdbe_Vbei
      Qbe_Vrth=Qbe_Vrth+Qbe_tff*tff_Vrth
      Qbe_Vbei=Qbe_Vbei+Qbe_tff*tff_Vbei
      Qbe_Vbci=Qbe_tff*tff_Vbci
      Qbe_Vrth=Qbe_Vrth+Qbe_Ifi*Ifi_Vrth
      Qbe_Vbei=Qbe_Vbei+Qbe_Ifi*Ifi_Vbei
      Qbe_Vrth=Qbe_Vrth+Qbe_qb*qb_Vrth
      Qbe_Vbei=Qbe_Vbei+Qbe_qb*qb_Vbei
      Qbe_Vbci=Qbe_Vbci+Qbe_qb*qb_Vbci
      Qbex=CJEatT*qdbex*(1.0-WBE)
      Qbex_CJEatT=qdbex*(1.0-WBE)
      Qbex_qdbex=CJEatT*(1.0-WBE)
      Qbex_Vrth=Qbex_CJEatT*CJEatT_Vrth
      Qbex_Vrth=Qbex_Vrth+Qbex_qdbex*qdbex_Vrth
      Qbex_Vbex=Qbex_qdbex*qdbex_Vbex
      Qbc=CJCatT*qdbc+TR*Iri+QCO*Kbci
      Qbc_CJCatT=qdbc
      Qbc_qdbc=CJCatT
      Qbc_Iri=TR
      Qbc_Kbci=QCO
      Qbc_Vrth=Qbc_CJCatT*CJCatT_Vrth
      Qbc_Vrth=Qbc_Vrth+Qbc_qdbc*qdbc_Vrth
      Qbc_Vbci=Qbc_qdbc*qdbc_Vbci
      Qbc_Vrth=Qbc_Vrth+Qbc_Iri*Iri_Vrth
      Qbc_Vbci=Qbc_Vbci+Qbc_Iri*Iri_Vbci
      Qbc_Vrth=Qbc_Vrth+Qbc_Kbci*Kbci_Vrth
      Qbc_Vbci=Qbc_Vbci+Qbc_Kbci*Kbci_Vbci
      Qbcx=QCO*Kbcx
      Qbcx_Kbcx=QCO
      Qbcx_Vrth=Qbcx_Kbcx*Kbcx_Vrth
      Qbcx_Vbcx=Qbcx_Kbcx*Kbcx_Vbcx
      Qbep=CJEPatT*qdbep+TR*Ifp
      Qbep_CJEPatT=qdbep
      Qbep_qdbep=CJEPatT
      Qbep_Ifp=TR
      Qbep_Vrth=Qbep_CJEPatT*CJEPatT_Vrth
      Qbep_Vrth=Qbep_Vrth+Qbep_qdbep*qdbep_Vrth
      Qbep_Vbep=Qbep_qdbep*qdbep_Vbep
      Qbep_Vrth=Qbep_Vrth+Qbep_Ifp*Ifp_Vrth
      Qbep_Vbep=Qbep_Vbep+Qbep_Ifp*Ifp_Vbep
      Qbep_Vbci=Qbep_Ifp*Ifp_Vbci
      Qbeo=Vbe*CBEO
      Qbeo_Vbe=CBEO
      Qbco=Vbc*CBCO
      Qbco_Vbc=CBCO
      Ith=-(Ibe*Vbei+Ibc*Vbci+(Itxf-Itzr)*Vcei+Ibex*Vbex+Ibep*Vbep+Ircx*
     +Vrcx+Irci*Vrci+Irbx*Vrbx+Irbi*Vrbi+Ire*Vre+Irbp*Vrbp)
      Ith_Ibe=-Vbei
      Ith_Vbei=-Ibe
      Ith_Ibc=-Vbci
      Ith_Vbci=-Ibc
      Ith_Itxf=-Vcei
      Ith_Itzr=Vcei
      Ith_Vcei=Itzr-Itxf
      Ith_Ibex=-Vbex
      Ith_Vbex=-Ibex
      Ith_Ibep=-Vbep
      Ith_Vbep=-Ibep
      Ith_Ircx=-Vrcx
      Ith_Vrcx=-Ircx
      Ith_Irci=-Vrci
      Ith_Vrci=-Irci
      Ith_Irbx=-Vrbx
      Ith_Vrbx=-Irbx
      Ith_Irbi=-Vrbi
      Ith_Vrbi=-Irbi
      Ith_Ire=-Vre
      Ith_Vre=-Ire
      Ith_Irbp=-Vrbp
      Ith_Vrbp=-Irbp
      Ith_Vrth=Ith_Ibe*Ibe_Vrth
      Ith_Vbei=Ith_Vbei+Ith_Ibe*Ibe_Vbei
      Ith_Vrth=Ith_Vrth+Ith_Ibc*Ibc_Vrth
      Ith_Vbci=Ith_Vbci+Ith_Ibc*Ibc_Vbci
      Ith_Vrxf=Ith_Ibc*Ibc_Vrxf
      Ith_Vbei=Ith_Vbei+Ith_Ibc*Ibc_Vbei
      Ith_Vrxf=Ith_Vrxf+Ith_Itxf*Itxf_Vrxf
      Ith_Vrth=Ith_Vrth+Ith_Itzr*Itzr_Vrth
      Ith_Vbci=Ith_Vbci+Ith_Itzr*Itzr_Vbci
      Ith_Vbei=Ith_Vbei+Ith_Itzr*Itzr_Vbei
      Ith_Vrth=Ith_Vrth+Ith_Ibex*Ibex_Vrth
      Ith_Vbex=Ith_Vbex+Ith_Ibex*Ibex_Vbex
      Ith_Vrth=Ith_Vrth+Ith_Ibep*Ibep_Vrth
      Ith_Vbep=Ith_Vbep+Ith_Ibep*Ibep_Vbep
      Ith_Vrcx=Ith_Vrcx+Ith_Ircx*Ircx_Vrcx
      Ith_Vrth=Ith_Vrth+Ith_Ircx*Ircx_Vrth
      Ith_Vrci=Ith_Vrci+Ith_Irci*Irci_Vrci
      Ith_Vrth=Ith_Vrth+Ith_Irci*Irci_Vrth
      Ith_Vbci=Ith_Vbci+Ith_Irci*Irci_Vbci
      Ith_Vbcx=Ith_Irci*Irci_Vbcx
      Ith_Vrbx=Ith_Vrbx+Ith_Irbx*Irbx_Vrbx
      Ith_Vrth=Ith_Vrth+Ith_Irbx*Irbx_Vrth
      Ith_Vrbi=Ith_Vrbi+Ith_Irbi*Irbi_Vrbi
      Ith_Vrth=Ith_Vrth+Ith_Irbi*Irbi_Vrth
      Ith_Vbei=Ith_Vbei+Ith_Irbi*Irbi_Vbei
      Ith_Vbci=Ith_Vbci+Ith_Irbi*Irbi_Vbci
      Ith_Vre=Ith_Vre+Ith_Ire*Ire_Vre
      Ith_Vrth=Ith_Vrth+Ith_Ire*Ire_Vrth
      Ith_Vrbp=Ith_Vrbp+Ith_Irbp*Irbp_Vrbp
      Ith_Vrth=Ith_Vrth+Ith_Irbp*Irbp_Vrth
      Ith_Vbep=Ith_Vbep+Ith_Irbp*Irbp_Vbep
      Ith_Vbci=Ith_Vbci+Ith_Irbp*Irbp_Vbci
      if(RTH.GT.0.0)then
         Irth=Vrth/RTH
         Irth_Vrth=1.0/RTH
      else
         Irth=0.0
         Irth_Vrth=0.0
      endif
      Qcth=Vrth*CTH
      Qcth_Vrth=CTH
      Flxf=LEP*Ixxf
      Flxf_Ixxf=LEP
      Flxf_Vrxf=Flxf_Ixxf*Ixxf_Vrxf
      Qcxf=CEP*Vcxf
      Qcxf_Vcxf=CEP
c
c     Scale outputs
c
      if(SCALE.NE.1.0)then
         Ibe=SCALE*Ibe
         Ibe_Vrth=SCALE*Ibe_Vrth
         Ibe_Vbei=SCALE*Ibe_Vbei
         Ibex=SCALE*Ibex
         Ibex_Vrth=SCALE*Ibex_Vrth
         Ibex_Vbex=SCALE*Ibex_Vbex
         Itxf=SCALE*Itxf
         Itxf_Vrxf=SCALE*Itxf_Vrxf
         Itzr=SCALE*Itzr
         Itzr_Vrth=SCALE*Itzr_Vrth
         Itzr_Vbci=SCALE*Itzr_Vbci
         Itzr_Vbei=SCALE*Itzr_Vbei
         Ibc=SCALE*Ibc
         Ibc_Vrth=SCALE*Ibc_Vrth
         Ibc_Vbci=SCALE*Ibc_Vbci
         Ibc_Vrxf=SCALE*Ibc_Vrxf
         Ibc_Vbei=SCALE*Ibc_Vbei
         Ibep=SCALE*Ibep
         Ibep_Vrth=SCALE*Ibep_Vrth
         Ibep_Vbep=SCALE*Ibep_Vbep
         Ircx=SCALE*Ircx
         Ircx_Vrcx=SCALE*Ircx_Vrcx
         Ircx_Vrth=SCALE*Ircx_Vrth
         Irci=SCALE*Irci
         Irci_Vrci=SCALE*Irci_Vrci
         Irci_Vrth=SCALE*Irci_Vrth
         Irci_Vbci=SCALE*Irci_Vbci
         Irci_Vbcx=SCALE*Irci_Vbcx
         Irbx=SCALE*Irbx
         Irbx_Vrbx=SCALE*Irbx_Vrbx
         Irbx_Vrth=SCALE*Irbx_Vrth
         Irbi=SCALE*Irbi
         Irbi_Vrbi=SCALE*Irbi_Vrbi
         Irbi_Vrth=SCALE*Irbi_Vrth
         Irbi_Vbei=SCALE*Irbi_Vbei
         Irbi_Vbci=SCALE*Irbi_Vbci
         Ire=SCALE*Ire
         Ire_Vre=SCALE*Ire_Vre
         Ire_Vrth=SCALE*Ire_Vrth
         Irbp=SCALE*Irbp
         Irbp_Vrbp=SCALE*Irbp_Vrbp
         Irbp_Vrth=SCALE*Irbp_Vrth
         Irbp_Vbep=SCALE*Irbp_Vbep
         Irbp_Vbci=SCALE*Irbp_Vbci
         Qbe=SCALE*Qbe
         Qbe_Vrth=SCALE*Qbe_Vrth
         Qbe_Vbei=SCALE*Qbe_Vbei
         Qbe_Vbci=SCALE*Qbe_Vbci
         Qbex=SCALE*Qbex
         Qbex_Vrth=SCALE*Qbex_Vrth
         Qbex_Vbex=SCALE*Qbex_Vbex
         Qbc=SCALE*Qbc
         Qbc_Vrth=SCALE*Qbc_Vrth
         Qbc_Vbci=SCALE*Qbc_Vbci
         Qbcx=SCALE*Qbcx
         Qbcx_Vrth=SCALE*Qbcx_Vrth
         Qbcx_Vbcx=SCALE*Qbcx_Vbcx
         Qbep=SCALE*Qbep
         Qbep_Vrth=SCALE*Qbep_Vrth
         Qbep_Vbep=SCALE*Qbep_Vbep
         Qbep_Vbci=SCALE*Qbep_Vbci
         Qbeo=SCALE*Qbeo
         Qbeo_Vbe=SCALE*Qbeo_Vbe
         Qbco=SCALE*Qbco
         Qbco_Vbc=SCALE*Qbco_Vbc
         Irth=SCALE*Irth
         Irth_Vrth=SCALE*Irth_Vrth
         Ith=SCALE*Ith
         Ith_Vrth=SCALE*Ith_Vrth
         Ith_Vbei=SCALE*Ith_Vbei
         Ith_Vbci=SCALE*Ith_Vbci
         Ith_Vrxf=SCALE*Ith_Vrxf
         Ith_Vcei=SCALE*Ith_Vcei
         Ith_Vbex=SCALE*Ith_Vbex
         Ith_Vbep=SCALE*Ith_Vbep
         Ith_Vrcx=SCALE*Ith_Vrcx
         Ith_Vrci=SCALE*Ith_Vrci
         Ith_Vbcx=SCALE*Ith_Vbcx
         Ith_Vrbx=SCALE*Ith_Vrbx
         Ith_Vrbi=SCALE*Ith_Vrbi
         Ith_Vre=SCALE*Ith_Vre
         Ith_Vrbp=SCALE*Ith_Vrbp
         Qcth=SCALE*Qcth
         Qcth_Vrth=SCALE*Qcth_Vrth
         Ixzf=SCALE*Ixzf
         Ixzf_Vrth=SCALE*Ixzf_Vrth
         Ixzf_Vbei=SCALE*Ixzf_Vbei
         Ixzf_Vbci=SCALE*Ixzf_Vbci
         Ixxf=SCALE*Ixxf
         Ixxf_Vrxf=SCALE*Ixxf_Vrxf
         Qcxf=SCALE*Qcxf
         Qcxf_Vcxf=SCALE*Qcxf_Vcxf
         Flxf=SCALE*Flxf
         Flxf_Vrxf=SCALE*Flxf_Vrxf
      endif
      return
      end
