#/bin/sh

cp utils/ADMS/examples/fbh_hbt-2.1/N_DEV_ADMSHBT_X.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/fbh_hbt-2.1/N_DEV_ADMSHBT_X.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/vbic_r1.3_prerelease/N_DEV_ADMSvbic13.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/vbic_r1.3_prerelease/N_DEV_ADMSvbic13.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/vbic_r1.3_prerelease/N_DEV_ADMSvbic13_4t.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/vbic_r1.3_prerelease/N_DEV_ADMSvbic13_4t.C src/DeviceModelPKG/ADMS
cp utils/ADMS/examples/bsimcmg_107.0.0/code/N_DEV_ADMSbsimcmg.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/bsimcmg_107.0.0/code/N_DEV_ADMSbsimcmg.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/bsimcmg_107.0.0/code/*.tex doc/Reference_Guide
cp utils/ADMS/examples/BSIMCMG108.0.0_20140822/code/N_DEV_ADMSbsimcmg_108.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIMCMG108.0.0_20140822/code/N_DEV_ADMSbsimcmg_108.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIMCMG108.0.0_20140822/code/*.tex doc/Reference_Guide
cp utils/ADMS/examples/BSIMCMG110.0.0_20160101/code/N_DEV_ADMSbsimcmg_110.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIMCMG110.0.0_20160101/code/N_DEV_ADMSbsimcmg_110.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp102/N_DEV_ADMSPSP102VA.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp102/N_DEV_ADMSPSP102VA.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp102/*.tex doc/Reference_Guide
cp utils/ADMS/examples/psp103/N_DEV_ADMSPSP103VA.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/N_DEV_ADMSPSP103VA.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/N_DEV_ADMSPSP103TVA.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/N_DEV_ADMSPSP103TVA.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/N_DEV_ADMSJUNCAP200.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/N_DEV_ADMSJUNCAP200.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/psp103/*.tex doc/Reference_Guide
cp utils/ADMS/examples/mextram_504.12.1/N_DEV_ADMSbjt504va.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mextram_504.12.1/N_DEV_ADMSbjt504va.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mextram_504.12.1/N_DEV_ADMSbjt504tva.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mextram_504.12.1/N_DEV_ADMSbjt504tva.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIM6.1.1/code/N_DEV_ADMSbsim6.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIM6.1.1/code/N_DEV_ADMSbsim6.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/BSIM6.1.1/code/M_77_OutputVars.tex doc/Reference_Guide
cp utils/ADMS/examples/mvs_2.0.0/N_DEV_ADMSmvs_2_0_0_hemt.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mvs_2.0.0/N_DEV_ADMSmvs_2_0_0_etsoi.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mvs_2.0.0/N_DEV_ADMSmvs_2_0_0_hemt.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mvs_2.0.0/N_DEV_ADMSmvs_2_0_0_etsoi.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mvsg_cmc_v1.1.0/vacode/N_DEV_ADMSmvsg_cmc.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/mvsg_cmc_v1.1.0/vacode/N_DEV_ADMSmvsg_cmc.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/hicum/N_DEV_ADMShicumL2va.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/hicum/N_DEV_ADMShicumL2va.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/hicum/Q_234_OutputVars.tex doc/Reference_Guide
cp utils/ADMS/examples/hicum_l0/N_DEV_ADMShic0_full.h src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/hicum_l0/N_DEV_ADMShic0_full.C src/DeviceModelPKG/ADMS/
cp utils/ADMS/examples/hicum_l0/Q_230_OutputVars.tex doc/ReferenceGuide
cp src/DeviceModelPKG/Xyce_NonFree/Verilog/ekv301_02/N_DEV_ADMSekv3.h src/DeviceModelPKG/Xyce_NonFree
cp src/DeviceModelPKG/Xyce_NonFree/Verilog/ekv301_02/N_DEV_ADMSekv3.C src/DeviceModelPKG/Xyce_NonFree
cp src/DeviceModelPKG/Xyce_NonFree/Verilog/ekv2.6/N_DEV_ADMSekv_va.h src/DeviceModelPKG/Xyce_NonFree
cp src/DeviceModelPKG/Xyce_NonFree/Verilog/ekv2.6/N_DEV_ADMSekv_va.C src/DeviceModelPKG/Xyce_NonFree
