
#include <stdio.h>
#include <math.h>

int vbic_3T_et_xf_f(p
	,Vrth,Vbei,Vbex,Vbci,Vbep,Vrxf
	,Vrcx,Vbcx,Vrci,Vrbx,Vrbi,Vre,Vrbp
	,Vbe,Vbc,Vcei,Vcxf,Ibe,Ibex,Itxf
	,Itzr,Ibc,Ibep,Ircx,Irci,Irbx,Irbi
	,Ire,Irbp,Qbe,Qbex,Qbc,Qbcx,Qbep
	,Qbeo,Qbco,Irth,Ith,Qcth,Ixzf,Ixxf
	,Qcxf,Flxf,SCALE)
double *p
	,*Vrth,*Vbei,*Vbex,*Vbci,*Vbep,*Vrxf
	,*Vrcx,*Vbcx,*Vrci,*Vrbx,*Vrbi,*Vre,*Vrbp
	,*Vbe,*Vbc,*Vcei,*Vcxf,*Ibe,*Ibex,*Itxf
	,*Itzr,*Ibc,*Ibep,*Ircx,*Irci,*Irbx,*Irbi
	,*Ire,*Irbp,*Qbe,*Qbex,*Qbc,*Qbcx,*Qbep
	,*Qbeo,*Qbco,*Irth,*Ith,*Qcth,*Ixzf,*Ixxf
	,*Qcxf,*Flxf,*SCALE;
{
double	Tini,Tdev,Vtv,rT,dT,xvar1,IKFatT;
double	RCXatT,RCIatT,RBXatT,RBIatT,REatT,RSatT,RBPatT;
double	xvar2,xvar3,xvar4,xvar5,xvar6,ISatT,ISRRatT;
double	ISPatT,IBEIatT,IBENatT,IBCIatT,IBCNatT,IBEIPatT,IBENPatT;
double	IBCIPatT,IBCNPatT,NFatT,NRatT,AVC2atT,VBBEatT,NBBEatT;
double	psiio,psiin,PEatT,PCatT,PSatT,CJEatT,CJCatT;
double	CJEPatT,CJCPatT,GAMMatT,VOatT,EBBEatT,IVEF,IVER;
double	IIKF,IIKR,IIKP,IVO,IHRCF,IVTF,IITF;
double	slTF,LEP,CEP,dv0,dvh,pwq,qlo;
double	qhi,qdbe,mv0,vl0,q0,dv,mv;
double	vl,qdbex,qdbc,vn0,vnl0,qlo0,vn;
double	vnl,sel,crt,cmx,cl,ql,qdbep;
double	argi,expi,Ifi,Iri,q1z,q1,q2;
double	qb,Itzf,argx,expx,Ifp,q2p,qbp;
double	argn,expn,Ibcj,avalf,Igc,Kbci,Kbcx;
double	rKp1,Iohm,derf,sgIf,rIf,mIf,tff;
double	TNOM,RCX,RCI,VO,GAMM,HRCF,RBX;
double	RBI,RE,RS,RBP,IS,NF,NR;
double	FC,CBEO,CJE,PE,ME,AJE,CBCO;
double	CJC,QCO,CJEP,PC,MC,AJC,CJCP;
double	PS,MS,IBEI,WBE,NEI,IBEN,NEN;
double	IBCI,NCI,IBCN,NCN,AVC1,AVC2,ISP;
double	WSP,NFP,IBEIP,IBENP,IBCIP,NCIP,IBCNP;
double	NCNP,VEF,VER,IKF,IKR,IKP,TF;
double	QTF,XTF,VTF,ITF,TR,TD,XRE;
double	XRBI,XRCI,XRS,XVO,EA,EAIE,EAIC;
double	EAIS,EANE,EANC,EANS,XIS,XII,XIN;
double	TNF,TAVC,RTH,CTH,VRT,ART,QBM;
double	NKF,XIKF,XRCX,XRBX,XRBP,ISRR,XISR;
double	DEAR,EAP,VBBE,NBBE,IBBE,TVBBE1,TVBBE2;
double	TNBBE;

/*	Map parameter array into symbolic names */

	TNOM=p[0];
	RCX=p[1];
	RCI=p[2];
	VO=p[3];
	GAMM=p[4];
	HRCF=p[5];
	RBX=p[6];
	RBI=p[7];
	RE=p[8];
	RS=p[9];
	RBP=p[10];
	IS=p[11];
	NF=p[12];
	NR=p[13];
	FC=p[14];
	CBEO=p[15];
	CJE=p[16];
	PE=p[17];
	ME=p[18];
	AJE=p[19];
	CBCO=p[20];
	CJC=p[21];
	QCO=p[22];
	CJEP=p[23];
	PC=p[24];
	MC=p[25];
	AJC=p[26];
	CJCP=p[27];
	PS=p[28];
	MS=p[29];
	IBEI=p[31];
	WBE=p[32];
	NEI=p[33];
	IBEN=p[34];
	NEN=p[35];
	IBCI=p[36];
	NCI=p[37];
	IBCN=p[38];
	NCN=p[39];
	AVC1=p[40];
	AVC2=p[41];
	ISP=p[42];
	WSP=p[43];
	NFP=p[44];
	IBEIP=p[45];
	IBENP=p[46];
	IBCIP=p[47];
	NCIP=p[48];
	IBCNP=p[49];
	NCNP=p[50];
	VEF=p[51];
	VER=p[52];
	IKF=p[53];
	IKR=p[54];
	IKP=p[55];
	TF=p[56];
	QTF=p[57];
	XTF=p[58];
	VTF=p[59];
	ITF=p[60];
	TR=p[61];
	TD=p[62];
	XRE=p[66];
	XRBI=p[67];
	XRCI=p[68];
	XRS=p[69];
	XVO=p[70];
	EA=p[71];
	EAIE=p[72];
	EAIC=p[73];
	EAIS=p[74];
	EANE=p[75];
	EANC=p[76];
	EANS=p[77];
	XIS=p[78];
	XII=p[79];
	XIN=p[80];
	TNF=p[81];
	TAVC=p[82];
	RTH=p[83];
	CTH=p[84];
	VRT=p[85];
	ART=p[86];
	QBM=p[88];
	NKF=p[89];
	XIKF=p[90];
	XRCX=p[91];
	XRBX=p[92];
	XRBP=p[93];
	ISRR=p[94];
	XISR=p[95];
	DEAR=p[96];
	EAP=p[97];
	VBBE=p[98];
	NBBE=p[99];
	IBBE=p[100];
	TVBBE1=p[101];
	TVBBE2=p[102];
	TNBBE=p[103];

/*	Function only code */

	Tini=2.731500e+02+TNOM;
	Tdev=(2.731500e+02+TNOM)+(*Vrth);
	Vtv=1.380662e-23*Tdev/1.602189e-19;
	rT=Tdev/Tini;
	dT=Tdev-Tini;
	xvar1=pow(rT,XIKF);
	IKFatT=IKF*xvar1;
	xvar1=pow(rT,XRCX);
	RCXatT=RCX*xvar1;
	xvar1=pow(rT,XRCI);
	RCIatT=RCI*xvar1;
	xvar1=pow(rT,XRBX);
	RBXatT=RBX*xvar1;
	xvar1=pow(rT,XRBI);
	RBIatT=RBI*xvar1;
	xvar1=pow(rT,XRE);
	REatT=RE*xvar1;
	xvar1=pow(rT,XRS);
	RSatT=RS*xvar1;
	xvar1=pow(rT,XRBP);
	RBPatT=RBP*xvar1;
	xvar2=pow(rT,XIS);
	xvar3=-EA*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NF);
	xvar6=pow(xvar1,xvar5);
	ISatT=IS*xvar6;
	xvar2=pow(rT,XISR);
	xvar3=-DEAR*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NR);
	xvar6=pow(xvar1,xvar5);
	ISRRatT=ISRR*xvar6;
	xvar2=pow(rT,XIS);
	xvar3=-EAP*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NFP);
	xvar6=pow(xvar1,xvar5);
	ISPatT=ISP*xvar6;
	xvar2=pow(rT,XII);
	xvar3=-EAIE*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NEI);
	xvar6=pow(xvar1,xvar5);
	IBEIatT=IBEI*xvar6;
	xvar2=pow(rT,XIN);
	xvar3=-EANE*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NEN);
	xvar6=pow(xvar1,xvar5);
	IBENatT=IBEN*xvar6;
	xvar2=pow(rT,XII);
	xvar3=-EAIC*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCI);
	xvar6=pow(xvar1,xvar5);
	IBCIatT=IBCI*xvar6;
	xvar2=pow(rT,XIN);
	xvar3=-EANC*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCN);
	xvar6=pow(xvar1,xvar5);
	IBCNatT=IBCN*xvar6;
	xvar2=pow(rT,XII);
	xvar3=-EAIC*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCI);
	xvar6=pow(xvar1,xvar5);
	IBEIPatT=IBEIP*xvar6;
	xvar2=pow(rT,XIN);
	xvar3=-EANC*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCN);
	xvar6=pow(xvar1,xvar5);
	IBENPatT=IBENP*xvar6;
	xvar2=pow(rT,XII);
	xvar3=-EAIS*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCIP);
	xvar6=pow(xvar1,xvar5);
	IBCIPatT=IBCIP*xvar6;
	xvar2=pow(rT,XIN);
	xvar3=-EANS*(1.0-rT)/Vtv;
	xvar4=exp(xvar3);
	xvar1=(xvar2*xvar4);
	xvar5=(1.0/NCNP);
	xvar6=pow(xvar1,xvar5);
	IBCNPatT=IBCNP*xvar6;
	NFatT=NF*(1.0+dT*TNF);
	NRatT=NR*(1.0+dT*TNF);
	AVC2atT=AVC2*(1.0+dT*TAVC);
	VBBEatT=VBBE*(1.0+dT*(TVBBE1+dT*TVBBE2));
	NBBEatT=NBBE*(1.0+dT*TNBBE);
	xvar2=0.5*PE*rT/Vtv;
	xvar3=exp(xvar2);
	xvar4=-0.5*PE*rT/Vtv;
	xvar5=exp(xvar4);
	xvar1=xvar3-xvar5;
	xvar6=log(xvar1);
	psiio=2.0*(Vtv/rT)*xvar6;
	xvar1=log(rT);
	psiin=psiio*rT-3.0*Vtv*xvar1-EAIE*(rT-1.0);
	xvar2=-psiin/Vtv;
	xvar3=exp(xvar2);
	xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3));
	xvar4=log(xvar1);
	PEatT=psiin+2.0*Vtv*xvar4;
	xvar2=0.5*PC*rT/Vtv;
	xvar3=exp(xvar2);
	xvar4=-0.5*PC*rT/Vtv;
	xvar5=exp(xvar4);
	xvar1=xvar3-xvar5;
	xvar6=log(xvar1);
	psiio=2.0*(Vtv/rT)*xvar6;
	xvar1=log(rT);
	psiin=psiio*rT-3.0*Vtv*xvar1-EAIC*(rT-1.0);
	xvar2=-psiin/Vtv;
	xvar3=exp(xvar2);
	xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3));
	xvar4=log(xvar1);
	PCatT=psiin+2.0*Vtv*xvar4;
	xvar2=0.5*PS*rT/Vtv;
	xvar3=exp(xvar2);
	xvar4=-0.5*PS*rT/Vtv;
	xvar5=exp(xvar4);
	xvar1=xvar3-xvar5;
	xvar6=log(xvar1);
	psiio=2.0*(Vtv/rT)*xvar6;
	xvar1=log(rT);
	psiin=psiio*rT-3.0*Vtv*xvar1-EAIS*(rT-1.0);
	xvar2=-psiin/Vtv;
	xvar3=exp(xvar2);
	xvar1=0.5*(1.0+sqrt(1.0+4.0*xvar3));
	xvar4=log(xvar1);
	PSatT=psiin+2.0*Vtv*xvar4;
	xvar1=PE/PEatT;
	xvar2=pow(xvar1,ME);
	CJEatT=CJE*xvar2;
	xvar1=PC/PCatT;
	xvar2=pow(xvar1,MC);
	CJCatT=CJC*xvar2;
	xvar1=PC/PCatT;
	xvar2=pow(xvar1,MC);
	CJEPatT=CJEP*xvar2;
	xvar1=PS/PSatT;
	xvar2=pow(xvar1,MS);
	CJCPatT=CJCP*xvar2;
	xvar1=pow(rT,XIS);
	xvar2=-EA*(1.0-rT)/Vtv;
	xvar3=exp(xvar2);
	GAMMatT=GAMM*xvar1*xvar3;
	xvar1=pow(rT,XVO);
	VOatT=VO*xvar1;
	xvar1=-VBBEatT/(NBBEatT*Vtv);
	EBBEatT=exp(xvar1);
	if(VEF>0.0){
		IVEF=1.0/VEF;
	}else{
		IVEF=0.0;
	}
	if(VER>0.0){
		IVER=1.0/VER;
	}else{
		IVER=0.0;
	}
	if(IKF>0.0){
		IIKF=1.0/IKFatT;
	}else{
		IIKF=0.0;
	}
	if(IKR>0.0){
		IIKR=1.0/IKR;
	}else{
		IIKR=0.0;
	}
	if(IKP>0.0){
		IIKP=1.0/IKP;
	}else{
		IIKP=0.0;
	}
	if(VO>0.0){
		IVO=1.0/VOatT;
	}else{
		IVO=0.0;
	}
	if(HRCF>0.0){
		IHRCF=1.0/HRCF;
	}else{
		IHRCF=0.0;
	}
	if(VTF>0.0){
		IVTF=1.0/VTF;
	}else{
		IVTF=0.0;
	}
	if(ITF>0.0){
		IITF=1.0/ITF;
	}else{
		IITF=0.0;
	}
	if(ITF>0.0){
		slTF=0.0;
	}else{
		slTF=1.0;
	}
	if(TD>0.0){
		LEP=TD/3.0;
	}else{
		LEP=0.0;
	}
	if(TD>0.0){
		CEP=TD;
	}else{
		CEP=0.0;
	}
	dv0=-PEatT*FC;
	if(AJE<=0.0){
		dvh=(*Vbei)+dv0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-ME);
			pwq=pow(xvar1,xvar2);
			qlo=PEatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME);
			qhi=dvh*(1.0-FC+0.5*ME*dvh/PEatT)*pwq;
		}else{
			xvar1=(1.0-(*Vbei)/PEatT);
			xvar2=(1.0-ME);
			xvar3=pow(xvar1,xvar2);
			qlo=PEatT*(1.0-xvar3)/(1.0-ME);
			qhi=0.0;
		}
		qdbe=qlo+qhi;
	}else{
		mv0=sqrt(dv0*dv0+4.0*AJE*AJE);
		vl0=-0.5*(dv0+mv0);
		xvar1=(1.0-vl0/PEatT);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		q0=-PEatT*xvar3/(1.0-ME);
		dv=(*Vbei)+dv0;
		mv=sqrt(dv*dv+4.0*AJE*AJE);
		vl=0.5*(dv-mv)-dv0;
		xvar1=(1.0-vl/PEatT);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		qlo=-PEatT*xvar3/(1.0-ME);
		xvar1=(1.0-FC);
		xvar2=(-ME);
		xvar3=pow(xvar1,xvar2);
		qdbe=qlo+xvar3*((*Vbei)-vl+vl0)-q0;
	}
	dv0=-PEatT*FC;
	if(AJE<=0.0){
		dvh=(*Vbex)+dv0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-ME);
			pwq=pow(xvar1,xvar2);
			qlo=PEatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-ME);
			qhi=dvh*(1.0-FC+0.5*ME*dvh/PEatT)*pwq;
		}else{
			xvar1=(1.0-(*Vbex)/PEatT);
			xvar2=(1.0-ME);
			xvar3=pow(xvar1,xvar2);
			qlo=PEatT*(1.0-xvar3)/(1.0-ME);
			qhi=0.0;
		}
		qdbex=qlo+qhi;
	}else{
		mv0=sqrt(dv0*dv0+4.0*AJE*AJE);
		vl0=-0.5*(dv0+mv0);
		xvar1=(1.0-vl0/PEatT);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		q0=-PEatT*xvar3/(1.0-ME);
		dv=(*Vbex)+dv0;
		mv=sqrt(dv*dv+4.0*AJE*AJE);
		vl=0.5*(dv-mv)-dv0;
		xvar1=(1.0-vl/PEatT);
		xvar2=(1.0-ME);
		xvar3=pow(xvar1,xvar2);
		qlo=-PEatT*xvar3/(1.0-ME);
		xvar1=(1.0-FC);
		xvar2=(-ME);
		xvar3=pow(xvar1,xvar2);
		qdbex=qlo+xvar3*((*Vbex)-vl+vl0)-q0;
	}
	dv0=-PCatT*FC;
	if(AJC<=0.0){
		dvh=(*Vbci)+dv0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-MC);
			pwq=pow(xvar1,xvar2);
			qlo=PCatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC);
			qhi=dvh*(1.0-FC+0.5*MC*dvh/PCatT)*pwq;
		}else{
			if((VRT>0.0)&&((*Vbci)<-VRT)){
				xvar1=(1.0+VRT/PCatT);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PCatT*(1.0-xvar3*(1.0-((1.0-MC)*((*Vbci)+VRT))/(PCatT+VRT)))/(1.0-MC);
			}else{
				xvar1=(1.0-(*Vbci)/PCatT);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PCatT*(1.0-xvar3)/(1.0-MC);
			}
			qhi=0.0;
		}
		qdbc=qlo+qhi;
	}else{
		if((VRT>0.0)&&(ART>0.0)){
			vn0=(VRT+dv0)/(VRT-dv0);
			vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn0+1.0)*(vn0+1.0)+4.0*ART*ART));
			vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl0/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo0=PCatT*(1.0-xvar3)/(1.0-MC);
			vn=(2.0*(*Vbci)+VRT+dv0)/(VRT-dv0);
			vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0)*(vn+1.0)+4.0*ART*ART));
			vl=0.5*(vnl*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo=PCatT*(1.0-xvar3)/(1.0-MC);
			sel=0.5*(vnl+1.0);
			xvar1=(1.0+VRT/PCatT);
			xvar2=(-MC);
			crt=pow(xvar1,xvar2);
			xvar1=(1.0+dv0/PCatT);
			xvar2=(-MC);
			cmx=pow(xvar1,xvar2);
			cl=(1.0-sel)*crt+sel*cmx;
			ql=((*Vbci)-vl+vl0)*cl;
			qdbc=ql+qlo-qlo0;
		}else{
			mv0=sqrt(dv0*dv0+4.0*AJC*AJC);
			vl0=-0.5*(dv0+mv0);
			xvar1=(1.0-vl0/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			q0=-PCatT*xvar3/(1.0-MC);
			dv=(*Vbci)+dv0;
			mv=sqrt(dv*dv+4.0*AJC*AJC);
			vl=0.5*(dv-mv)-dv0;
			xvar1=(1.0-vl/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo=-PCatT*xvar3/(1.0-MC);
			xvar1=(1.0-FC);
			xvar2=(-MC);
			xvar3=pow(xvar1,xvar2);
			qdbc=qlo+xvar3*((*Vbci)-vl+vl0)-q0;
		}
	}
	dv0=-PCatT*FC;
	if(AJC<=0.0){
		dvh=(*Vbep)+dv0;
		if(dvh>0.0){
			xvar1=(1.0-FC);
			xvar2=(-1.0-MC);
			pwq=pow(xvar1,xvar2);
			qlo=PCatT*(1.0-pwq*(1.0-FC)*(1.0-FC))/(1.0-MC);
			qhi=dvh*(1.0-FC+0.5*MC*dvh/PCatT)*pwq;
		}else{
			if((VRT>0.0)&&((*Vbep)<-VRT)){
				xvar1=(1.0+VRT/PCatT);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PCatT*(1.0-xvar3*(1.0-((1.0-MC)*((*Vbep)+VRT))/(PCatT+VRT)))/(1.0-MC);
			}else{
				xvar1=(1.0-(*Vbep)/PCatT);
				xvar2=(1.0-MC);
				xvar3=pow(xvar1,xvar2);
				qlo=PCatT*(1.0-xvar3)/(1.0-MC);
			}
			qhi=0.0;
		}
		qdbep=qlo+qhi;
	}else{
		if((VRT>0.0)&&(ART>0.0)){
			vn0=(VRT+dv0)/(VRT-dv0);
			vnl0=2.0*vn0/(sqrt((vn0-1.0)*(vn0-1.0)+4.0*AJC*AJC)+sqrt((vn0+1.0)*(vn0+1.0)+4.0*ART*ART));
			vl0=0.5*(vnl0*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl0/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo0=PCatT*(1.0-xvar3)/(1.0-MC);
			vn=(2.0*(*Vbep)+VRT+dv0)/(VRT-dv0);
			vnl=2.0*vn/(sqrt((vn-1.0)*(vn-1.0)+4.0*AJC*AJC)+sqrt((vn+1.0)*(vn+1.0)+4.0*ART*ART));
			vl=0.5*(vnl*(VRT-dv0)-VRT-dv0);
			xvar1=(1.0-vl/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo=PCatT*(1.0-xvar3)/(1.0-MC);
			sel=0.5*(vnl+1.0);
			xvar1=(1.0+VRT/PCatT);
			xvar2=(-MC);
			crt=pow(xvar1,xvar2);
			xvar1=(1.0+dv0/PCatT);
			xvar2=(-MC);
			cmx=pow(xvar1,xvar2);
			cl=(1.0-sel)*crt+sel*cmx;
			ql=((*Vbep)-vl+vl0)*cl;
			qdbep=ql+qlo-qlo0;
		}else{
			mv0=sqrt(dv0*dv0+4.0*AJC*AJC);
			vl0=-0.5*(dv0+mv0);
			xvar1=(1.0-vl0/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			q0=-PCatT*xvar3/(1.0-MC);
			dv=(*Vbep)+dv0;
			mv=sqrt(dv*dv+4.0*AJC*AJC);
			vl=0.5*(dv-mv)-dv0;
			xvar1=(1.0-vl/PCatT);
			xvar2=(1.0-MC);
			xvar3=pow(xvar1,xvar2);
			qlo=-PCatT*xvar3/(1.0-MC);
			xvar1=(1.0-FC);
			xvar2=(-MC);
			xvar3=pow(xvar1,xvar2);
			qdbep=qlo+xvar3*((*Vbep)-vl+vl0)-q0;
		}
	}
	argi=(*Vbei)/(NFatT*Vtv);
	expi=exp(argi);
	Ifi=ISatT*(expi-1.0);
	argi=(*Vbci)/(NRatT*Vtv);
	expi=exp(argi);
	Iri=ISatT*ISRRatT*(expi-1.0);
	q1z=1.0+qdbe*IVER+qdbc*IVEF;
	q1=0.5*(sqrt((q1z-1.0e-4)*(q1z-1.0e-4)+1.0e-8)+q1z-1.0e-4)+1.0e-4;
	q2=Ifi*IIKF+Iri*IIKR;
	if(QBM<0.5){
		xvar2=1.0/NKF;
		xvar3=pow(q1,xvar2);
		xvar1=(xvar3+4.0*q2);
		xvar4=pow(xvar1,NKF);
		qb=0.5*(q1+xvar4);
	}else{
		xvar1=(1.0+4.0*q2);
		xvar2=pow(xvar1,NKF);
		qb=0.5*q1*(1.0+xvar2);
	}
	(*Itzr)=Iri/qb;
	Itzf=Ifi/qb;
	(*Ixzf)=-Itzf;
	(*Itxf)=(*Vrxf);
	(*Ixxf)=(*Vrxf);
	if(ISP>0.0){
		argi=(*Vbep)/(NFP*Vtv);
		expi=exp(argi);
		argx=(*Vbci)/(NFP*Vtv);
		expx=exp(argx);
		Ifp=ISPatT*(WSP*expi+(1.0-WSP)*expx-1.0);
		q2p=Ifp*IIKP;
		qbp=0.5*(1.0+sqrt(1.0+4.0*q2p));
	}else{
		Ifp=0.0;
		qbp=1.0;
	}
	if(WBE==1.0){
		argi=(*Vbei)/(NEI*Vtv);
		expi=exp(argi);
		argn=(*Vbei)/(NEN*Vtv);
		expn=exp(argn);
		if(VBBE>0.0){
			argx=(-VBBEatT-(*Vbei))/(NBBEatT*Vtv);
			expx=exp(argx);
			(*Ibe)=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEatT);
		}else{
			(*Ibe)=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0);
		}
		(*Ibex)=0.0;
	}else if(WBE==0.0){
		(*Ibe)=0.0;
		argi=(*Vbex)/(NEI*Vtv);
		expi=exp(argi);
		argn=(*Vbex)/(NEN*Vtv);
		expn=exp(argn);
		if(VBBE>0.0){
			argx=(-VBBEatT-(*Vbex))/(NBBEatT*Vtv);
			expx=exp(argx);
			(*Ibex)=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEatT);
		}else{
			(*Ibex)=IBEIatT*(expi-1.0)+IBENatT*(expn-1.0);
		}
	}else{
		argi=(*Vbei)/(NEI*Vtv);
		expi=exp(argi);
		argn=(*Vbei)/(NEN*Vtv);
		expn=exp(argn);
		if(VBBE>0.0){
			argx=(-VBBEatT-(*Vbei))/(NBBEatT*Vtv);
			expx=exp(argx);
			(*Ibe)=WBE*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEatT));
		}else{
			(*Ibe)=WBE*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0));
		}
		argi=(*Vbex)/(NEI*Vtv);
		expi=exp(argi);
		argn=(*Vbex)/(NEN*Vtv);
		expn=exp(argn);
		if(VBBE>0.0){
			argx=(-VBBEatT-(*Vbex))/(NBBEatT*Vtv);
			expx=exp(argx);
			(*Ibex)=(1.0-WBE)*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0)-IBBE*(expx-EBBEatT));
		}else{
			(*Ibex)=(1.0-WBE)*(IBEIatT*(expi-1.0)+IBENatT*(expn-1.0));
		}
	}
	argi=(*Vbci)/(NCI*Vtv);
	expi=exp(argi);
	argn=(*Vbci)/(NCN*Vtv);
	expn=exp(argn);
	Ibcj=IBCIatT*(expi-1.0)+IBCNatT*(expn-1.0);
	if((IBEIP>0.0)||(IBENP>0.0)){
		argi=(*Vbep)/(NCI*Vtv);
		expi=exp(argi);
		argn=(*Vbep)/(NCN*Vtv);
		expn=exp(argn);
		(*Ibep)=IBEIPatT*(expi-1.0)+IBENPatT*(expn-1.0);
	}else{
		(*Ibep)=0.0;
	}
	if(AVC1>0.0){
		vl=0.5*(sqrt((PCatT-(*Vbci))*(PCatT-(*Vbci))+0.01)+(PCatT-(*Vbci)));
		xvar2=(MC-1.0);
		xvar3=pow(vl,xvar2);
		xvar1=-AVC2atT*xvar3;
		xvar4=exp(xvar1);
		avalf=AVC1*vl*xvar4;
		Igc=((*Itxf)-(*Itzr)-Ibcj)*avalf;
	}else{
		Igc=0.0;
	}
	(*Ibc)=Ibcj-Igc;
	if(RCX>0.0){
		(*Ircx)=(*Vrcx)/RCXatT;
	}else{
		(*Ircx)=0.0;
	}
	argi=(*Vbci)/Vtv;
	expi=exp(argi);
	argx=(*Vbcx)/Vtv;
	expx=exp(argx);
	Kbci=sqrt(1.0+GAMMatT*expi);
	Kbcx=sqrt(1.0+GAMMatT*expx);
	if(RCI>0.0){
		rKp1=(Kbci+1.0)/(Kbcx+1.0);
		xvar1=log(rKp1);
		Iohm=((*Vrci)+Vtv*(Kbci-Kbcx-xvar1))/RCIatT;
		derf=IVO*RCIatT*Iohm/(1.0+0.5*IVO*IHRCF*sqrt((*Vrci)*(*Vrci)+0.01));
		(*Irci)=Iohm/sqrt(1.0+derf*derf);
	}else{
		(*Irci)=0.0;
	}
	if(RBX>0.0){
		(*Irbx)=(*Vrbx)/RBXatT;
	}else{
		(*Irbx)=0.0;
	}
	if(RBI>0.0){
		(*Irbi)=(*Vrbi)*qb/RBIatT;
	}else{
		(*Irbi)=0.0;
	}
	if(RE>0.0){
		(*Ire)=(*Vre)/REatT;
	}else{
		(*Ire)=0.0;
	}
	if(RBP>0.0){
		(*Irbp)=(*Vrbp)*qbp/RBPatT;
	}else{
		(*Irbp)=0.0;
	}
	if(Ifi>0.0){
		sgIf=1.0;
	}else{
		sgIf=0.0;
	}
	rIf=Ifi*sgIf*IITF;
	mIf=rIf/(rIf+1.0);
	xvar1=(*Vbci)*IVTF/1.44;
	xvar2=exp(xvar1);
	tff=TF*(1.0+QTF*q1)*(1.0+XTF*xvar2*(slTF+mIf*mIf)*sgIf);
	(*Qbe)=CJEatT*qdbe*WBE+tff*Ifi/qb;
	(*Qbex)=CJEatT*qdbex*(1.0-WBE);
	(*Qbc)=CJCatT*qdbc+TR*Iri+QCO*Kbci;
	(*Qbcx)=QCO*Kbcx;
	(*Qbep)=CJEPatT*qdbep+TR*Ifp;
	(*Qbeo)=(*Vbe)*CBEO;
	(*Qbco)=(*Vbc)*CBCO;
	(*Ith)=-((*Ibe)*(*Vbei)+(*Ibc)*(*Vbci)+((*Itxf)-(*Itzr))*(*Vcei)+(*Ibex)*(*Vbex)+(*Ibep)*(*Vbep)+(*Ircx)*(*Vrcx)+(*Irci)*(*Vrci)+(*Irbx)*(*Vrbx)+(*Irbi)*(*Vrbi)+(*Ire)*(*Vre)+(*Irbp)*(*Vrbp));
	if(RTH>0.0){
		(*Irth)=(*Vrth)/RTH;
	}else{
		(*Irth)=0.0;
	}
	(*Qcth)=(*Vrth)*CTH;
	(*Flxf)=LEP*(*Ixxf);
	(*Qcxf)=CEP*(*Vcxf);

/*	Scale outputs */
	if(*SCALE!=1.0){
		*Ibe=(*SCALE)*(*Ibe);
		*Ibex=(*SCALE)*(*Ibex);
		*Itxf=(*SCALE)*(*Itxf);
		*Itzr=(*SCALE)*(*Itzr);
		*Ibc=(*SCALE)*(*Ibc);
		*Ibep=(*SCALE)*(*Ibep);
		*Ircx=(*SCALE)*(*Ircx);
		*Irci=(*SCALE)*(*Irci);
		*Irbx=(*SCALE)*(*Irbx);
		*Irbi=(*SCALE)*(*Irbi);
		*Ire=(*SCALE)*(*Ire);
		*Irbp=(*SCALE)*(*Irbp);
		*Qbe=(*SCALE)*(*Qbe);
		*Qbex=(*SCALE)*(*Qbex);
		*Qbc=(*SCALE)*(*Qbc);
		*Qbcx=(*SCALE)*(*Qbcx);
		*Qbep=(*SCALE)*(*Qbep);
		*Qbeo=(*SCALE)*(*Qbeo);
		*Qbco=(*SCALE)*(*Qbco);
		*Irth=(*SCALE)*(*Irth);
		*Ith=(*SCALE)*(*Ith);
		*Qcth=(*SCALE)*(*Qcth);
		*Ixzf=(*SCALE)*(*Ixzf);
		*Ixxf=(*SCALE)*(*Ixxf);
		*Qcxf=(*SCALE)*(*Qcxf);
		*Flxf=(*SCALE)*(*Flxf);
	}
	return(0);
}
