include:
  - gitlab-ci/variables/build-var-sets.yml

.build_test_install_xyce:
  extends: .build_base
  stage: buildTestInstallXyce
  dependencies: []
  variables:
    GoogleUnitTesting: "OFF"
    XYCE_NO_TRACKING: "TRUE"
    BuildWithMPI: "OFF"
    cmakeBuildType: "Release"
    # variables for xyce-ctest.cmake. typically do NOT want to modify
    # these
    branch: ${XyceBranch}
    TESTSET: Experimental
    WORKSPACE: $CI_PROJECT_DIR
    GTest_ROOT: /projects/xyce/GTest/RHEL7
    ExcludeTestLabel: ""
    cmakeArgsList: |
      --log-level=STATUS;\
      -DXyce_REGRESSION=ON;\
      -DXyce_USE_FFT=ON;\
      -DXyce_PLUGIN_SUPPORT=BLD_SHARED_TEMPLATE;\
      -DBUILD_SHARED_LIBS=BLD_SHARED_TEMPLATE;\
      -DCMAKE_BUILD_TYPE=${cmakeBuildType};\
      -DBUILD_TESTING=ON;\
      -DXyce_GTEST_UNIT_TESTS=${GoogleUnitTesting};\
      -DXyce_PARALLEL_MPI=${BuildWithMPI};\
      -DXyce_RAD_MODELS=ON;\
      -DXyce_USE_CURL=ON;\
      -DXyce_TRACKING_URL=http://morannon.sandia.gov/Xyce_Stats/cgi-bin/collectstats.pl;\
      -DXyce_AS_SPECIAL_CHARON_TPL=OFF;\
      -DCMAKE_INSTALL_PREFIX=${xyceInstallDir}
      
  script:
    - set -euo pipefail
    # activate python virtual for xyce build and test
    - source /projects/xyce_user/pythonVirtEnv/Xyce/bin/activate
    - cloneAllXyceRepos
    # so admsXml will be found
    - export PATH="${PATH}:${admsInstallDir}/${optStr}/bin"
    # remove backslashes and newline characters from list for proper
    # parsing by ctest script
    - rawCmakeArgsList=$(echo ${cmakeArgsList} | sed "s/BLD_SHARED_TEMPLATE/${buildShared}/g" | tr -d '\\\n')
    # this appears on the dashboard under "Build Name"
    - export MYBUILDNAME=Xyce/${XYCE_INSTALL_STRING}/${optStr}/${libTypeStr}-${archFullName}
    - echo "MYBUILDNAME=${MYBUILDNAME}"
    # only doing links against dynamic libraries for now
    - export Trilinos_DIR=${trilinosInstallDir}/${optStr}/${libTypeStr}
    - echo "Trilinos_DIR=${Trilinos_DIR}"
    # note use of the use of the pipeline's xyce-ctest.cmake file, NOT
    # the build repos copy
    - |
      ctest --timeout 600 -DVERBOSITY=5 -C ${cmakeBuildType} \
        -DUSE_GITLAB_CI_TESTING=ON \
        -DEXCLUDE_TESTS_WITH_LABEL="${ExcludeTestLabel}" \
        -DCMAKE_ARGS_LIST="${rawCmakeArgsList}" \
        -S ${CI_PROJECT_DIR}/cmake/ctest/xyce-ctest.cmake
    # clean out the installation directory
    - cleanInstallDir "${xyceInstallDir}"
    - cmake --install ${CI_PROJECT_DIR}/repos/build --config ${cmakeBuildType}
  artifacts:
    paths:
      - repos/build
      - slurm*.out
    expire_in: 1 month
    exclude:
      - repos/build/**/*.o
      - repos/build/**/*.so*
      - repos/build/**/*.a
      - repos/build/**/*.d
      - repos/build/**/Xyce
    when: always
  rules:
    - if: '$DO_XYCE_BUILDS == "ON" && $CI_PIPELINE_SOURCE == "trigger"'
  
# Begin concrete gitlab CI stages
GNU_serial.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce
    - .gnu_serial_vars
  needs:
    - job: GNU_serial.dyn.buildTPLs
      artifacts: false
      optional: true

GNU_OpenMPI.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce
    - .gnu_openmpi_vars
  variables:
     ExcludeTestLabel: "timesensitive"
  needs:
    - job: GNU_OpenMPI.dyn.buildTPLs
      artifacts: false
      optional: true

GNU_OpenMPI.Debug.buildTestInstallXyce:
  extends:
     - .build_test_install_xyce
     - .gnu_openmpi_vars
  variables:
     cmakeBuildType: "Debug"
     ExcludeTestLabel: "timesensitive"
  needs:
    - job: GNU_OpenMPI.dyn.Debug.buildTPLs
      artifacts: false
      optional: true

Intel_serial.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce
    - .intel_serial_vars
  needs:
    - job: Intel_serial.dyn.buildTPLs
      artifacts: false
      optional: true

Intel_OpenMPI.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce
    - .intel_openmpi_vars
  variables:
     ExcludeTestLabel: "timesensitive"
  needs:
    - job: Intel_OpenMPI.dyn.buildTPLs
      artifacts: false
      optional: true

.build_test_install_xyce_cts:
  extends: .build_test_install_xyce
  script:
    - set -euo pipefail
    - cloneAllXyceRepos
    # this appears on the dashboard under "Build Name"
    - export MYBUILDNAME=Xyce/${XYCE_INSTALL_STRING}/${optStr}/${libTypeStr}-${archFullName}
    - echo "MYBUILDNAME=${MYBUILDNAME}"
    # only doing links against dynamic libraries for now
    - export Trilinos_DIR=${trilinosInstallDir}/${optStr}/${libTypeStr}
    - echo "Trilinos_DIR=${Trilinos_DIR}"
    # so admsXml will be found
    - export PATH="${PATH}:${admsInstallDir}/${optStr}/bin"
    - rawCmakeArgsList=$(echo ${cmakeArgsList} | sed "s/BLD_SHARED_TEMPLATE/${buildShared}/g" | tr -d '\\\\\n')
    - |
      case $(hostname) in
        flight*)
          SBATCH_EXTRA_ARGS="--reservation=condo-ascic-ci ${CTS_LICENSE_ARG}"
          ;;
        *)
          SBATCH_EXTRA_ARGS="${CTS_LICENSE_ARG}"
          ;;
      esac
    - echo "Trilinos_DIR=${Trilinos_DIR}"
    - rm -f slurm*.out
    - sbatch ${SBATCH_EXTRA_ARGS}
        --wait
        --time=3:59:00
        --job-name=xyce_ci
        --account=FY200136
        --partition=short,batch
        ${CI_PROJECT_DIR}/gitlab-ci/cts-sbatch-ctest.sh "${rawCmakeArgsList}" "${xyceInstallDir}" "${CI_PROJECT_DIR}" "${ExcludeTestLabel}"
    # clean out the installation directory
    - cleanInstallDir "${xyceInstallDir}"
    - cmake --install ${CI_PROJECT_DIR}/repos/build --config ${cmakeBuildType}

GNU_OpenMPI.cts.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce_cts
    - .gnu_openmpi_cts_vars
  variables:
    CUSTOM_CI_BUILDS_DIR: "/gpfs/${GITLAB_USER_LOGIN}/jacamar-ci"
    ExcludeTestLabel: "timesensitive"
  needs:
    - job: GNU_OpenMPI.cts.buildTPLs
      artifacts: false
      optional: true

GNU_serial.cts.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce_cts
    - .gnu_serial_cts_vars
  variables:
    CUSTOM_CI_BUILDS_DIR: "/gpfs/${GITLAB_USER_LOGIN}/jacamar-ci"
  needs:
    - job: GNU_serial.cts.buildTPLs
      artifacts: false
      optional: true

Intel_OpenMPI.cts.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce_cts
    - .intel_openmpi_cts_vars
  variables:
    ExcludeTestLabel: "timesensitive"
    CUSTOM_CI_BUILDS_DIR: "/gpfs/${GITLAB_USER_LOGIN}/jacamar-ci"
  needs:
    - job: Intel_OpenMPI.cts.buildTPLs
      artifacts: false
      optional: true

Intel_serial.cts.buildTestInstallXyce:
  extends:
    - .build_test_install_xyce_cts
    - .intel_serial_cts_vars
  variables:
    CUSTOM_CI_BUILDS_DIR: "/gpfs/${GITLAB_USER_LOGIN}/jacamar-ci"
  needs:
    - job: Intel_serial.cts.buildTPLs
      artifacts: false
      optional: true
