# this is distinct from the installation so that static and dynamic
# builds can be installed into the same directory and all of them are
# cleaned up here.
.clean_tpl_installs:
  extends: .build_base
  stage: cleanTPLInstalls
  variables:
    # no need to clone repo
    GIT_STRATEGY: none
  script:
    - cleanInstallDir "${admsInstallDir}/${optStr}"
    - cleanInstallDir "${ssInstallDir}/${optStr}/${libTypeStr}"
    - cleanInstallDir "${trilinosInstallDir}/${optStr}/${libTypeStr}"
  rules:
    # always do cleanup if TPLs are building
    - if: $DO_TPL_BUILDS == "ON" && $CI_PIPELINE_SOURCE == "trigger" 

GNU_serial.cleanup:
  extends:
    - .clean_tpl_installs
    - .gnu_serial_vars

GNU_OpenMPI.cleanup:
  extends:
    - .clean_tpl_installs
    - .gnu_openmpi_vars

GNU_OpenMPI.Debug.cleanup:
  variables:
    cmakeBuildType: "Debug"
  extends:
    - .clean_tpl_installs
    - .gnu_openmpi_vars

Intel_serial.cleanup:
  extends:
    - .clean_tpl_installs
    - .intel_serial_vars

Intel_OpenMPI.cleanup:
  extends:
    - .clean_tpl_installs
    - .intel_openmpi_vars

GNU_OpenMPI.cts.cleanup:
  extends:
    - .clean_tpl_installs
    - .gnu_openmpi_cts_vars

GNU_serial.cts.cleanup:
  extends:
    - .clean_tpl_installs
    - .gnu_serial_cts_vars

Intel_OpenMPI.cts.cleanup:
  extends:
    - .clean_tpl_installs
    - .intel_openmpi_cts_vars

Intel_serial.cts.cleanup:
  extends:
    - .clean_tpl_installs
    - .intel_serial_cts_vars
